import {
  A7_PRODUCT_COMMAND_CONTRACT_NAME,
  A7_PRODUCT_COMMAND_CONTRACT_VERSION,
  A7_PRODUCT_COMMAND_IDENTITY_NAMESPACE,
  A7_PRODUCT_OPERATION_IDENTITY_NAMESPACE,
  A7_PRODUCT_COMMAND_INTERNAL_IDEMPOTENCY_SCOPE,
  A7_PRODUCT_COMMAND_PROVIDER_IDEMPOTENCY_SCOPE,
  A7_PRODUCT_COMMAND_IDEMPOTENCY_RETENTION_SECONDS,
  A7_PRODUCT_COMMAND_AUDIT_ENTITY_TYPE,
  A7_PRODUCT_COMMAND_AUDIT_ACTOR,
  A7_PRODUCT_COMMAND_AUDIT_ACTION_RESERVED,
  A7_PRODUCT_COMMAND_AUDIT_ACTION_ADMITTED,
  A7_PRODUCT_COMMAND_AUDIT_ACTION_COMPLETED,
  A7_PRODUCT_COMMAND_AUDIT_ACTION_FAILED,
  A7_PRODUCT_COMMAND_AUDIT_ACTION_REPLAYED,
  A7_PRODUCT_COMMAND_AUDIT_ACTION_CONFLICTED,
  A7_PRODUCT_COMMAND_OUTBOX_EVENT_TYPE,
  A7_PRODUCT_COMMAND_OUTBOX_EVENT_CLASSIFICATION,
  A7_PRODUCT_COMMAND_OUTBOX_EVENT_RETENTION_CLASS,
  A7_PRODUCT_COMMAND_OPERATION_STATES,
  A7_PRODUCT_COMMAND_OPERATION_STATE_RESERVED,
  A7_PRODUCT_COMMAND_OPERATION_STATE_ADMITTED,
  A7_PRODUCT_COMMAND_OPERATION_STATE_COMPLETED,
  A7_PRODUCT_COMMAND_OPERATION_STATE_FAILED,
  A7_PRODUCT_COMMAND_OPERATION_STATE_REPLAYED,
  A7_PRODUCT_COMMAND_OPERATION_STATE_CONFLICTED,
  A7_PRODUCT_COMMAND_ASSIGN_STATES,
  A7_PRODUCT_COMMAND_FUNDING_STATES,
  A7_PRODUCT_COMMAND_ALL_STATES,
  A7_PRODUCT_COMMAND_CAPABILITY_ASSIGN,
  A7_PRODUCT_COMMAND_CAPABILITY_INBOUND_FUNDING,
  A7_PRODUCT_COMMAND_ACTION_ASSIGN,
  A7_PRODUCT_COMMAND_ACTION_LIFECYCLE,
  A7_PRODUCT_COMMAND_PARTNER_KEY,
  A7_PRODUCT_COMMAND_PARTNER_CAPABILITY,
  A7_PRODUCT_COMMAND_PARTNER_OPERATION,
  A7_PRODUCT_COMMAND_FAILURE_A2_AUTHORIZATION_MISSING,
  A7_PRODUCT_COMMAND_FAILURE_A2_AUTHORIZATION_STALE,
  A7_PRODUCT_COMMAND_FAILURE_A2_AUTHORIZATION_DENIED,
  A7_PRODUCT_COMMAND_FAILURE_A3_BINDING_MISSING,
  A7_PRODUCT_COMMAND_FAILURE_A3_BINDING_NOT_ACTIVE,
  A7_PRODUCT_COMMAND_FAILURE_A3_STALE_BINDING,
  A7_PRODUCT_COMMAND_FAILURE_A4_POLICY_DECISION_MISSING,
  A7_PRODUCT_COMMAND_FAILURE_A4_POLICY_DECISION_EXPIRED,
  A7_PRODUCT_COMMAND_FAILURE_A4_POLICY_DECISION_NOT_EXECUTABLE,
  A7_PRODUCT_COMMAND_FAILURE_A7T04_PRODUCT_CUSTOMER_BINDING_MISSING,
  A7_PRODUCT_COMMAND_FAILURE_A7T04_PRODUCT_CUSTOMER_BINDING_FAILED,
  A7_PRODUCT_COMMAND_FAILURE_A6_EXTERNAL_OPERATION_MISSING,
  A7_PRODUCT_COMMAND_FAILURE_A6_EXTERNAL_OPERATION_NOT_FOUND,
  A7_PRODUCT_COMMAND_FAILURE_A6_EXTERNAL_OPERATION_MAPPING_CONFLICT,
  A7_PRODUCT_COMMAND_FAILURE_A6_EXTERNAL_OPERATION_CONTEXT_MISMATCH,
  A7_PRODUCT_COMMAND_FAILURE_REQUEST_HASH_CONFLICT,
  A7_PRODUCT_COMMAND_FAILURE_IDEMPOTENCY_IN_PROGRESS,
  A7_PRODUCT_COMMAND_FAILURE_PRODUCT_CATALOG_REJECTED,
  A7_PRODUCT_COMMAND_FAILURE_CURRENCY_MISMATCH,
  A7_PRODUCT_COMMAND_FAILURE_ACCOUNTING_UNIT_MISMATCH,
  A7_PRODUCT_COMMAND_FAILURE_AMOUNT_INVALID,
  A7_PRODUCT_COMMAND_FAILURE_OPERATIONS_EVIDENCE_UNAVAILABLE,
  A7_PRODUCT_COMMAND_REFERENCE_PREFIX,
  A7_PRODUCT_OPERATION_REFERENCE_PREFIX,
} from '../src/policy/a7-product-command.constants';

describe('A7 product command constants (A7T05)', () => {
  it('freezes the A7 product command contract name and version', () => {
    expect(A7_PRODUCT_COMMAND_CONTRACT_NAME).toBe('A7-PRODUCT-COMMAND');
    expect(A7_PRODUCT_COMMAND_CONTRACT_VERSION).toBe(1);
  });

  it('freezes the A7 product command identity namespaces', () => {
    expect(A7_PRODUCT_COMMAND_IDENTITY_NAMESPACE).toBe('A7-PRODUCT-COMMAND');
    expect(A7_PRODUCT_OPERATION_IDENTITY_NAMESPACE).toBe('A7-PRODUCT-OPERATION');
  });

  it('separates the A7 internal idempotency scope from the A6T05 provider idempotency scope', () => {
    expect(A7_PRODUCT_COMMAND_INTERNAL_IDEMPOTENCY_SCOPE).toBe('A7-PRODUCT-IDEMPOTENCY.v1');
    expect(A7_PRODUCT_COMMAND_PROVIDER_IDEMPOTENCY_SCOPE).toBe('nibss.nip.external-operation.v1');
    expect(A7_PRODUCT_COMMAND_INTERNAL_IDEMPOTENCY_SCOPE).not.toBe(
      A7_PRODUCT_COMMAND_PROVIDER_IDEMPOTENCY_SCOPE,
    );
  });

  it('aligns the A7 product command idempotency retention with Operations', () => {
    expect(A7_PRODUCT_COMMAND_IDEMPOTENCY_RETENTION_SECONDS).toBe(86_400);
  });

  it('freezes the A7 product command audit entity type and actor', () => {
    expect(A7_PRODUCT_COMMAND_AUDIT_ENTITY_TYPE).toBe('A7_PRODUCT_COMMAND');
    expect(A7_PRODUCT_COMMAND_AUDIT_ACTOR).toBe('a7-product-command');
  });

  it('freezes the A7 product command audit action codes', () => {
    expect(A7_PRODUCT_COMMAND_AUDIT_ACTION_RESERVED).toBe('A7_PRODUCT_COMMAND_RESERVED');
    expect(A7_PRODUCT_COMMAND_AUDIT_ACTION_ADMITTED).toBe('A7_PRODUCT_COMMAND_ADMITTED');
    expect(A7_PRODUCT_COMMAND_AUDIT_ACTION_COMPLETED).toBe('A7_PRODUCT_COMMAND_COMPLETED');
    expect(A7_PRODUCT_COMMAND_AUDIT_ACTION_FAILED).toBe('A7_PRODUCT_COMMAND_FAILED');
    expect(A7_PRODUCT_COMMAND_AUDIT_ACTION_REPLAYED).toBe('A7_PRODUCT_COMMAND_REPLAYED');
    expect(A7_PRODUCT_COMMAND_AUDIT_ACTION_CONFLICTED).toBe('A7_PRODUCT_COMMAND_CONFLICTED');
  });

  it('freezes the A7 product command outbox event type, classification, and retention class', () => {
    expect(A7_PRODUCT_COMMAND_OUTBOX_EVENT_TYPE).toBe('A7ProductCommandAdmitted');
    expect(A7_PRODUCT_COMMAND_OUTBOX_EVENT_CLASSIFICATION).toBe('INTERNAL_OPERATIONS');
    expect(A7_PRODUCT_COMMAND_OUTBOX_EVENT_RETENTION_CLASS).toBe('OPERATIONS_DEFAULT');
  });

  it('freezes the A7 product command operation state vocabulary', () => {
    expect(A7_PRODUCT_COMMAND_OPERATION_STATES).toEqual([
      A7_PRODUCT_COMMAND_OPERATION_STATE_RESERVED,
      A7_PRODUCT_COMMAND_OPERATION_STATE_ADMITTED,
      A7_PRODUCT_COMMAND_OPERATION_STATE_COMPLETED,
      A7_PRODUCT_COMMAND_OPERATION_STATE_FAILED,
      A7_PRODUCT_COMMAND_OPERATION_STATE_REPLAYED,
      A7_PRODUCT_COMMAND_OPERATION_STATE_CONFLICTED,
    ]);
    expect(A7_PRODUCT_COMMAND_OPERATION_STATES).toContain('COMMAND_RESERVED');
    expect(A7_PRODUCT_COMMAND_OPERATION_STATES).toContain('COMMAND_ADMITTED');
    expect(A7_PRODUCT_COMMAND_OPERATION_STATES).toContain('COMMAND_COMPLETED');
    expect(A7_PRODUCT_COMMAND_OPERATION_STATES).toContain('COMMAND_FAILED');
    expect(A7_PRODUCT_COMMAND_OPERATION_STATES).toContain('COMMAND_REPLAYED');
    expect(A7_PRODUCT_COMMAND_OPERATION_STATES).toContain('COMMAND_CONFLICTED');
  });

  it('reuses the A7 product-state vocabulary from the A7T02 product catalog', () => {
    expect(A7_PRODUCT_COMMAND_ASSIGN_STATES).toContain('ASSIGN_REQUESTED');
    expect(A7_PRODUCT_COMMAND_ASSIGN_STATES).toContain('ASSIGN_PENDING');
    expect(A7_PRODUCT_COMMAND_ASSIGN_STATES).toContain('ASSIGN_ACTIVE');
    expect(A7_PRODUCT_COMMAND_ASSIGN_STATES).toContain('ASSIGN_SUSPENDED');
    expect(A7_PRODUCT_COMMAND_ASSIGN_STATES).toContain('ASSIGN_FAILED');
    expect(A7_PRODUCT_COMMAND_ASSIGN_STATES).toContain('ASSIGN_CLOSED');
    expect(A7_PRODUCT_COMMAND_FUNDING_STATES).toContain('FUNDING_REQUESTED');
    expect(A7_PRODUCT_COMMAND_FUNDING_STATES).toContain('FUNDING_PENDING_VERIFICATION');
    expect(A7_PRODUCT_COMMAND_FUNDING_STATES).toContain('FUNDING_SETTLED');
    expect(A7_PRODUCT_COMMAND_FUNDING_STATES).toContain('FUNDING_UNKNOWN');
    expect(A7_PRODUCT_COMMAND_FUNDING_STATES).toContain('FUNDING_SUSPENDED');
    expect(A7_PRODUCT_COMMAND_FUNDING_STATES).toContain('FUNDING_FAILED');
    expect(A7_PRODUCT_COMMAND_FUNDING_STATES).toContain('FUNDING_CLOSED');
    expect(A7_PRODUCT_COMMAND_ALL_STATES).toEqual([
      ...A7_PRODUCT_COMMAND_ASSIGN_STATES,
      ...A7_PRODUCT_COMMAND_FUNDING_STATES,
    ]);
  });

  it('freezes the A7 product command capability and action keys', () => {
    expect(A7_PRODUCT_COMMAND_CAPABILITY_ASSIGN).toBe('virtual-account.assign');
    expect(A7_PRODUCT_COMMAND_CAPABILITY_INBOUND_FUNDING).toBe('virtual-account.inbound-funding');
    expect(A7_PRODUCT_COMMAND_ACTION_ASSIGN).toBe('assign');
    expect(A7_PRODUCT_COMMAND_ACTION_LIFECYCLE).toBe('lifecycle');
  });

  it('freezes the A6 partner identity reused by A7 product command', () => {
    expect(A7_PRODUCT_COMMAND_PARTNER_KEY).toBe('NIBSS_NIP');
    expect(A7_PRODUCT_COMMAND_PARTNER_CAPABILITY).toBe('external.wallet.withdrawal.settlement');
    expect(A7_PRODUCT_COMMAND_PARTNER_OPERATION).toBe('OUTBOUND_BANK_SETTLEMENT');
  });

  it('freezes the A7 product command failure codes', () => {
    expect(A7_PRODUCT_COMMAND_FAILURE_A2_AUTHORIZATION_MISSING).toBe(
      'A7_PRODUCT_A2_AUTHORIZATION_MISSING',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A2_AUTHORIZATION_STALE).toBe(
      'A7_PRODUCT_A2_AUTHORIZATION_STALE',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A2_AUTHORIZATION_DENIED).toBe(
      'A7_PRODUCT_A2_AUTHORIZATION_DENIED',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A3_BINDING_MISSING).toBe('A7_PRODUCT_A3_BINDING_MISSING');
    expect(A7_PRODUCT_COMMAND_FAILURE_A3_BINDING_NOT_ACTIVE).toBe(
      'A7_PRODUCT_A3_BINDING_NOT_ACTIVE',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A3_STALE_BINDING).toBe('A7_PRODUCT_A3_STALE_BINDING');
    expect(A7_PRODUCT_COMMAND_FAILURE_A4_POLICY_DECISION_MISSING).toBe(
      'A7_PRODUCT_A4_POLICY_DECISION_MISSING',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A4_POLICY_DECISION_EXPIRED).toBe(
      'A7_PRODUCT_A4_POLICY_DECISION_EXPIRED',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A4_POLICY_DECISION_NOT_EXECUTABLE).toBe(
      'A7_PRODUCT_A4_POLICY_DECISION_NOT_EXECUTABLE',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A7T04_PRODUCT_CUSTOMER_BINDING_MISSING).toBe(
      'A7_PRODUCT_A7T04_PRODUCT_CUSTOMER_BINDING_MISSING',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A7T04_PRODUCT_CUSTOMER_BINDING_FAILED).toBe(
      'A7_PRODUCT_A7T04_PRODUCT_CUSTOMER_BINDING_FAILED',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A6_EXTERNAL_OPERATION_MISSING).toBe(
      'A7_PRODUCT_A6_EXTERNAL_OPERATION_MISSING',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A6_EXTERNAL_OPERATION_NOT_FOUND).toBe(
      'A7_PRODUCT_A6_EXTERNAL_OPERATION_NOT_FOUND',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A6_EXTERNAL_OPERATION_MAPPING_CONFLICT).toBe(
      'A7_PRODUCT_A6_EXTERNAL_OPERATION_MAPPING_CONFLICT',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_A6_EXTERNAL_OPERATION_CONTEXT_MISMATCH).toBe(
      'A7_PRODUCT_A6_EXTERNAL_OPERATION_CONTEXT_MISMATCH',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_REQUEST_HASH_CONFLICT).toBe(
      'A7_PRODUCT_REQUEST_HASH_CONFLICT',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_IDEMPOTENCY_IN_PROGRESS).toBe(
      'A7_PRODUCT_IDEMPOTENCY_IN_PROGRESS',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_PRODUCT_CATALOG_REJECTED).toBe('A7_PRODUCT_CATALOG_REJECTED');
    expect(A7_PRODUCT_COMMAND_FAILURE_CURRENCY_MISMATCH).toBe('A7_PRODUCT_CURRENCY_MISMATCH');
    expect(A7_PRODUCT_COMMAND_FAILURE_ACCOUNTING_UNIT_MISMATCH).toBe(
      'A7_PRODUCT_ACCOUNTING_UNIT_MISMATCH',
    );
    expect(A7_PRODUCT_COMMAND_FAILURE_AMOUNT_INVALID).toBe('A7_PRODUCT_AMOUNT_INVALID');
    expect(A7_PRODUCT_COMMAND_FAILURE_OPERATIONS_EVIDENCE_UNAVAILABLE).toBe(
      'A7_PRODUCT_OPERATIONS_EVIDENCE_UNAVAILABLE',
    );
  });

  it('freezes the A7 product command and product operation reference prefixes', () => {
    expect(A7_PRODUCT_COMMAND_REFERENCE_PREFIX).toBe('a7-product-command');
    expect(A7_PRODUCT_OPERATION_REFERENCE_PREFIX).toBe('a7-product-operation');
  });
});
