import {
  A7_PRODUCT_LIFECYCLE_CONTRACT_NAME,
  A7_PRODUCT_LIFECYCLE_CONTRACT_VERSION,
  A7_PRODUCT_LIFECYCLE_IDENTITY_NAMESPACE,
  A7_PRODUCT_LIFECYCLE_INTERNAL_IDEMPOTENCY_SCOPE,
  A7_PRODUCT_LIFECYCLE_PROVIDER_IDEMPOTENCY_SCOPE,
  A7_PRODUCT_LIFECYCLE_IDEMPOTENCY_RETENTION_SECONDS,
  A7_PRODUCT_LIFECYCLE_AUDIT_ENTITY_TYPE,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTOR,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_RESERVED,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_ADMITTED,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_PARTNER_PENDING,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_PENDING_VERIFICATION,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_UNKNOWN,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_MANUAL_REVIEW,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_FAILED,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_RETRY_SCHEDULED,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_RETRY_EXHAUSTED,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_CANCELLED,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_RECOVERY_ISSUED,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_RECOVERY_RESOLVED,
  A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_REPLAYED,
  A7_PRODUCT_LIFECYCLE_OUTBOX_EVENT_TYPE,
  A7_PRODUCT_LIFECYCLE_OUTBOX_EVENT_CLASSIFICATION,
  A7_PRODUCT_LIFECYCLE_OUTBOX_EVENT_RETENTION_CLASS,
  A7_PRODUCT_LIFECYCLE_STATES,
  A7_PRODUCT_LIFECYCLE_STATE_PENDING,
  A7_PRODUCT_LIFECYCLE_STATE_ADMITTED,
  A7_PRODUCT_LIFECYCLE_STATE_PENDING_PARTNER,
  A7_PRODUCT_LIFECYCLE_STATE_PENDING_VERIFICATION,
  A7_PRODUCT_LIFECYCLE_STATE_UNKNOWN,
  A7_PRODUCT_LIFECYCLE_STATE_MANUAL_REVIEW,
  A7_PRODUCT_LIFECYCLE_STATE_RETRY_SCHEDULED,
  A7_PRODUCT_LIFECYCLE_STATE_RECOVERY_ISSUED,
  A7_PRODUCT_LIFECYCLE_STATE_FAILED,
  A7_PRODUCT_LIFECYCLE_STATE_CANCELLED,
  A7_PRODUCT_LIFECYCLE_TERMINAL_STATES,
  A7_PRODUCT_LIFECYCLE_TRANSITIONS,
  A7_PRODUCT_LIFECYCLE_MAX_RETRY_ATTEMPTS,
  A7_PRODUCT_LIFECYCLE_RETRY_CLASSES,
  A7_PRODUCT_LIFECYCLE_RETRY_CLASS_SAFE_TRANSPORT,
  A7_PRODUCT_LIFECYCLE_RETRY_CLASS_PARTNER_REJECTION,
  A7_PRODUCT_LIFECYCLE_RETRY_CLASS_RATE_LIMIT,
  A7_PRODUCT_LIFECYCLE_RETRY_CLASS_TIMEOUT,
  A7_PRODUCT_LIFECYCLE_RETRY_CLASS_STATUS_QUERY,
  A7_PRODUCT_LIFECYCLE_RETRY_CLASS_AMBIGUOUS_COMMIT,
  A7_PRODUCT_LIFECYCLE_RETRY_CLASS_NONE,
  A7_PRODUCT_LIFECYCLE_OUTCOMES,
  A7_PRODUCT_LIFECYCLE_OUTCOME_PENDING,
  A7_PRODUCT_LIFECYCLE_OUTCOME_VERIFIED,
  A7_PRODUCT_LIFECYCLE_OUTCOME_REJECTED,
  A7_PRODUCT_LIFECYCLE_OUTCOME_UNKNOWN,
  A7_PRODUCT_LIFECYCLE_OUTCOME_MANUAL_REVIEW,
  A7_PRODUCT_LIFECYCLE_OUTCOME_FAILED,
  A7_PRODUCT_LIFECYCLE_TO_A6_LIFECYCLE,
  A7_PRODUCT_LIFECYCLE_ASSIGN_STATES,
  A7_PRODUCT_LIFECYCLE_FUNDING_STATES,
  A7_PRODUCT_LIFECYCLE_ALL_STATES,
  A7_PRODUCT_LIFECYCLE_CAPABILITY_ASSIGN,
  A7_PRODUCT_LIFECYCLE_CAPABILITY_INBOUND_FUNDING,
  A7_PRODUCT_LIFECYCLE_ACTION_ASSIGN,
  A7_PRODUCT_LIFECYCLE_ACTION_LIFECYCLE,
  A7_PRODUCT_LIFECYCLE_PARTNER_KEY,
  A7_PRODUCT_LIFECYCLE_PARTNER_CAPABILITY,
  A7_PRODUCT_LIFECYCLE_PARTNER_OPERATION,
  A7_PRODUCT_LIFECYCLE_HANDOFF_SCOPE,
  A7_PRODUCT_LIFECYCLE_HANDOFF_VALIDITY_SECONDS,
  A7_PRODUCT_LIFECYCLE_FAILURE_A6_LIFECYCLE_MISSING,
  A7_PRODUCT_LIFECYCLE_FAILURE_A6_LIFECYCLE_INVALID_TRANSITION,
  A7_PRODUCT_LIFECYCLE_FAILURE_A6_LIFECYCLE_TERMINAL,
  A7_PRODUCT_LIFECYCLE_FAILURE_A6_LIFECYCLE_STALE,
  A7_PRODUCT_LIFECYCLE_FAILURE_A6_STATUS_VERIFICATION_UNAVAILABLE,
  A7_PRODUCT_LIFECYCLE_FAILURE_A6_CIRCUIT_OPEN,
  A7_PRODUCT_LIFECYCLE_FAILURE_A6_RETRY_EXHAUSTED,
  A7_PRODUCT_LIFECYCLE_FAILURE_A2_AUTHORIZATION_MISSING,
  A7_PRODUCT_LIFECYCLE_FAILURE_A2_AUTHORIZATION_STALE,
  A7_PRODUCT_LIFECYCLE_FAILURE_A2_AUTHORIZATION_DENIED,
  A7_PRODUCT_LIFECYCLE_FAILURE_A4_POLICY_DECISION_MISSING,
  A7_PRODUCT_LIFECYCLE_FAILURE_A4_POLICY_DECISION_EXPIRED,
  A7_PRODUCT_LIFECYCLE_FAILURE_A4_POLICY_DECISION_NOT_EXECUTABLE,
  A7_PRODUCT_LIFECYCLE_FAILURE_A7T05_PRODUCT_COMMAND_MISSING,
  A7_PRODUCT_LIFECYCLE_FAILURE_A7T05_PRODUCT_COMMAND_NOT_FOUND,
  A7_PRODUCT_LIFECYCLE_FAILURE_A7T05_PRODUCT_COMMAND_CONTEXT_MISMATCH,
  A7_PRODUCT_LIFECYCLE_FAILURE_RECOVERY_REFERENCE_MISSING,
  A7_PRODUCT_LIFECYCLE_FAILURE_RECOVERY_REFERENCE_MISMATCH,
  A7_PRODUCT_LIFECYCLE_FAILURE_RETRY_EXHAUSTED,
  A7_PRODUCT_LIFECYCLE_FAILURE_RETRY_CLASS_NOT_RETRYABLE,
  A7_PRODUCT_LIFECYCLE_FAILURE_PRODUCT_CATALOG_REJECTED,
  A7_PRODUCT_LIFECYCLE_FAILURE_PRODUCT_STATE_INVALID,
  A7_PRODUCT_LIFECYCLE_FAILURE_REQUEST_HASH_CONFLICT,
  A7_PRODUCT_LIFECYCLE_FAILURE_IDEMPOTENCY_IN_PROGRESS,
  A7_PRODUCT_LIFECYCLE_FAILURE_OPERATIONS_EVIDENCE_UNAVAILABLE,
  A7_PRODUCT_LIFECYCLE_FAILURE_OUTBOX_PUBLICATION_FAILED,
  A7_PRODUCT_LIFECYCLE_FAILURE_OUTCOME_UNKNOWN,
  A7_PRODUCT_LIFECYCLE_FAILURE_OUTCOME_MANUAL_REVIEW_REQUIRED,
  A7_PRODUCT_LIFECYCLE_FAILURE_OUTCOME_FAILED,
  A7_PRODUCT_LIFECYCLE_METRIC_ADMITTED,
  A7_PRODUCT_LIFECYCLE_METRIC_TRANSITIONED,
  A7_PRODUCT_LIFECYCLE_METRIC_RETRY_SCHEDULED,
  A7_PRODUCT_LIFECYCLE_METRIC_RETRY_EXHAUSTED,
  A7_PRODUCT_LIFECYCLE_METRIC_RECOVERY_ISSUED,
  A7_PRODUCT_LIFECYCLE_METRIC_RECOVERY_RESOLVED,
  A7_PRODUCT_LIFECYCLE_METRIC_MANUAL_REVIEW,
  A7_PRODUCT_LIFECYCLE_METRIC_FAILED,
  A7_PRODUCT_LIFECYCLE_METRIC_CANCELLED,
  A7_PRODUCT_LIFECYCLE_METRIC_REPLAYED,
  A7_PRODUCT_LIFECYCLE_REFERENCE_PREFIX,
  A7_PRODUCT_LIFECYCLE_RECOVERY_REFERENCE_PREFIX,
} from '../src/policy/a7-product-lifecycle.constants';

describe('A7 product lifecycle constants (A7T07)', () => {
  it('freezes the A7 product lifecycle contract name and version', () => {
    expect(A7_PRODUCT_LIFECYCLE_CONTRACT_NAME).toBe('A7-PRODUCT-LIFECYCLE');
    expect(A7_PRODUCT_LIFECYCLE_CONTRACT_VERSION).toBe(1);
  });

  it('freezes the A7 product lifecycle identity namespace', () => {
    expect(A7_PRODUCT_LIFECYCLE_IDENTITY_NAMESPACE).toBe('A7-PRODUCT-LIFECYCLE');
  });

  it('separates the A7 internal idempotency scope from the A6T05 provider idempotency scope', () => {
    expect(A7_PRODUCT_LIFECYCLE_INTERNAL_IDEMPOTENCY_SCOPE).toBe(
      'a7.product-lifecycle.idempotency.v1',
    );
    expect(A7_PRODUCT_LIFECYCLE_PROVIDER_IDEMPOTENCY_SCOPE).toBe('nibss.nip.external-operation.v1');
    expect(A7_PRODUCT_LIFECYCLE_INTERNAL_IDEMPOTENCY_SCOPE).not.toBe(
      A7_PRODUCT_LIFECYCLE_PROVIDER_IDEMPOTENCY_SCOPE,
    );
  });

  it('aligns the A7 product lifecycle idempotency retention with Operations', () => {
    expect(A7_PRODUCT_LIFECYCLE_IDEMPOTENCY_RETENTION_SECONDS).toBe(86_400);
  });

  it('freezes the A7 product lifecycle audit entity type and actor', () => {
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ENTITY_TYPE).toBe('A7_PRODUCT_LIFECYCLE');
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTOR).toBe('a7-product-lifecycle');
  });

  it('freezes the A7 product lifecycle audit action codes', () => {
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_RESERVED).toBe('A7_PRODUCT_LIFECYCLE_RESERVED');
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_ADMITTED).toBe('A7_PRODUCT_LIFECYCLE_ADMITTED');
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_PARTNER_PENDING).toBe(
      'A7_PRODUCT_LIFECYCLE_PARTNER_PENDING',
    );
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_PENDING_VERIFICATION).toBe(
      'A7_PRODUCT_LIFECYCLE_PENDING_VERIFICATION',
    );
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_UNKNOWN).toBe('A7_PRODUCT_LIFECYCLE_UNKNOWN');
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_MANUAL_REVIEW).toBe(
      'A7_PRODUCT_LIFECYCLE_MANUAL_REVIEW',
    );
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_FAILED).toBe('A7_PRODUCT_LIFECYCLE_FAILED');
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_RETRY_SCHEDULED).toBe(
      'A7_PRODUCT_LIFECYCLE_RETRY_SCHEDULED',
    );
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_RETRY_EXHAUSTED).toBe(
      'A7_PRODUCT_LIFECYCLE_RETRY_EXHAUSTED',
    );
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_CANCELLED).toBe('A7_PRODUCT_LIFECYCLE_CANCELLED');
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_RECOVERY_ISSUED).toBe(
      'A7_PRODUCT_LIFECYCLE_RECOVERY_ISSUED',
    );
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_RECOVERY_RESOLVED).toBe(
      'A7_PRODUCT_LIFECYCLE_RECOVERY_RESOLVED',
    );
    expect(A7_PRODUCT_LIFECYCLE_AUDIT_ACTION_REPLAYED).toBe('A7_PRODUCT_LIFECYCLE_REPLAYED');
  });

  it('freezes the A7 product lifecycle outbox event type, classification, and retention class', () => {
    expect(A7_PRODUCT_LIFECYCLE_OUTBOX_EVENT_TYPE).toBe('A7ProductLifecycleTransitioned');
    expect(A7_PRODUCT_LIFECYCLE_OUTBOX_EVENT_CLASSIFICATION).toBe('INTERNAL_OPERATIONS');
    expect(A7_PRODUCT_LIFECYCLE_OUTBOX_EVENT_RETENTION_CLASS).toBe('OPERATIONS_DEFAULT');
  });

  it('freezes the A7 product lifecycle state vocabulary', () => {
    expect(A7_PRODUCT_LIFECYCLE_STATES).toEqual([
      A7_PRODUCT_LIFECYCLE_STATE_PENDING,
      A7_PRODUCT_LIFECYCLE_STATE_ADMITTED,
      A7_PRODUCT_LIFECYCLE_STATE_PENDING_PARTNER,
      A7_PRODUCT_LIFECYCLE_STATE_PENDING_VERIFICATION,
      A7_PRODUCT_LIFECYCLE_STATE_UNKNOWN,
      A7_PRODUCT_LIFECYCLE_STATE_MANUAL_REVIEW,
      A7_PRODUCT_LIFECYCLE_STATE_RETRY_SCHEDULED,
      A7_PRODUCT_LIFECYCLE_STATE_RECOVERY_ISSUED,
      A7_PRODUCT_LIFECYCLE_STATE_FAILED,
      A7_PRODUCT_LIFECYCLE_STATE_CANCELLED,
    ]);
  });

  it('freezes the A7 product lifecycle terminal state vocabulary', () => {
    expect(A7_PRODUCT_LIFECYCLE_TERMINAL_STATES).toEqual([
      A7_PRODUCT_LIFECYCLE_STATE_FAILED,
      A7_PRODUCT_LIFECYCLE_STATE_CANCELLED,
    ]);
  });

  it('freezes the A7 product lifecycle transition table', () => {
    expect(A7_PRODUCT_LIFECYCLE_TRANSITIONS[A7_PRODUCT_LIFECYCLE_STATE_PENDING]).toEqual([
      A7_PRODUCT_LIFECYCLE_STATE_ADMITTED,
      A7_PRODUCT_LIFECYCLE_STATE_FAILED,
      A7_PRODUCT_LIFECYCLE_STATE_CANCELLED,
    ]);
    expect(A7_PRODUCT_LIFECYCLE_TRANSITIONS[A7_PRODUCT_LIFECYCLE_STATE_ADMITTED]).toContain(
      A7_PRODUCT_LIFECYCLE_STATE_PENDING_PARTNER,
    );
    expect(A7_PRODUCT_LIFECYCLE_TRANSITIONS[A7_PRODUCT_LIFECYCLE_STATE_ADMITTED]).toContain(
      A7_PRODUCT_LIFECYCLE_STATE_UNKNOWN,
    );
    expect(A7_PRODUCT_LIFECYCLE_TRANSITIONS[A7_PRODUCT_LIFECYCLE_STATE_PENDING_PARTNER]).toContain(
      A7_PRODUCT_LIFECYCLE_STATE_PENDING_VERIFICATION,
    );
    expect(
      A7_PRODUCT_LIFECYCLE_TRANSITIONS[A7_PRODUCT_LIFECYCLE_STATE_PENDING_VERIFICATION],
    ).toContain(A7_PRODUCT_LIFECYCLE_STATE_RECOVERY_ISSUED);
    expect(A7_PRODUCT_LIFECYCLE_TRANSITIONS[A7_PRODUCT_LIFECYCLE_STATE_UNKNOWN]).toContain(
      A7_PRODUCT_LIFECYCLE_STATE_MANUAL_REVIEW,
    );
    expect(A7_PRODUCT_LIFECYCLE_TRANSITIONS[A7_PRODUCT_LIFECYCLE_STATE_MANUAL_REVIEW]).toEqual([
      A7_PRODUCT_LIFECYCLE_STATE_PENDING_VERIFICATION,
      A7_PRODUCT_LIFECYCLE_STATE_FAILED,
    ]);
    expect(A7_PRODUCT_LIFECYCLE_TRANSITIONS[A7_PRODUCT_LIFECYCLE_STATE_RECOVERY_ISSUED]).toEqual([
      A7_PRODUCT_LIFECYCLE_STATE_PENDING_VERIFICATION,
      A7_PRODUCT_LIFECYCLE_STATE_MANUAL_REVIEW,
      A7_PRODUCT_LIFECYCLE_STATE_FAILED,
    ]);
    expect(A7_PRODUCT_LIFECYCLE_TRANSITIONS[A7_PRODUCT_LIFECYCLE_STATE_FAILED]).toEqual([]);
    expect(A7_PRODUCT_LIFECYCLE_TRANSITIONS[A7_PRODUCT_LIFECYCLE_STATE_CANCELLED]).toEqual([]);
  });

  it('freezes the A7 product lifecycle maximum retry attempts', () => {
    expect(A7_PRODUCT_LIFECYCLE_MAX_RETRY_ATTEMPTS).toBe(3);
  });

  it('freezes the A7 product lifecycle retry class vocabulary', () => {
    expect(A7_PRODUCT_LIFECYCLE_RETRY_CLASSES).toEqual([
      A7_PRODUCT_LIFECYCLE_RETRY_CLASS_SAFE_TRANSPORT,
      A7_PRODUCT_LIFECYCLE_RETRY_CLASS_PARTNER_REJECTION,
      A7_PRODUCT_LIFECYCLE_RETRY_CLASS_RATE_LIMIT,
      A7_PRODUCT_LIFECYCLE_RETRY_CLASS_TIMEOUT,
      A7_PRODUCT_LIFECYCLE_RETRY_CLASS_STATUS_QUERY,
      A7_PRODUCT_LIFECYCLE_RETRY_CLASS_AMBIGUOUS_COMMIT,
      A7_PRODUCT_LIFECYCLE_RETRY_CLASS_NONE,
    ]);
  });

  it('freezes the A7 product lifecycle outcome vocabulary', () => {
    expect(A7_PRODUCT_LIFECYCLE_OUTCOMES).toEqual([
      A7_PRODUCT_LIFECYCLE_OUTCOME_PENDING,
      A7_PRODUCT_LIFECYCLE_OUTCOME_VERIFIED,
      A7_PRODUCT_LIFECYCLE_OUTCOME_REJECTED,
      A7_PRODUCT_LIFECYCLE_OUTCOME_UNKNOWN,
      A7_PRODUCT_LIFECYCLE_OUTCOME_MANUAL_REVIEW,
      A7_PRODUCT_LIFECYCLE_OUTCOME_FAILED,
    ]);
  });

  it('freezes the A7 product lifecycle to A6 lifecycle state mapping', () => {
    expect(A7_PRODUCT_LIFECYCLE_TO_A6_LIFECYCLE[A7_PRODUCT_LIFECYCLE_STATE_PENDING]).toBe(
      'CREATED',
    );
    expect(A7_PRODUCT_LIFECYCLE_TO_A6_LIFECYCLE[A7_PRODUCT_LIFECYCLE_STATE_ADMITTED]).toBe(
      'SUBMITTING',
    );
    expect(A7_PRODUCT_LIFECYCLE_TO_A6_LIFECYCLE[A7_PRODUCT_LIFECYCLE_STATE_PENDING_PARTNER]).toBe(
      'PENDING_PROVIDER',
    );
    expect(
      A7_PRODUCT_LIFECYCLE_TO_A6_LIFECYCLE[A7_PRODUCT_LIFECYCLE_STATE_PENDING_VERIFICATION],
    ).toBe('PENDING_VERIFICATION');
    expect(A7_PRODUCT_LIFECYCLE_TO_A6_LIFECYCLE[A7_PRODUCT_LIFECYCLE_STATE_UNKNOWN]).toBe(
      'UNKNOWN',
    );
    expect(A7_PRODUCT_LIFECYCLE_TO_A6_LIFECYCLE[A7_PRODUCT_LIFECYCLE_STATE_MANUAL_REVIEW]).toBe(
      'MANUAL_REVIEW',
    );
    expect(A7_PRODUCT_LIFECYCLE_TO_A6_LIFECYCLE[A7_PRODUCT_LIFECYCLE_STATE_RECOVERY_ISSUED]).toBe(
      'PENDING_VERIFICATION',
    );
    expect(A7_PRODUCT_LIFECYCLE_TO_A6_LIFECYCLE[A7_PRODUCT_LIFECYCLE_STATE_FAILED]).toBe('FAILED');
    expect(A7_PRODUCT_LIFECYCLE_TO_A6_LIFECYCLE[A7_PRODUCT_LIFECYCLE_STATE_CANCELLED]).toBe(
      'CANCELLED',
    );
  });

  it('reuses the A7 product-state vocabulary from the A7T02 product catalog', () => {
    expect(A7_PRODUCT_LIFECYCLE_ASSIGN_STATES).toContain('ASSIGN_REQUESTED');
    expect(A7_PRODUCT_LIFECYCLE_ASSIGN_STATES).toContain('ASSIGN_PENDING');
    expect(A7_PRODUCT_LIFECYCLE_ASSIGN_STATES).toContain('ASSIGN_ACTIVE');
    expect(A7_PRODUCT_LIFECYCLE_ASSIGN_STATES).toContain('ASSIGN_SUSPENDED');
    expect(A7_PRODUCT_LIFECYCLE_ASSIGN_STATES).toContain('ASSIGN_FAILED');
    expect(A7_PRODUCT_LIFECYCLE_ASSIGN_STATES).toContain('ASSIGN_CLOSED');
    expect(A7_PRODUCT_LIFECYCLE_FUNDING_STATES).toContain('FUNDING_REQUESTED');
    expect(A7_PRODUCT_LIFECYCLE_FUNDING_STATES).toContain('FUNDING_PENDING_VERIFICATION');
    expect(A7_PRODUCT_LIFECYCLE_FUNDING_STATES).toContain('FUNDING_SETTLED');
    expect(A7_PRODUCT_LIFECYCLE_FUNDING_STATES).toContain('FUNDING_UNKNOWN');
    expect(A7_PRODUCT_LIFECYCLE_FUNDING_STATES).toContain('FUNDING_SUSPENDED');
    expect(A7_PRODUCT_LIFECYCLE_FUNDING_STATES).toContain('FUNDING_FAILED');
    expect(A7_PRODUCT_LIFECYCLE_FUNDING_STATES).toContain('FUNDING_CLOSED');
    expect(A7_PRODUCT_LIFECYCLE_ALL_STATES).toEqual([
      ...A7_PRODUCT_LIFECYCLE_ASSIGN_STATES,
      ...A7_PRODUCT_LIFECYCLE_FUNDING_STATES,
    ]);
  });

  it('freezes the A7 product lifecycle capability and action keys', () => {
    expect(A7_PRODUCT_LIFECYCLE_CAPABILITY_ASSIGN).toBe('virtual-account.assign');
    expect(A7_PRODUCT_LIFECYCLE_CAPABILITY_INBOUND_FUNDING).toBe('virtual-account.inbound-funding');
    expect(A7_PRODUCT_LIFECYCLE_ACTION_ASSIGN).toBe('assign');
    expect(A7_PRODUCT_LIFECYCLE_ACTION_LIFECYCLE).toBe('lifecycle');
  });

  it('freezes the A6 partner identity reused by A7 product lifecycle', () => {
    expect(A7_PRODUCT_LIFECYCLE_PARTNER_KEY).toBe('NIBSS_NIP');
    expect(A7_PRODUCT_LIFECYCLE_PARTNER_CAPABILITY).toBe('external.wallet.withdrawal.settlement');
    expect(A7_PRODUCT_LIFECYCLE_PARTNER_OPERATION).toBe('OUTBOUND_BANK_SETTLEMENT');
  });

  it('freezes the A7 product lifecycle handoff scope and validity', () => {
    expect(A7_PRODUCT_LIFECYCLE_HANDOFF_SCOPE).toBe('a7-product-lifecycle-handoff.v1');
    expect(A7_PRODUCT_LIFECYCLE_HANDOFF_VALIDITY_SECONDS).toBe(15 * 60);
  });

  it('freezes the A7 product lifecycle failure codes', () => {
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A6_LIFECYCLE_MISSING).toBe(
      'A7_PRODUCT_LIFECYCLE_A6_LIFECYCLE_MISSING',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A6_LIFECYCLE_INVALID_TRANSITION).toBe(
      'A7_PRODUCT_LIFECYCLE_A6_LIFECYCLE_INVALID_TRANSITION',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A6_LIFECYCLE_TERMINAL).toBe(
      'A7_PRODUCT_LIFECYCLE_A6_LIFECYCLE_TERMINAL',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A6_LIFECYCLE_STALE).toBe(
      'A7_PRODUCT_LIFECYCLE_A6_LIFECYCLE_STALE',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A6_STATUS_VERIFICATION_UNAVAILABLE).toBe(
      'A7_PRODUCT_LIFECYCLE_A6_STATUS_VERIFICATION_UNAVAILABLE',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A6_CIRCUIT_OPEN).toBe(
      'A7_PRODUCT_LIFECYCLE_A6_CIRCUIT_OPEN',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A6_RETRY_EXHAUSTED).toBe(
      'A7_PRODUCT_LIFECYCLE_A6_RETRY_EXHAUSTED',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A2_AUTHORIZATION_MISSING).toBe(
      'A7_PRODUCT_LIFECYCLE_A2_AUTHORIZATION_MISSING',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A2_AUTHORIZATION_STALE).toBe(
      'A7_PRODUCT_LIFECYCLE_A2_AUTHORIZATION_STALE',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A2_AUTHORIZATION_DENIED).toBe(
      'A7_PRODUCT_LIFECYCLE_A2_AUTHORIZATION_DENIED',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A4_POLICY_DECISION_MISSING).toBe(
      'A7_PRODUCT_LIFECYCLE_A4_POLICY_DECISION_MISSING',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A4_POLICY_DECISION_EXPIRED).toBe(
      'A7_PRODUCT_LIFECYCLE_A4_POLICY_DECISION_EXPIRED',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A4_POLICY_DECISION_NOT_EXECUTABLE).toBe(
      'A7_PRODUCT_LIFECYCLE_A4_POLICY_DECISION_NOT_EXECUTABLE',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A7T05_PRODUCT_COMMAND_MISSING).toBe(
      'A7_PRODUCT_LIFECYCLE_A7T05_PRODUCT_COMMAND_MISSING',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A7T05_PRODUCT_COMMAND_NOT_FOUND).toBe(
      'A7_PRODUCT_LIFECYCLE_A7T05_PRODUCT_COMMAND_NOT_FOUND',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_A7T05_PRODUCT_COMMAND_CONTEXT_MISMATCH).toBe(
      'A7_PRODUCT_LIFECYCLE_A7T05_PRODUCT_COMMAND_CONTEXT_MISMATCH',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_RECOVERY_REFERENCE_MISSING).toBe(
      'A7_PRODUCT_LIFECYCLE_RECOVERY_REFERENCE_MISSING',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_RECOVERY_REFERENCE_MISMATCH).toBe(
      'A7_PRODUCT_LIFECYCLE_RECOVERY_REFERENCE_MISMATCH',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_RETRY_EXHAUSTED).toBe(
      'A7_PRODUCT_LIFECYCLE_RETRY_EXHAUSTED',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_RETRY_CLASS_NOT_RETRYABLE).toBe(
      'A7_PRODUCT_LIFECYCLE_RETRY_CLASS_NOT_RETRYABLE',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_PRODUCT_CATALOG_REJECTED).toBe(
      'A7_PRODUCT_LIFECYCLE_PRODUCT_CATALOG_REJECTED',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_PRODUCT_STATE_INVALID).toBe(
      'A7_PRODUCT_LIFECYCLE_PRODUCT_STATE_INVALID',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_REQUEST_HASH_CONFLICT).toBe(
      'A7_PRODUCT_LIFECYCLE_REQUEST_HASH_CONFLICT',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_IDEMPOTENCY_IN_PROGRESS).toBe(
      'A7_PRODUCT_LIFECYCLE_IDEMPOTENCY_IN_PROGRESS',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_OPERATIONS_EVIDENCE_UNAVAILABLE).toBe(
      'A7_PRODUCT_LIFECYCLE_OPERATIONS_EVIDENCE_UNAVAILABLE',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_OUTBOX_PUBLICATION_FAILED).toBe(
      'A7_PRODUCT_LIFECYCLE_OUTBOX_PUBLICATION_FAILED',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_OUTCOME_UNKNOWN).toBe(
      'A7_PRODUCT_LIFECYCLE_OUTCOME_UNKNOWN',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_OUTCOME_MANUAL_REVIEW_REQUIRED).toBe(
      'A7_PRODUCT_LIFECYCLE_OUTCOME_MANUAL_REVIEW_REQUIRED',
    );
    expect(A7_PRODUCT_LIFECYCLE_FAILURE_OUTCOME_FAILED).toBe('A7_PRODUCT_LIFECYCLE_OUTCOME_FAILED');
  });

  it('freezes the A7 product lifecycle metric names', () => {
    expect(A7_PRODUCT_LIFECYCLE_METRIC_ADMITTED).toBe('a7.product-lifecycle.admitted');
    expect(A7_PRODUCT_LIFECYCLE_METRIC_TRANSITIONED).toBe('a7.product-lifecycle.transitioned');
    expect(A7_PRODUCT_LIFECYCLE_METRIC_RETRY_SCHEDULED).toBe(
      'a7.product-lifecycle.retry-scheduled',
    );
    expect(A7_PRODUCT_LIFECYCLE_METRIC_RETRY_EXHAUSTED).toBe(
      'a7.product-lifecycle.retry-exhausted',
    );
    expect(A7_PRODUCT_LIFECYCLE_METRIC_RECOVERY_ISSUED).toBe(
      'a7.product-lifecycle.recovery-issued',
    );
    expect(A7_PRODUCT_LIFECYCLE_METRIC_RECOVERY_RESOLVED).toBe(
      'a7.product-lifecycle.recovery-resolved',
    );
    expect(A7_PRODUCT_LIFECYCLE_METRIC_MANUAL_REVIEW).toBe('a7.product-lifecycle.manual-review');
    expect(A7_PRODUCT_LIFECYCLE_METRIC_FAILED).toBe('a7.product-lifecycle.failed');
    expect(A7_PRODUCT_LIFECYCLE_METRIC_CANCELLED).toBe('a7.product-lifecycle.cancelled');
    expect(A7_PRODUCT_LIFECYCLE_METRIC_REPLAYED).toBe('a7.product-lifecycle.replayed');
  });

  it('freezes the A7 product lifecycle reference prefixes', () => {
    expect(A7_PRODUCT_LIFECYCLE_REFERENCE_PREFIX).toBe('a7-product-lifecycle');
    expect(A7_PRODUCT_LIFECYCLE_RECOVERY_REFERENCE_PREFIX).toBe('a7-product-lifecycle-recovery');
  });
});
