import {
  A7_PRODUCT_COMMAND_OPERATION_STATE_RESERVED,
  A7_PRODUCT_COMMAND_OPERATION_STATE_ADMITTED,
  A7_PRODUCT_COMMAND_OPERATION_STATE_COMPLETED,
  A7_PRODUCT_COMMAND_OPERATION_STATE_FAILED,
  A7_PRODUCT_COMMAND_OPERATION_STATE_REPLAYED,
  A7_PRODUCT_COMMAND_OPERATION_STATE_CONFLICTED,
} from '../src/policy/a7-product-command.constants';

describe('A7 product command types (A7T05)', () => {
  it('exposes the A7 product command operation state constants', () => {
    expect(A7_PRODUCT_COMMAND_OPERATION_STATE_RESERVED).toBe('COMMAND_RESERVED');
    expect(A7_PRODUCT_COMMAND_OPERATION_STATE_ADMITTED).toBe('COMMAND_ADMITTED');
    expect(A7_PRODUCT_COMMAND_OPERATION_STATE_COMPLETED).toBe('COMMAND_COMPLETED');
    expect(A7_PRODUCT_COMMAND_OPERATION_STATE_FAILED).toBe('COMMAND_FAILED');
    expect(A7_PRODUCT_COMMAND_OPERATION_STATE_REPLAYED).toBe('COMMAND_REPLAYED');
    expect(A7_PRODUCT_COMMAND_OPERATION_STATE_CONFLICTED).toBe('COMMAND_CONFLICTED');
  });
});
