import {
  A7_PRODUCT_CUSTOMER_BINDING_AUDIT_ACTION_HANDOFF_ISSUED,
  A7_PRODUCT_CUSTOMER_BINDING_AUDIT_ACTION_MAP_REJECTED,
  A7_PRODUCT_CUSTOMER_BINDING_AUDIT_ACTION_MAP_RESOLVED,
  A7_PRODUCT_CUSTOMER_BINDING_AUDIT_ACTION_MAP_VERIFIED,
  A7_PRODUCT_CUSTOMER_BINDING_AUDIT_ACTOR,
  A7_PRODUCT_CUSTOMER_BINDING_CONTRACT_NAME,
  A7_PRODUCT_CUSTOMER_BINDING_CONTRACT_VERSION,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A2_AUTHORIZATION_DENIED,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A2_AUTHORIZATION_MISSING,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A2_AUTHORIZATION_STALE,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A3_BINDING_MISSING,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A3_BINDING_NOT_ACTIVE,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A3_STALE_BINDING,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A4_POLICY_DECISION_EXPIRED,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A4_POLICY_DECISION_MISSING,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A4_POLICY_DECISION_NOT_EXECUTABLE,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A4_POLICY_LIMIT_INSUFFICIENT,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6_PARTNER_CONNECTION_UNAVAILABLE,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6_PARTNER_REFERENCE_MISSING,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6_PARTNER_REFERENCE_REPLAYED,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6_PARTNER_REFERENCE_STALE,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_CONSENT_INVALID,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_CURRENCY_UNSUPPORTED,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_NOT_ACTIVE,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_NOT_FOUND,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_NOT_VERIFIED,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_OWNERSHIP_MISMATCH,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_TYPE_UNSUPPORTED,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_VERSION_STALE,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_BANK_NOT_FOUND,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_CURRENCY_MISMATCH,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_OPERATIONS_EVIDENCE_UNAVAILABLE,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_PRODUCT_PURPOSE_MISMATCH,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_VIRTUAL_ACCOUNT_INACTIVE,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_VIRTUAL_ACCOUNT_MISSING,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_VIRTUAL_ACCOUNT_OWNER_MISMATCH,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_VIRTUAL_ACCOUNT_PROVIDER_MISMATCH,
  A7_PRODUCT_CUSTOMER_BINDING_FAILURE_VIRTUAL_ACCOUNT_NUMBER_MISMATCH,
  A7_PRODUCT_CUSTOMER_BINDING_HANDOFF_SCOPE,
  A7_PRODUCT_CUSTOMER_BINDING_HANDOFF_VALIDITY_SECONDS,
  A7_PRODUCT_CUSTOMER_BINDING_MAPPING_NAME,
  A7_PRODUCT_CUSTOMER_BINDING_MAPPING_VERSION,
  A7_PRODUCT_CUSTOMER_BINDING_PARTNER_CAPABILITY_EXTERNAL_WALLET_WITHDRAWAL_SETTLEMENT,
  A7_PRODUCT_CUSTOMER_BINDING_PARTNER_ENVIRONMENT_PRODUCTION,
  A7_PRODUCT_CUSTOMER_BINDING_PARTNER_ENVIRONMENT_SANDBOX,
  A7_PRODUCT_CUSTOMER_BINDING_PARTNER_KEY_NIBSS_NIP,
  A7_PRODUCT_CUSTOMER_BINDING_PARTNER_OPERATION_TYPE_OUTBOUND_BANK_SETTLEMENT,
  A7_PRODUCT_CUSTOMER_BINDING_ALL_STATES,
  A7_PRODUCT_CUSTOMER_BINDING_ASSIGN_STATES,
  A7_PRODUCT_CUSTOMER_BINDING_FUNDING_STATES,
} from '../src/policy/a7-product-customer-binding.constants';

describe('A7T04 A4 product customer-binding frozen constants', () => {
  it('binds the A7 product-customer-binding contract name and version', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_CONTRACT_NAME).toBe('A7-PRODUCT-CUSTOMER-BINDING');
    expect(A7_PRODUCT_CUSTOMER_BINDING_CONTRACT_VERSION).toBe(1);
  });

  it('binds the A7 product-customer-binding mapping name and version', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_MAPPING_NAME).toBe('A7-PRODUCT-CUSTOMER-BINDING');
    expect(A7_PRODUCT_CUSTOMER_BINDING_MAPPING_VERSION).toBe(1);
  });

  it('binds the A7 product-customer-binding handoff scope and validity interval', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_HANDOFF_SCOPE).toBe(
      'a7-product-customer-binding-handoff.v1',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_HANDOFF_VALIDITY_SECONDS).toBe(15 * 60);
  });

  it('binds the A7 product-customer-binding audit actor and audit action codes', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_AUDIT_ACTOR).toBe('a7-product-customer-binding');
    expect(A7_PRODUCT_CUSTOMER_BINDING_AUDIT_ACTION_MAP_VERIFIED).toBe(
      'A7_PRODUCT_CUSTOMER_BINDING_VERIFIED',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_AUDIT_ACTION_MAP_RESOLVED).toBe(
      'A7_PRODUCT_CUSTOMER_BINDING_RESOLVED',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_AUDIT_ACTION_HANDOFF_ISSUED).toBe(
      'A7_PRODUCT_CUSTOMER_BINDING_HANDOFF_ISSUED',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_AUDIT_ACTION_MAP_REJECTED).toBe(
      'A7_PRODUCT_CUSTOMER_BINDING_REJECTED',
    );
  });

  it('binds the A6 partner identity and reference types to the A6 partner boundary', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_PARTNER_KEY_NIBSS_NIP).toBe('NIBSS_NIP');
    expect(
      A7_PRODUCT_CUSTOMER_BINDING_PARTNER_CAPABILITY_EXTERNAL_WALLET_WITHDRAWAL_SETTLEMENT,
    ).toBe('external.wallet.withdrawal.settlement');
    expect(A7_PRODUCT_CUSTOMER_BINDING_PARTNER_OPERATION_TYPE_OUTBOUND_BANK_SETTLEMENT).toBe(
      'OUTBOUND_BANK_SETTLEMENT',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_PARTNER_ENVIRONMENT_SANDBOX).toBe('sandbox');
    expect(A7_PRODUCT_CUSTOMER_BINDING_PARTNER_ENVIRONMENT_PRODUCTION).toBe('production');
  });

  it('binds the A7 product-state vocabulary to the A7T02 frozen ASSIGN_* and FUNDING_* states', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_ASSIGN_STATES).toEqual([
      'ASSIGN_REQUESTED',
      'ASSIGN_PENDING',
      'ASSIGN_ACTIVE',
      'ASSIGN_SUSPENDED',
      'ASSIGN_FAILED',
      'ASSIGN_CLOSED',
    ]);
    expect(A7_PRODUCT_CUSTOMER_BINDING_FUNDING_STATES).toEqual([
      'FUNDING_REQUESTED',
      'FUNDING_PENDING_VERIFICATION',
      'FUNDING_SETTLED',
      'FUNDING_UNKNOWN',
      'FUNDING_SUSPENDED',
      'FUNDING_FAILED',
      'FUNDING_CLOSED',
    ]);
    expect(A7_PRODUCT_CUSTOMER_BINDING_ALL_STATES).toEqual([
      ...A7_PRODUCT_CUSTOMER_BINDING_ASSIGN_STATES,
      ...A7_PRODUCT_CUSTOMER_BINDING_FUNDING_STATES,
    ]);
  });

  it('binds the A3 binding recheck failure codes to the A3 binding authority', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A3_BINDING_MISSING).toBe('A3_BINDING_MISSING');
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A3_BINDING_NOT_ACTIVE).toBe('A3_BINDING_NOT_ACTIVE');
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A3_STALE_BINDING).toBe('A3_STALE_BINDING');
  });

  it('binds the virtual-account ownership failure codes to the existing virtual-account module', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_VIRTUAL_ACCOUNT_MISSING).toBe(
      'VIRTUAL_ACCOUNT_MISSING',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_VIRTUAL_ACCOUNT_INACTIVE).toBe(
      'VIRTUAL_ACCOUNT_INACTIVE',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_VIRTUAL_ACCOUNT_OWNER_MISMATCH).toBe(
      'VIRTUAL_ACCOUNT_OWNER_MISMATCH',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_VIRTUAL_ACCOUNT_PROVIDER_MISMATCH).toBe(
      'VIRTUAL_ACCOUNT_PROVIDER_MISMATCH',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_VIRTUAL_ACCOUNT_NUMBER_MISMATCH).toBe(
      'VIRTUAL_ACCOUNT_NUMBER_MISMATCH',
    );
  });

  it('binds the A4 product-policy failure codes to the A4 product-policy authority', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A4_POLICY_DECISION_MISSING).toBe(
      'A4_POLICY_DECISION_MISSING',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A4_POLICY_DECISION_NOT_EXECUTABLE).toBe(
      'A4_POLICY_DECISION_NOT_EXECUTABLE',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A4_POLICY_DECISION_EXPIRED).toBe(
      'A4_POLICY_DECISION_EXPIRED',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A4_POLICY_LIMIT_INSUFFICIENT).toBe(
      'A4_POLICY_LIMIT_INSUFFICIENT',
    );
  });

  it('binds the A2 authorization failure codes to the A2 authorization authority', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A2_AUTHORIZATION_MISSING).toBe(
      'A2_AUTHORIZATION_MISSING',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A2_AUTHORIZATION_DENIED).toBe(
      'A2_AUTHORIZATION_DENIED',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A2_AUTHORIZATION_STALE).toBe(
      'A2_AUTHORIZATION_STALE',
    );
  });

  it('binds the A6 partner reference failure codes to the A6 partner boundary', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6_PARTNER_CONNECTION_UNAVAILABLE).toBe(
      'A6_PARTNER_CONNECTION_UNAVAILABLE',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6_PARTNER_REFERENCE_MISSING).toBe(
      'A6_PARTNER_REFERENCE_MISSING',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6_PARTNER_REFERENCE_REPLAYED).toBe(
      'A6_PARTNER_REFERENCE_REPLAYED',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6_PARTNER_REFERENCE_STALE).toBe(
      'A6_PARTNER_REFERENCE_STALE',
    );
  });

  it('binds the A6T04 funding-target failure codes to the A6T04 funding-target authority', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_NOT_FOUND).toBe(
      'A6T04_TARGET_NOT_FOUND',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_TYPE_UNSUPPORTED).toBe(
      'A6T04_TARGET_TYPE_UNSUPPORTED',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_NOT_VERIFIED).toBe(
      'A6T04_TARGET_NOT_VERIFIED',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_NOT_ACTIVE).toBe(
      'A6T04_TARGET_NOT_ACTIVE',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_VERSION_STALE).toBe(
      'A6T04_TARGET_VERSION_STALE',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_TARGET_OWNERSHIP_MISMATCH).toBe(
      'A6T04_TARGET_OWNERSHIP_MISMATCH',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_CONSENT_INVALID).toBe('A6T04_CONSENT_INVALID');
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_A6T04_CURRENCY_UNSUPPORTED).toBe(
      'A6T04_CURRENCY_UNSUPPORTED',
    );
  });

  it('binds the bank directory, currency, purpose, and operations evidence failure codes', () => {
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_BANK_NOT_FOUND).toBe('BANK_NOT_FOUND');
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_CURRENCY_MISMATCH).toBe('CURRENCY_MISMATCH');
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_PRODUCT_PURPOSE_MISMATCH).toBe(
      'PRODUCT_PURPOSE_MISMATCH',
    );
    expect(A7_PRODUCT_CUSTOMER_BINDING_FAILURE_OPERATIONS_EVIDENCE_UNAVAILABLE).toBe(
      'OPERATIONS_EVIDENCE_UNAVAILABLE',
    );
  });
});
