import {
  A7_PRODUCT_LIFECYCLE_STATE_PENDING,
  A7_PRODUCT_LIFECYCLE_STATE_ADMITTED,
  A7_PRODUCT_LIFECYCLE_STATE_PENDING_PARTNER,
  A7_PRODUCT_LIFECYCLE_STATE_PENDING_VERIFICATION,
  A7_PRODUCT_LIFECYCLE_STATE_UNKNOWN,
  A7_PRODUCT_LIFECYCLE_STATE_MANUAL_REVIEW,
  A7_PRODUCT_LIFECYCLE_STATE_RETRY_SCHEDULED,
  A7_PRODUCT_LIFECYCLE_STATE_RECOVERY_ISSUED,
  A7_PRODUCT_LIFECYCLE_STATE_FAILED,
  A7_PRODUCT_LIFECYCLE_STATE_CANCELLED,
  A7_PRODUCT_LIFECYCLE_RETRY_CLASS_NONE,
  A7_PRODUCT_LIFECYCLE_RETRY_CLASS_SAFE_TRANSPORT,
  A7_PRODUCT_LIFECYCLE_RETRY_CLASS_TIMEOUT,
  A7_PRODUCT_LIFECYCLE_OUTCOME_VERIFIED,
  A7_PRODUCT_LIFECYCLE_OUTCOME_PENDING,
  A7_PRODUCT_LIFECYCLE_OUTCOME_UNKNOWN,
  A7_PRODUCT_LIFECYCLE_INTERNAL_IDEMPOTENCY_SCOPE,
  A7_PRODUCT_LIFECYCLE_HANDOFF_SCOPE,
  A7_PRODUCT_LIFECYCLE_CONTRACT_NAME,
  A7_PRODUCT_LIFECYCLE_CONTRACT_VERSION,
} from '../src/policy/a7-product-lifecycle.constants';

describe('A7 product lifecycle types (A7T07)', () => {
  it('exposes the A7 product lifecycle state constants', () => {
    expect(A7_PRODUCT_LIFECYCLE_STATE_PENDING).toBe('LIFECYCLE_PENDING');
    expect(A7_PRODUCT_LIFECYCLE_STATE_ADMITTED).toBe('LIFECYCLE_ADMITTED');
    expect(A7_PRODUCT_LIFECYCLE_STATE_PENDING_PARTNER).toBe('LIFECYCLE_PENDING_PARTNER');
    expect(A7_PRODUCT_LIFECYCLE_STATE_PENDING_VERIFICATION).toBe('LIFECYCLE_PENDING_VERIFICATION');
    expect(A7_PRODUCT_LIFECYCLE_STATE_UNKNOWN).toBe('LIFECYCLE_UNKNOWN');
    expect(A7_PRODUCT_LIFECYCLE_STATE_MANUAL_REVIEW).toBe('LIFECYCLE_MANUAL_REVIEW');
    expect(A7_PRODUCT_LIFECYCLE_STATE_RETRY_SCHEDULED).toBe('LIFECYCLE_RETRY_SCHEDULED');
    expect(A7_PRODUCT_LIFECYCLE_STATE_RECOVERY_ISSUED).toBe('LIFECYCLE_RECOVERY_ISSUED');
    expect(A7_PRODUCT_LIFECYCLE_STATE_FAILED).toBe('LIFECYCLE_FAILED');
    expect(A7_PRODUCT_LIFECYCLE_STATE_CANCELLED).toBe('LIFECYCLE_CANCELLED');
  });

  it('exposes the A7 product lifecycle retry class constants', () => {
    expect(A7_PRODUCT_LIFECYCLE_RETRY_CLASS_NONE).toBe('NONE');
    expect(A7_PRODUCT_LIFECYCLE_RETRY_CLASS_SAFE_TRANSPORT).toBe('SAFE_TRANSPORT');
    expect(A7_PRODUCT_LIFECYCLE_RETRY_CLASS_TIMEOUT).toBe('TIMEOUT');
  });

  it('exposes the A7 product lifecycle outcome constants', () => {
    expect(A7_PRODUCT_LIFECYCLE_OUTCOME_VERIFIED).toBe('OUTCOME_VERIFIED');
    expect(A7_PRODUCT_LIFECYCLE_OUTCOME_PENDING).toBe('OUTCOME_PENDING');
    expect(A7_PRODUCT_LIFECYCLE_OUTCOME_UNKNOWN).toBe('OUTCOME_UNKNOWN');
  });

  it('exposes the A7 product lifecycle internal idempotency scope', () => {
    expect(A7_PRODUCT_LIFECYCLE_INTERNAL_IDEMPOTENCY_SCOPE).toBe(
      'a7.product-lifecycle.idempotency.v1',
    );
  });

  it('exposes the A7 product lifecycle handoff scope', () => {
    expect(A7_PRODUCT_LIFECYCLE_HANDOFF_SCOPE).toBe('a7-product-lifecycle-handoff.v1');
  });

  it('exposes the A7 product lifecycle contract name and version', () => {
    expect(A7_PRODUCT_LIFECYCLE_CONTRACT_NAME).toBe('A7-PRODUCT-LIFECYCLE');
    expect(A7_PRODUCT_LIFECYCLE_CONTRACT_VERSION).toBe(1);
  });
});
