import {
  A7_PRODUCT_FINANCIAL_EFFECT_CONTRACT_NAME,
  A7_PRODUCT_FINANCIAL_EFFECT_CONTRACT_VERSION,
  A7_PRODUCT_FINANCIAL_EFFECT_INTERNAL_IDEMPOTENCY_SCOPE,
  A7_PRODUCT_FINANCIAL_EFFECT_HANDOFF_SCOPE,
  A7_PRODUCT_FINANCIAL_EFFECT_OUTCOMES,
  A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_VERIFIED,
  A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_REJECTED,
  A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_SUSPENSE,
  A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_UNKNOWN,
  A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_MANUAL_REVIEW,
  A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_FAILED,
  A7_PRODUCT_FINANCIAL_EFFECT_STATES,
  A7_PRODUCT_FINANCIAL_EFFECT_STATE_PENDING,
  A7_PRODUCT_FINANCIAL_EFFECT_STATE_ADMITTED,
  A7_PRODUCT_FINANCIAL_EFFECT_STATE_SETTLEMENT_POSTED,
  A7_PRODUCT_FINANCIAL_EFFECT_STATE_SUSPENSE_RECORDED,
  A7_PRODUCT_FINANCIAL_EFFECT_STATE_COMPENSATING_POSTED,
  A7_PRODUCT_FINANCIAL_EFFECT_STATE_REVERSAL_POSTED,
  A7_PRODUCT_FINANCIAL_EFFECT_STATE_FAILED,
  A7_PRODUCT_FINANCIAL_EFFECT_STATE_CANCELLED,
  A7_PRODUCT_FINANCIAL_EFFECT_CATEGORIES,
  A7_PRODUCT_FINANCIAL_EFFECT_CATEGORY_SETTLEMENT,
  A7_PRODUCT_FINANCIAL_EFFECT_CATEGORY_SUSPENSE,
  A7_PRODUCT_FINANCIAL_EFFECT_CATEGORY_COMPENSATING,
  A7_PRODUCT_FINANCIAL_EFFECT_CATEGORY_REVERSAL,
  A7_PRODUCT_FINANCIAL_EFFECT_TERMINAL_STATES,
} from '../src/policy/a7-product-financial-effect.constants';

describe('A7 product financial effect types (A7T08)', () => {
  it('exposes the A7 product financial effect state constants', () => {
    expect(A7_PRODUCT_FINANCIAL_EFFECT_STATE_PENDING).toBe('FINANCIAL_EFFECT_PENDING');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_STATE_ADMITTED).toBe('FINANCIAL_EFFECT_ADMITTED');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_STATE_SETTLEMENT_POSTED).toBe(
      'FINANCIAL_EFFECT_SETTLEMENT_POSTED',
    );
    expect(A7_PRODUCT_FINANCIAL_EFFECT_STATE_SUSPENSE_RECORDED).toBe(
      'FINANCIAL_EFFECT_SUSPENSE_RECORDED',
    );
    expect(A7_PRODUCT_FINANCIAL_EFFECT_STATE_COMPENSATING_POSTED).toBe(
      'FINANCIAL_EFFECT_COMPENSATING_POSTED',
    );
    expect(A7_PRODUCT_FINANCIAL_EFFECT_STATE_REVERSAL_POSTED).toBe(
      'FINANCIAL_EFFECT_REVERSAL_POSTED',
    );
    expect(A7_PRODUCT_FINANCIAL_EFFECT_STATE_FAILED).toBe('FINANCIAL_EFFECT_FAILED');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_STATE_CANCELLED).toBe('FINANCIAL_EFFECT_CANCELLED');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_STATES).toHaveLength(8);
    expect(A7_PRODUCT_FINANCIAL_EFFECT_TERMINAL_STATES).toEqual([
      'FINANCIAL_EFFECT_FAILED',
      'FINANCIAL_EFFECT_CANCELLED',
    ]);
  });

  it('exposes the A7 product financial effect outcome constants', () => {
    expect(A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_VERIFIED).toBe('OUTCOME_VERIFIED');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_REJECTED).toBe('OUTCOME_REJECTED');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_SUSPENSE).toBe('OUTCOME_SUSPENSE');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_UNKNOWN).toBe('OUTCOME_UNKNOWN');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_MANUAL_REVIEW).toBe('OUTCOME_MANUAL_REVIEW');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_OUTCOME_FAILED).toBe('OUTCOME_FAILED');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_OUTCOMES).toHaveLength(6);
  });

  it('exposes the A7 product financial effect category constants', () => {
    expect(A7_PRODUCT_FINANCIAL_EFFECT_CATEGORY_SETTLEMENT).toBe('CATEGORY_SETTLEMENT');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_CATEGORY_SUSPENSE).toBe('CATEGORY_SUSPENSE');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_CATEGORY_COMPENSATING).toBe('CATEGORY_COMPENSATING');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_CATEGORY_REVERSAL).toBe('CATEGORY_REVERSAL');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_CATEGORIES).toHaveLength(4);
  });

  it('exposes the A7 product financial effect internal idempotency scope', () => {
    expect(A7_PRODUCT_FINANCIAL_EFFECT_INTERNAL_IDEMPOTENCY_SCOPE).toBe(
      'a7.product-financial-effect.idempotency.v1',
    );
  });

  it('exposes the A7 product financial effect handoff scope', () => {
    expect(A7_PRODUCT_FINANCIAL_EFFECT_HANDOFF_SCOPE).toBe(
      'a7-product-financial-effect-handoff.v1',
    );
  });

  it('exposes the A7 product financial effect contract name and version', () => {
    expect(A7_PRODUCT_FINANCIAL_EFFECT_CONTRACT_NAME).toBe('A7-PRODUCT-FINANCIAL-EFFECT');
    expect(A7_PRODUCT_FINANCIAL_EFFECT_CONTRACT_VERSION).toBe(1);
  });
});
