import {
  A7_PRODUCT_CONSENT_APPROVED_JURISDICTIONS,
  A7_PRODUCT_CONSENT_PURPOSES,
  A7_PRODUCT_DATA_HANDLING_LEVELS,
  A7_PRODUCT_DATA_MINIMIZATION_AUDIT_ACTOR,
  A7_PRODUCT_DATA_MINIMIZATION_AUDIT_ENTITY_TYPE,
  A7_PRODUCT_DATA_MINIMIZATION_CONTRACT_DOCUMENT,
  A7_PRODUCT_DATA_MINIMIZATION_CONTRACT_NAME,
  A7_PRODUCT_DATA_MINIMIZATION_CONTRACT_VERSION,
  A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES,
  A7_PRODUCT_DATA_MINIMIZATION_FAILURE_INVALID_COMMAND,
  A7_PRODUCT_DATA_MINIMIZATION_FAILURE_QUERY_UNAVAILABLE,
  A7_PRODUCT_DATA_MINIMIZATION_INTERNAL_IDEMPOTENCY_SCOPE,
  A7_PRODUCT_DATA_MINIMIZATION_PROVIDER_IDEMPOTENCY_SCOPE,
  A7_PRODUCT_DATA_MINIMIZATION_REFERENCE_PREFIX,
  A7_PRODUCT_DATA_MINIMIZATION_RETENTION_SECONDS,
  A7_PRODUCT_DISCLOSURE_AUDIENCES,
  A7_PRODUCT_LEGAL_HOLD_SCOPES,
  A7_PRODUCT_RETENTION_DATASETS,
  A7_PRODUCT_SECRET_CATEGORIES,
} from '../src/policy/a7-product-data-minimization.constants';

describe('A7T10 constants', () => {
  it('freezes the A7 product data minimization contract identity', () => {
    expect(A7_PRODUCT_DATA_MINIMIZATION_CONTRACT_NAME).toBe('A7-PRODUCT-DATA-MINIMIZATION');
    expect(A7_PRODUCT_DATA_MINIMIZATION_CONTRACT_VERSION).toBe(1);
    expect(A7_PRODUCT_DATA_MINIMIZATION_CONTRACT_DOCUMENT).toBe(
      'docs/A7-PRODUCT-DATA-CLASSIFICATION-MATRIX.md',
    );
  });

  it('freezes the A7 product data minimization internal idempotency scope, provider scope, retention, audit entity type, and audit actor', () => {
    expect(A7_PRODUCT_DATA_MINIMIZATION_INTERNAL_IDEMPOTENCY_SCOPE).toBe(
      'a7.product-data-minimization.idempotency.v1',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_PROVIDER_IDEMPOTENCY_SCOPE).toBe(
      'nibss.nip.external-operation.v1',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_RETENTION_SECONDS).toBe(86_400);
    expect(A7_PRODUCT_DATA_MINIMIZATION_AUDIT_ENTITY_TYPE).toBe('A7_PRODUCT_DATA_MINIMIZATION');
    expect(A7_PRODUCT_DATA_MINIMIZATION_AUDIT_ACTOR).toBe('a7-product-data-minimization');
  });

  it('freezes the A7 product data minimization reference prefix', () => {
    expect(A7_PRODUCT_DATA_MINIMIZATION_REFERENCE_PREFIX).toBe('a7-product-data-minimization');
  });

  it('freezes the A7 product data minimization failure codes (frozen vocabulary)', () => {
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_INVALID_COMMAND).toBe(
      'A7_PRODUCT_DATA_MINIMIZATION_INVALID_COMMAND',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_QUERY_UNAVAILABLE).toBe(
      'A7_PRODUCT_DATA_MINIMIZATION_QUERY_UNAVAILABLE',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_CLASSIFICATION_NOT_REGISTERED',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_CONSENT_EXPIRED',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_CONSENT_REVOKED',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_CONSENT_PURPOSE_MISMATCH',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_CONSENT_JURISDICTION_MISMATCH',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_CONSENT_MISSING',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_RETENTION_HOLD_ACTIVE',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_RETENTION_BELOW_FLOOR',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_HOLD_AUTHORITY_MISSING',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_HOLD_NOT_FOUND',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_SECRET_IN_RAW_PAYLOAD',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_SECRET_IN_SUPPORT_TRACE',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_DISCLOSURE_AUDIENCE_TOO_LOW',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_DISCLOSURE_FIELD_NOT_REGISTERED',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_DISCLOSURE_REJECTED_HIGHLY_RESTRICTED',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_DISCLOSURE_BEYOND_LEGAL_HOLD',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_PARTNER_PAYLOAD_REJECTED',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES).toContain(
      'A7_PRODUCT_DATA_MINIMIZATION_PARTNER_PAYLOAD_MISSING_FIELD',
    );
    expect(A7_PRODUCT_DATA_MINIMIZATION_FAILURE_CODES.length).toBe(20);
  });

  it('freezes the A7 product consent purpose and approved jurisdiction vocabularies (reused from A6T10)', () => {
    expect(A7_PRODUCT_CONSENT_PURPOSES).toEqual(['PRODUCT_VIRTUAL_ACCOUNT_INBOUND_FUNDING']);
    expect(A7_PRODUCT_CONSENT_APPROVED_JURISDICTIONS).toEqual(['NG']);
  });

  it('freezes the A7 product retention dataset vocabulary (frozen)', () => {
    expect(A7_PRODUCT_RETENTION_DATASETS).toContain('A7_PRODUCT_OPERATION');
    expect(A7_PRODUCT_RETENTION_DATASETS).toContain('A7_PRODUCT_COMMAND');
    expect(A7_PRODUCT_RETENTION_DATASETS).toContain('A7_PRODUCT_LIFECYCLE');
    expect(A7_PRODUCT_RETENTION_DATASETS).toContain('A7_PRODUCT_FINANCIAL_EFFECT');
    expect(A7_PRODUCT_RETENTION_DATASETS).toContain('A7_PRODUCT_CUSTOMER_BINDING');
    expect(A7_PRODUCT_RETENTION_DATASETS).toContain('A7_PRODUCT_NOTIFICATION_DELIVERY');
    expect(A7_PRODUCT_RETENTION_DATASETS).toContain('A7_PRODUCT_DISCLOSURE');
    expect(A7_PRODUCT_RETENTION_DATASETS).toContain('A7_PRODUCT_SUPPORT_TRACE');
    expect(A7_PRODUCT_RETENTION_DATASETS).toContain('A7_PRODUCT_RECONCILIATION');
    expect(A7_PRODUCT_RETENTION_DATASETS.length).toBe(9);
  });

  it('freezes the A7 product legal-hold scope vocabulary (frozen; mirrors the retention dataset vocabulary)', () => {
    expect(A7_PRODUCT_LEGAL_HOLD_SCOPES).toEqual(A7_PRODUCT_RETENTION_DATASETS);
  });

  it('freezes the A7 product disclosure audience vocabulary (reused from A6T10)', () => {
    expect(A7_PRODUCT_DISCLOSURE_AUDIENCES).toEqual([
      'SUPPORT',
      'OPERATIONS',
      'RECONCILIATION',
      'FINANCE',
      'COMPLIANCE',
      'LEGAL',
      'SECURITY',
      'A6_TEN_INTERNAL',
    ]);
  });

  it('freezes the A7 product data handling level vocabulary (reused from A6T10)', () => {
    expect(A7_PRODUCT_DATA_HANDLING_LEVELS).toEqual([
      'PUBLIC',
      'INTERNAL',
      'CONFIDENTIAL',
      'RESTRICTED',
      'HIGHLY_RESTRICTED',
    ]);
  });

  it('freezes the A7 product secret category vocabulary (reused from A6T10)', () => {
    expect(A7_PRODUCT_SECRET_CATEGORIES).toContain('PARTNER_CLIENT_AUTHENTICATION');
    expect(A7_PRODUCT_SECRET_CATEGORIES).toContain('PARTNER_REQUEST_SIGNING_KEY');
    expect(A7_PRODUCT_SECRET_CATEGORIES).toContain('CALLBACK_SECRET');
    expect(A7_PRODUCT_SECRET_CATEGORIES).toContain('CALLBACK_SIGNATURE');
    expect(A7_PRODUCT_SECRET_CATEGORIES).toContain('PRIVATE_KEY');
    expect(A7_PRODUCT_SECRET_CATEGORIES).toContain('CUSTOMER_PIN');
    expect(A7_PRODUCT_SECRET_CATEGORIES).toContain('CUSTOMER_OTP');
    expect(A7_PRODUCT_SECRET_CATEGORIES).toContain('DEVICE_FINGERPRINT_RAW');
    expect(A7_PRODUCT_SECRET_CATEGORIES).toContain('RISK_NARRATIVE_RAW');
    expect(A7_PRODUCT_SECRET_CATEGORIES).toContain('COMPLIANCE_CASE_RAW');
    expect(A7_PRODUCT_SECRET_CATEGORIES.length).toBe(10);
  });
});
