import {
  A7_PRODUCT_NOTIFICATION_DELIVERY_CONTRACT_NAME,
  A7_PRODUCT_NOTIFICATION_DELIVERY_CONTRACT_VERSION,
  A7_PRODUCT_NOTIFICATION_EVENT_IDENTITY_NAMESPACE,
  A7_PRODUCT_NOTIFICATION_DISPATCH_IDENTITY_NAMESPACE,
  A7_PRODUCT_NOTIFICATION_DELIVERY_INTERNAL_IDEMPOTENCY_SCOPE,
  A7_PRODUCT_NOTIFICATION_DELIVERY_PROVIDER_IDEMPOTENCY_SCOPE,
  A7_PRODUCT_NOTIFICATION_DELIVERY_IDEMPOTENCY_RETENTION_SECONDS,
  A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ENTITY_TYPE,
  A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTOR,
  A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTION_RESERVED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTION_ADMITTED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTION_SUPPRESSED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTION_FAILED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTION_REPLAYED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_OUTBOX_EVENT_TYPE,
  A7_PRODUCT_NOTIFICATION_DELIVERY_OUTBOX_EVENT_CLASSIFICATION,
  A7_PRODUCT_NOTIFICATION_DELIVERY_OUTBOX_EVENT_RETENTION_CLASS,
  A7_PRODUCT_NOTIFICATION_DELIVERY_STATES,
  A7_PRODUCT_NOTIFICATION_DELIVERY_STATE_PENDING,
  A7_PRODUCT_NOTIFICATION_DELIVERY_STATE_DISPATCHED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_STATE_SUPPRESSED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_STATE_FAILED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_STATE_REPLAYED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNELS,
  A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNEL_EMAIL,
  A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNEL_SMS,
  A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNEL_PUSH,
  A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNEL_IN_APP,
  A7_PRODUCT_NOTIFICATION_DELIVERY_ASSIGN_STATES,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FUNDING_STATES,
  A7_PRODUCT_NOTIFICATION_DELIVERY_ALL_STATES,
  A7_PRODUCT_NOTIFICATION_DELIVERY_CAPABILITY_ASSIGN,
  A7_PRODUCT_NOTIFICATION_DELIVERY_CAPABILITY_INBOUND_FUNDING,
  A7_PRODUCT_NOTIFICATION_DELIVERY_ACTION_ASSIGN,
  A7_PRODUCT_NOTIFICATION_DELIVERY_ACTION_LIFECYCLE,
  A7_PRODUCT_NOTIFICATION_DELIVERY_PARTNER_KEY,
  A7_PRODUCT_NOTIFICATION_DELIVERY_PARTNER_CAPABILITY,
  A7_PRODUCT_NOTIFICATION_DELIVERY_PARTNER_OPERATION,
  A7_PRODUCT_NOTIFICATION_DELIVERY_HANDOFF_SCOPE,
  A7_PRODUCT_NOTIFICATION_DELIVERY_HANDOFF_VALIDITY_SECONDS,
  A7_PRODUCT_NOTIFICATION_EVENT_REFERENCE_PREFIX,
  A7_PRODUCT_NOTIFICATION_DISPATCH_REFERENCE_PREFIX,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A2_AUTHORIZATION_MISSING,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A2_AUTHORIZATION_STALE,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A2_AUTHORIZATION_DENIED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_CUSTOMER_PREFERENCE_MISSING,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_CUSTOMER_PREFERENCE_STALE,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_CUSTOMER_PREFERENCE_DISABLED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A4_POLICY_DECISION_MISSING,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A4_POLICY_DECISION_EXPIRED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A4_POLICY_DECISION_NOT_EXECUTABLE,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A7T04_PRODUCT_CUSTOMER_BINDING_MISSING,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A7T04_PRODUCT_CUSTOMER_BINDING_FAILED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A7T05_PRODUCT_COMMAND_MISSING,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PAYLOAD_SECRET_PRESENT,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PAYLOAD_DISCLOSURE_REJECTED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PAYLOAD_DISCLOSURE_AUDIENCE_TOO_LOW,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PAYLOAD_CLASSIFICATION_NOT_REGISTERED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_IDEMPOTENCY_IN_PROGRESS,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_REQUEST_HASH_CONFLICT,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_OPERATIONS_EVIDENCE_UNAVAILABLE,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_OUTBOX_PUBLICATION_FAILED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_NOTIFICATION_CHANNEL_UNSUPPORTED,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PAYLOAD_HASH_MISMATCH,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_TEMPLATE_REFERENCE_INVALID,
  A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PRODUCT_CATALOG_REJECTED,
} from '../src/policy/a7-product-notification-delivery.constants';

describe('A7 product notification delivery constants (A7T06)', () => {
  it('freezes the A7 product notification delivery contract name and version', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_CONTRACT_NAME).toBe('A7-NOTIFICATION-DELIVERY');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_CONTRACT_VERSION).toBe(1);
  });

  it('freezes the A7 product notification delivery identity namespaces', () => {
    expect(A7_PRODUCT_NOTIFICATION_EVENT_IDENTITY_NAMESPACE).toBe('A7-NOTIFICATION-DELIVERY');
    expect(A7_PRODUCT_NOTIFICATION_DISPATCH_IDENTITY_NAMESPACE).toBe('A7-NOTIFICATION-DISPATCH');
  });

  it('separates the A7 internal idempotency scope from the A6T05 provider idempotency scope', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_INTERNAL_IDEMPOTENCY_SCOPE).toBe(
      'a7.notification-dispatch.idempotency.v1',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_PROVIDER_IDEMPOTENCY_SCOPE).toBe(
      'nibss.nip.external-operation.v1',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_INTERNAL_IDEMPOTENCY_SCOPE).not.toBe(
      A7_PRODUCT_NOTIFICATION_DELIVERY_PROVIDER_IDEMPOTENCY_SCOPE,
    );
  });

  it('aligns the A7 product notification delivery idempotency retention with Operations', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_IDEMPOTENCY_RETENTION_SECONDS).toBe(86_400);
  });

  it('freezes the A7 product notification delivery audit entity type and actor', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ENTITY_TYPE).toBe('A7_NOTIFICATION_DISPATCH');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTOR).toBe('a7-product-notification-delivery');
  });

  it('freezes the A7 product notification delivery audit action codes', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTION_RESERVED).toBe(
      'A7_NOTIFICATION_DISPATCH_RESERVED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTION_ADMITTED).toBe(
      'A7_NOTIFICATION_DISPATCH_ADMITTED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTION_SUPPRESSED).toBe(
      'A7_NOTIFICATION_DISPATCH_SUPPRESSED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTION_FAILED).toBe(
      'A7_NOTIFICATION_DISPATCH_FAILED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_AUDIT_ACTION_REPLAYED).toBe(
      'A7_NOTIFICATION_DISPATCH_REPLAYED',
    );
  });

  it('freezes the A7 product notification delivery outbox event type, classification, and retention class', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_OUTBOX_EVENT_TYPE).toBe(
      'A7ProductNotificationDispatched',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_OUTBOX_EVENT_CLASSIFICATION).toBe(
      'INTERNAL_OPERATIONS',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_OUTBOX_EVENT_RETENTION_CLASS).toBe(
      'OPERATIONS_DEFAULT',
    );
  });

  it('freezes the A7 product notification delivery state vocabulary', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_STATES).toEqual([
      A7_PRODUCT_NOTIFICATION_DELIVERY_STATE_PENDING,
      A7_PRODUCT_NOTIFICATION_DELIVERY_STATE_DISPATCHED,
      A7_PRODUCT_NOTIFICATION_DELIVERY_STATE_SUPPRESSED,
      A7_PRODUCT_NOTIFICATION_DELIVERY_STATE_FAILED,
      A7_PRODUCT_NOTIFICATION_DELIVERY_STATE_REPLAYED,
    ]);
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_STATES).toContain('PENDING');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_STATES).toContain('DISPATCHED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_STATES).toContain('SUPPRESSED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_STATES).toContain('FAILED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_STATES).toContain('REPLAYED');
  });

  it('freezes the A7 product notification delivery notification channel vocabulary', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNELS).toEqual([
      A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNEL_EMAIL,
      A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNEL_SMS,
      A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNEL_PUSH,
      A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNEL_IN_APP,
    ]);
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNELS).toContain('email');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNELS).toContain('sms');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNELS).toContain('push');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_CHANNELS).toContain('inApp');
  });

  it('reuses the A7 product-state vocabulary from the A7T02 product catalog', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_ASSIGN_STATES).toContain('ASSIGN_REQUESTED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_ASSIGN_STATES).toContain('ASSIGN_PENDING');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_ASSIGN_STATES).toContain('ASSIGN_ACTIVE');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_ASSIGN_STATES).toContain('ASSIGN_SUSPENDED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_ASSIGN_STATES).toContain('ASSIGN_FAILED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_ASSIGN_STATES).toContain('ASSIGN_CLOSED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FUNDING_STATES).toContain('FUNDING_REQUESTED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FUNDING_STATES).toContain(
      'FUNDING_PENDING_VERIFICATION',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FUNDING_STATES).toContain('FUNDING_SETTLED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FUNDING_STATES).toContain('FUNDING_UNKNOWN');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FUNDING_STATES).toContain('FUNDING_SUSPENDED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FUNDING_STATES).toContain('FUNDING_FAILED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FUNDING_STATES).toContain('FUNDING_CLOSED');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_ALL_STATES).toEqual([
      ...A7_PRODUCT_NOTIFICATION_DELIVERY_ASSIGN_STATES,
      ...A7_PRODUCT_NOTIFICATION_DELIVERY_FUNDING_STATES,
    ]);
  });

  it('freezes the A7 product notification delivery capability and action keys', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_CAPABILITY_ASSIGN).toBe('virtual-account.assign');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_CAPABILITY_INBOUND_FUNDING).toBe(
      'virtual-account.inbound-funding',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_ACTION_ASSIGN).toBe('assign');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_ACTION_LIFECYCLE).toBe('lifecycle');
  });

  it('freezes the A6 partner identity reused by A7 product notification delivery', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_PARTNER_KEY).toBe('NIBSS_NIP');
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_PARTNER_CAPABILITY).toBe(
      'external.wallet.withdrawal.settlement',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_PARTNER_OPERATION).toBe('OUTBOUND_BANK_SETTLEMENT');
  });

  it('freezes the A7 product notification delivery handoff scope and validity', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_HANDOFF_SCOPE).toBe(
      'a7-notification-dispatch-handoff.v1',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_HANDOFF_VALIDITY_SECONDS).toBe(15 * 60);
  });

  it('freezes the A7 product notification delivery reference prefixes', () => {
    expect(A7_PRODUCT_NOTIFICATION_EVENT_REFERENCE_PREFIX).toBe('a7-notification-event');
    expect(A7_PRODUCT_NOTIFICATION_DISPATCH_REFERENCE_PREFIX).toBe('a7-notification-dispatch');
  });

  it('freezes the A7 product notification delivery failure codes', () => {
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A2_AUTHORIZATION_MISSING).toBe(
      'A7_NOTIFICATION_A2_AUTHORIZATION_MISSING',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A2_AUTHORIZATION_STALE).toBe(
      'A7_NOTIFICATION_A2_AUTHORIZATION_STALE',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A2_AUTHORIZATION_DENIED).toBe(
      'A7_NOTIFICATION_A2_AUTHORIZATION_DENIED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_CUSTOMER_PREFERENCE_MISSING).toBe(
      'A7_NOTIFICATION_CUSTOMER_PREFERENCE_MISSING',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_CUSTOMER_PREFERENCE_STALE).toBe(
      'A7_NOTIFICATION_CUSTOMER_PREFERENCE_STALE',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_CUSTOMER_PREFERENCE_DISABLED).toBe(
      'A7_NOTIFICATION_CUSTOMER_PREFERENCE_DISABLED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A4_POLICY_DECISION_MISSING).toBe(
      'A7_NOTIFICATION_A4_POLICY_DECISION_MISSING',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A4_POLICY_DECISION_EXPIRED).toBe(
      'A7_NOTIFICATION_A4_POLICY_DECISION_EXPIRED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A4_POLICY_DECISION_NOT_EXECUTABLE).toBe(
      'A7_NOTIFICATION_A4_POLICY_DECISION_NOT_EXECUTABLE',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A7T04_PRODUCT_CUSTOMER_BINDING_MISSING).toBe(
      'A7_NOTIFICATION_A7T04_PRODUCT_CUSTOMER_BINDING_MISSING',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A7T04_PRODUCT_CUSTOMER_BINDING_FAILED).toBe(
      'A7_NOTIFICATION_A7T04_PRODUCT_CUSTOMER_BINDING_FAILED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_A7T05_PRODUCT_COMMAND_MISSING).toBe(
      'A7_NOTIFICATION_A7T05_PRODUCT_COMMAND_MISSING',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PAYLOAD_SECRET_PRESENT).toBe(
      'A7_NOTIFICATION_PAYLOAD_SECRET_PRESENT',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PAYLOAD_DISCLOSURE_REJECTED).toBe(
      'A7_NOTIFICATION_PAYLOAD_DISCLOSURE_REJECTED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PAYLOAD_DISCLOSURE_AUDIENCE_TOO_LOW).toBe(
      'A7_NOTIFICATION_PAYLOAD_DISCLOSURE_AUDIENCE_TOO_LOW',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PAYLOAD_CLASSIFICATION_NOT_REGISTERED).toBe(
      'A7_NOTIFICATION_PAYLOAD_CLASSIFICATION_NOT_REGISTERED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_IDEMPOTENCY_IN_PROGRESS).toBe(
      'A7_NOTIFICATION_IDEMPOTENCY_IN_PROGRESS',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_REQUEST_HASH_CONFLICT).toBe(
      'A7_NOTIFICATION_REQUEST_HASH_CONFLICT',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_OPERATIONS_EVIDENCE_UNAVAILABLE).toBe(
      'A7_NOTIFICATION_OPERATIONS_EVIDENCE_UNAVAILABLE',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_OUTBOX_PUBLICATION_FAILED).toBe(
      'A7_NOTIFICATION_OUTBOX_PUBLICATION_FAILED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_NOTIFICATION_CHANNEL_UNSUPPORTED).toBe(
      'A7_NOTIFICATION_NOTIFICATION_CHANNEL_UNSUPPORTED',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PAYLOAD_HASH_MISMATCH).toBe(
      'A7_NOTIFICATION_PAYLOAD_HASH_MISMATCH',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_TEMPLATE_REFERENCE_INVALID).toBe(
      'A7_NOTIFICATION_TEMPLATE_REFERENCE_INVALID',
    );
    expect(A7_PRODUCT_NOTIFICATION_DELIVERY_FAILURE_PRODUCT_CATALOG_REJECTED).toBe(
      'A7_NOTIFICATION_PRODUCT_CATALOG_REJECTED',
    );
  });
});
