import {
  B1_BILLING_ENGINE_AUDIT_ACTOR,
  B1_BILLING_ENGINE_AUDIT_ENTITY_TYPE,
  B1_BILLING_ENGINE_BILLING_PERIOD_KEY,
  B1_BILLING_ENGINE_BILLING_RECORD_STATES,
  B1_BILLING_ENGINE_CLASSIFICATION_LEVELS,
  B1_BILLING_ENGINE_COMPATIBILITY_RULE_IDS,
  B1_BILLING_ENGINE_CONSUMER_CONTRACT_IDS,
  B1_BILLING_ENGINE_CONTRACT_NAME,
  B1_BILLING_ENGINE_CONTRACT_VERSION,
  B1_BILLING_ENGINE_DATA_CONTROL_CLASSIFICATIONS,
  B1_BILLING_ENGINE_DECLARED_DEPENDENCIES,
  B1_BILLING_ENGINE_DOCUMENT_KIND_BILLING_RECORD,
  B1_BILLING_ENGINE_DOCUMENT_KIND_INVOICE,
  B1_BILLING_ENGINE_DOCUMENT_KIND_INVOICE_LINE,
  B1_BILLING_ENGINE_DOCUMENT_KIND_STATEMENT,
  B1_BILLING_ENGINE_DOCUMENT_KIND_STATEMENT_LINE,
  B1_BILLING_ENGINE_DOCUMENT_KIND_STATEMENT_PERIOD,
  B1_BILLING_ENGINE_DOCUMENT_KINDS,
  B1_BILLING_ENGINE_FAILURE_CODES,
  B1_BILLING_ENGINE_FAILURE_INCOMPATIBLE,
  B1_BILLING_ENGINE_FAILURE_INVALID_COMMAND,
  B1_BILLING_ENGINE_IDEMPOTENCY_RETENTION_SECONDS,
  B1_BILLING_ENGINE_INTERNAL_IDEMPOTENCY_SCOPE,
  B1_BILLING_ENGINE_INVOICE_IDEMPOTENCY_SCOPE,
  B1_BILLING_ENGINE_INVOICE_STATES,
  B1_BILLING_ENGINE_LINE_KIND_FEE,
  B1_BILLING_ENGINE_LINE_KINDS,
  B1_BILLING_ENGINE_OUTBOX_EVENT_TYPE,
  B1_BILLING_ENGINE_PROHIBITED_ADJACENT_SCOPES,
  B1_BILLING_ENGINE_PROHIBITED_DEPENDENCIES,
  B1_BILLING_ENGINE_REFERENCE_PREFIX,
  B1_BILLING_ENGINE_REPLAY_RULE_IDS,
  B1_BILLING_ENGINE_RETENTION_DAYS,
  B1_BILLING_ENGINE_RULE_KINDS,
  B1_BILLING_ENGINE_RULE_OUTCOMES,
  B1_BILLING_ENGINE_SCOPE_ACCOUNTING_UNIT,
  B1_BILLING_ENGINE_SCOPE_CURRENCY,
  B1_BILLING_ENGINE_SCOPE_DIRECTION,
  B1_BILLING_ENGINE_SCOPE_KEY,
  B1_BILLING_ENGINE_SCOPE_PARTNER_DEPENDENCY,
  B1_BILLING_ENGINE_SCOPE_PRODUCT_DEPENDENCY,
  B1_BILLING_ENGINE_SCOPE_PRODUCT_DEPENDENCY_VERSION,
  B1_BILLING_ENGINE_SCOPE_VERSION,
  B1_BILLING_ENGINE_STATEMENT_IDEMPOTENCY_SCOPE,
  B1_BILLING_ENGINE_STATEMENT_PERIOD_KEY,
  B1_BILLING_ENGINE_STATEMENT_STATES,
  B1_BILLING_ENGINE_VERSION_NEGOTIATION_RULE_IDS,
} from '../src/policy/b1-billing-engine.constants';

describe('B1 billing engine types (B1T05)', () => {
  it('exposes the B1 billing engine contract name and version', () => {
    expect(B1_BILLING_ENGINE_CONTRACT_NAME).toBe('B1-BILLING-ENGINE');
    expect(B1_BILLING_ENGINE_CONTRACT_VERSION).toBe(1);
  });

  it('exposes the B1 billing engine first commercial scope identity', () => {
    expect(B1_BILLING_ENGINE_SCOPE_KEY).toBe('commercial.virtual-account.inbound-funding');
    expect(B1_BILLING_ENGINE_SCOPE_VERSION).toBe(1);
    expect(B1_BILLING_ENGINE_SCOPE_DIRECTION).toBe('inbound');
    expect(B1_BILLING_ENGINE_SCOPE_CURRENCY).toBe('NGN');
    expect(B1_BILLING_ENGINE_SCOPE_ACCOUNTING_UNIT).toBe('CUSTOMER_FUNDS');
    expect(B1_BILLING_ENGINE_SCOPE_PARTNER_DEPENDENCY).toBe('NIBSS_NIP');
    expect(B1_BILLING_ENGINE_SCOPE_PRODUCT_DEPENDENCY).toBe('VIRTUAL_ACCOUNT');
    expect(B1_BILLING_ENGINE_SCOPE_PRODUCT_DEPENDENCY_VERSION).toBe(1);
  });

  it('exposes the B1 billing engine period identity', () => {
    expect(B1_BILLING_ENGINE_BILLING_PERIOD_KEY).toBe(
      'commercial.virtual-account.inbound-funding.billing-period.per-transaction.v1',
    );
    expect(B1_BILLING_ENGINE_STATEMENT_PERIOD_KEY).toBe(
      'commercial.virtual-account.inbound-funding.statement-period.daily.v1',
    );
  });

  it('exposes the B1 billing engine billing record state vocabulary', () => {
    expect(B1_BILLING_ENGINE_BILLING_RECORD_STATES).toContain('CREATED');
    expect(B1_BILLING_ENGINE_BILLING_RECORD_STATES).toContain('READY');
    expect(B1_BILLING_ENGINE_BILLING_RECORD_STATES).toContain('ISSUED');
    expect(B1_BILLING_ENGINE_BILLING_RECORD_STATES).toContain('CANCELLED');
    expect(B1_BILLING_ENGINE_BILLING_RECORD_STATES).toContain('REPLAYED');
  });

  it('exposes the B1 billing engine invoice state vocabulary', () => {
    expect(B1_BILLING_ENGINE_INVOICE_STATES).toContain('DRAFT');
    expect(B1_BILLING_ENGINE_INVOICE_STATES).toContain('GENERATED');
    expect(B1_BILLING_ENGINE_INVOICE_STATES).toContain('ISSUED');
    expect(B1_BILLING_ENGINE_INVOICE_STATES).toContain('CANCELLED');
    expect(B1_BILLING_ENGINE_INVOICE_STATES).toContain('VOIDED');
  });

  it('exposes the B1 billing engine statement state vocabulary', () => {
    expect(B1_BILLING_ENGINE_STATEMENT_STATES).toContain('OPEN');
    expect(B1_BILLING_ENGINE_STATEMENT_STATES).toContain('GENERATED');
    expect(B1_BILLING_ENGINE_STATEMENT_STATES).toContain('CLOSED');
    expect(B1_BILLING_ENGINE_STATEMENT_STATES).toContain('REGENERATED');
  });

  it('exposes the B1 billing engine document kind vocabulary', () => {
    expect(B1_BILLING_ENGINE_DOCUMENT_KIND_BILLING_RECORD).toBe('BILLING_RECORD');
    expect(B1_BILLING_ENGINE_DOCUMENT_KIND_INVOICE).toBe('INVOICE');
    expect(B1_BILLING_ENGINE_DOCUMENT_KIND_INVOICE_LINE).toBe('INVOICE_LINE');
    expect(B1_BILLING_ENGINE_DOCUMENT_KIND_STATEMENT).toBe('STATEMENT');
    expect(B1_BILLING_ENGINE_DOCUMENT_KIND_STATEMENT_LINE).toBe('STATEMENT_LINE');
    expect(B1_BILLING_ENGINE_DOCUMENT_KIND_STATEMENT_PERIOD).toBe('STATEMENT_PERIOD');
    expect(B1_BILLING_ENGINE_DOCUMENT_KINDS.length).toBe(7);
  });

  it('exposes the B1 billing engine billing line kind vocabulary', () => {
    expect(B1_BILLING_ENGINE_LINE_KINDS).toContain(B1_BILLING_ENGINE_LINE_KIND_FEE);
    expect(B1_BILLING_ENGINE_LINE_KINDS).toContain('COMMISSION');
    expect(B1_BILLING_ENGINE_LINE_KINDS).toContain('REVENUE_SHARING');
  });

  it('exposes the B1 billing engine failure code vocabulary', () => {
    expect(B1_BILLING_ENGINE_FAILURE_INVALID_COMMAND).toBe('B1_BILLING_ENGINE_INVALID_COMMAND');
    expect(B1_BILLING_ENGINE_FAILURE_INCOMPATIBLE).toBe('B1_BILLING_ENGINE_INCOMPATIBLE');
    expect(B1_BILLING_ENGINE_FAILURE_CODES.length).toBe(18);
  });

  it('exposes the B1 billing engine internal idempotency scope and retention', () => {
    expect(B1_BILLING_ENGINE_INTERNAL_IDEMPOTENCY_SCOPE).toBe('b1.billing-engine.idempotency.v1');
    expect(B1_BILLING_ENGINE_INVOICE_IDEMPOTENCY_SCOPE).toBe(
      'b1.billing-engine.invoice.idempotency.v1',
    );
    expect(B1_BILLING_ENGINE_STATEMENT_IDEMPOTENCY_SCOPE).toBe(
      'b1.billing-engine.statement.idempotency.v1',
    );
    expect(B1_BILLING_ENGINE_IDEMPOTENCY_RETENTION_SECONDS).toBe(86_400);
  });

  it('exposes the B1 billing engine audit, outbox, metric, and reference prefix', () => {
    expect(B1_BILLING_ENGINE_AUDIT_ACTOR).toBe('b1-billing-engine');
    expect(B1_BILLING_ENGINE_AUDIT_ENTITY_TYPE).toBe('B1_BILLING_DOCUMENT');
    expect(B1_BILLING_ENGINE_OUTBOX_EVENT_TYPE).toBe('B1BillingDocumentGenerated');
    expect(B1_BILLING_ENGINE_REFERENCE_PREFIX).toBe('b1-billing-document');
  });

  it('exposes the B1 billing engine retention, classification, and data control classification vocabularies', () => {
    expect(B1_BILLING_ENGINE_RETENTION_DAYS).toBe(365);
    expect(B1_BILLING_ENGINE_CLASSIFICATION_LEVELS).toContain('PUBLIC');
    expect(B1_BILLING_ENGINE_CLASSIFICATION_LEVELS).toContain('INTERNAL');
    expect(B1_BILLING_ENGINE_CLASSIFICATION_LEVELS).toContain('CONFIDENTIAL');
    expect(B1_BILLING_ENGINE_CLASSIFICATION_LEVELS).toContain('RESTRICTED');
    expect(B1_BILLING_ENGINE_CLASSIFICATION_LEVELS).toContain('HIGHLY_RESTRICTED');
    expect(B1_BILLING_ENGINE_DATA_CONTROL_CLASSIFICATIONS).toEqual(
      B1_BILLING_ENGINE_CLASSIFICATION_LEVELS,
    );
  });

  it('exposes the B1 billing engine rule outcome and rule kind vocabularies', () => {
    expect(B1_BILLING_ENGINE_RULE_OUTCOMES).toContain('PASS');
    expect(B1_BILLING_ENGINE_RULE_OUTCOMES).toContain('FAIL');
    expect(B1_BILLING_ENGINE_RULE_OUTCOMES).toContain('SKIP');
    expect(B1_BILLING_ENGINE_RULE_OUTCOMES).toContain('NOT_APPLICABLE');
    expect(B1_BILLING_ENGINE_RULE_KINDS.length).toBeGreaterThan(20);
  });

  it('exposes the B1 billing engine prohibited adjacent scopes, prohibited dependencies, and declared dependencies', () => {
    expect(B1_BILLING_ENGINE_PROHIBITED_ADJACENT_SCOPES.length).toBeGreaterThan(0);
    expect(B1_BILLING_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_CAMPAIGN_ENGINE');
    expect(B1_BILLING_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_PROMOTION_ENGINE');
    expect(B1_BILLING_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_COUPON_ENGINE');
    expect(B1_BILLING_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_REFERRAL_ENGINE');
    expect(B1_BILLING_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_CASHBACK_ENGINE');
    expect(B1_BILLING_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_LOYALTY_ENGINE');
    expect(B1_BILLING_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_REVENUE_RECOGNITION_ENGINE');
    expect(B1_BILLING_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_TAX_ENGINE');
    expect(B1_BILLING_ENGINE_DECLARED_DEPENDENCIES).toContain('A1-CANONICAL-IDENTITY');
    expect(B1_BILLING_ENGINE_DECLARED_DEPENDENCIES).toContain('A2-AUTHORIZATION-CONTEXT');
    expect(B1_BILLING_ENGINE_DECLARED_DEPENDENCIES).toContain(
      'A3-CUSTOMER-FINANCIAL-ACCOUNT-BINDING',
    );
    expect(B1_BILLING_ENGINE_DECLARED_DEPENDENCIES).toContain('A4-PRODUCT-POLICY-DECISION');
    expect(B1_BILLING_ENGINE_DECLARED_DEPENDENCIES).toContain('A5-LEDGER');
    expect(B1_BILLING_ENGINE_DECLARED_DEPENDENCIES).toContain('A6-PARTNER-ADAPTER');
    expect(B1_BILLING_ENGINE_DECLARED_DEPENDENCIES).toContain('A7-PRODUCT-CATALOG');
    expect(B1_BILLING_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-COMMERCIAL-CATALOG');
    expect(B1_BILLING_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-COMMERCIAL-DECISION');
  });

  it('exposes the B1 billing engine compatibility, consumer contract, version negotiation, and replay rule identifiers', () => {
    expect(B1_BILLING_ENGINE_COMPATIBILITY_RULE_IDS.length).toBeGreaterThan(0);
    expect(B1_BILLING_ENGINE_CONSUMER_CONTRACT_IDS.length).toBeGreaterThan(0);
    expect(B1_BILLING_ENGINE_VERSION_NEGOTIATION_RULE_IDS.length).toBeGreaterThan(0);
    expect(B1_BILLING_ENGINE_REPLAY_RULE_IDS.length).toBeGreaterThan(0);
  });
});
