import {
  B1_COMMERCIAL_CATALOG_AUDIT_ACTOR,
  B1_COMMERCIAL_CATALOG_AUDIT_ENTITY_TYPE,
  B1_COMMERCIAL_CATALOG_BILLING_CYCLE_PER_TRANSACTION,
  B1_COMMERCIAL_CATALOG_BUNDLE_KEY,
  B1_COMMERCIAL_CATALOG_BUNDLE_KEYS,
  B1_COMMERCIAL_CATALOG_CAPABILITIES,
  B1_COMMERCIAL_CATALOG_CAPABILITY_COMMISSION,
  B1_COMMERCIAL_CATALOG_CAPABILITY_FEE,
  B1_COMMERCIAL_CATALOG_CLASSIFICATION_LEVELS,
  B1_COMMERCIAL_CATALOG_COMPATIBILITY_RULE_IDS,
  B1_COMMERCIAL_CATALOG_CONSUMER_CONTRACT_IDS,
  B1_COMMERCIAL_CATALOG_CONTRACT_NAME,
  B1_COMMERCIAL_CATALOG_CONTRACT_VERSION,
  B1_COMMERCIAL_CATALOG_CUSTOMER_TIER_KEY,
  B1_COMMERCIAL_CATALOG_CUSTOMER_TIER_KEYS,
  B1_COMMERCIAL_CATALOG_DATA_CONTROL_CLASSIFICATIONS,
  B1_COMMERCIAL_CATALOG_DECLARED_DEPENDENCIES,
  B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT_COMMISSION,
  B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT_FEE,
  B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT_KEYS,
  B1_COMMERCIAL_CATALOG_FAILURE_CODES,
  B1_COMMERCIAL_CATALOG_FAILURE_INCOMPATIBLE,
  B1_COMMERCIAL_CATALOG_FAILURE_INVALID_COMMAND,
  B1_COMMERCIAL_CATALOG_FAILURE_MALFORMED,
  B1_COMMERCIAL_CATALOG_FAILURE_MISSING_BUNDLE,
  B1_COMMERCIAL_CATALOG_FAILURE_MISSING_ENTITLEMENT,
  B1_COMMERCIAL_CATALOG_FAILURE_MISSING_PACKAGE,
  B1_COMMERCIAL_CATALOG_FAILURE_MISSING_PLAN,
  B1_COMMERCIAL_CATALOG_FAILURE_MISSING_TIER,
  B1_COMMERCIAL_CATALOG_FAILURE_PROHIBITED,
  B1_COMMERCIAL_CATALOG_FAILURE_QUERY_UNAVAILABLE,
  B1_COMMERCIAL_CATALOG_FAILURE_UNSUPPORTED_CAPABILITY,
  B1_COMMERCIAL_CATALOG_FAILURE_WRONG_VERSION,
  B1_COMMERCIAL_CATALOG_FEATURE_FLAG_COMMISSION,
  B1_COMMERCIAL_CATALOG_FEATURE_FLAG_FEE,
  B1_COMMERCIAL_CATALOG_FEATURE_FLAG_KEYS,
  B1_COMMERCIAL_CATALOG_FIRST_SCOPE_CATALOG_KEY,
  B1_COMMERCIAL_CATALOG_IDEMPOTENCY_RETENTION_SECONDS,
  B1_COMMERCIAL_CATALOG_INTERNAL_IDEMPOTENCY_SCOPE,
  B1_COMMERCIAL_CATALOG_LOOKUP_KINDS,
  B1_COMMERCIAL_CATALOG_MERCHANT_TIER_KEY,
  B1_COMMERCIAL_CATALOG_MERCHANT_TIER_KEYS,
  B1_COMMERCIAL_CATALOG_METRIC_INCOMPATIBLE,
  B1_COMMERCIAL_CATALOG_METRIC_LOOKUP,
  B1_COMMERCIAL_CATALOG_METRIC_REPLAYED,
  B1_COMMERCIAL_CATALOG_OUTBOX_EVENT_TYPE,
  B1_COMMERCIAL_CATALOG_PACKAGE_KEY,
  B1_COMMERCIAL_CATALOG_PACKAGE_KEYS,
  B1_COMMERCIAL_CATALOG_PARTNER_TIER_KEY,
  B1_COMMERCIAL_CATALOG_PARTNER_TIER_KEYS,
  B1_COMMERCIAL_CATALOG_PLAN_KEYS,
  B1_COMMERCIAL_CATALOG_PLAN_KEY_COMMISSION,
  B1_COMMERCIAL_CATALOG_PLAN_KEY_FEE,
  B1_COMMERCIAL_CATALOG_PLAN_TYPES,
  B1_COMMERCIAL_CATALOG_PRICING_KEYS,
  B1_COMMERCIAL_CATALOG_PRODUCT_ENTITLEMENT_KEYS,
  B1_COMMERCIAL_CATALOG_PROHIBITED_ADJACENT_SCOPES,
  B1_COMMERCIAL_CATALOG_PROHIBITED_DEPENDENCIES,
  B1_COMMERCIAL_CATALOG_REFERENCE_PREFIX,
  B1_COMMERCIAL_CATALOG_REPLAY_RULE_IDS,
  B1_COMMERCIAL_CATALOG_SCOPE_ACCOUNTING_UNIT,
  B1_COMMERCIAL_CATALOG_SCOPE_CURRENCY,
  B1_COMMERCIAL_CATALOG_SCOPE_DIRECTION,
  B1_COMMERCIAL_CATALOG_SCOPE_KEY,
  B1_COMMERCIAL_CATALOG_SCOPE_PARTNER_DEPENDENCY,
  B1_COMMERCIAL_CATALOG_SCOPE_PRODUCT_DEPENDENCY,
  B1_COMMERCIAL_CATALOG_SCOPE_PRODUCT_DEPENDENCY_VERSION,
  B1_COMMERCIAL_CATALOG_SCOPE_RETENTION_DAYS,
  B1_COMMERCIAL_CATALOG_SCOPE_VERSION,
  B1_COMMERCIAL_CATALOG_STATE_ADMITTED,
  B1_COMMERCIAL_CATALOG_STATES,
  B1_COMMERCIAL_CATALOG_SUBSCRIPTION_PLAN_KEY,
  B1_COMMERCIAL_CATALOG_SUBSCRIPTION_PLAN_KEYS,
  B1_COMMERCIAL_CATALOG_VERSION_NEGOTIATION_RULE_IDS,
} from '../src/policy/b1-commercial-catalog.constants';

describe('B1 commercial catalog constants (B1T03)', () => {
  it('exposes the B1 commercial catalog contract name and version', () => {
    expect(B1_COMMERCIAL_CATALOG_CONTRACT_NAME).toBe('B1-COMMERCIAL-CATALOG');
    expect(B1_COMMERCIAL_CATALOG_CONTRACT_VERSION).toBe(1);
  });

  it('exposes the B1 commercial catalog first commercial scope identity', () => {
    expect(B1_COMMERCIAL_CATALOG_SCOPE_KEY).toBe('commercial.virtual-account.inbound-funding');
    expect(B1_COMMERCIAL_CATALOG_SCOPE_VERSION).toBe(1);
    expect(B1_COMMERCIAL_CATALOG_SCOPE_DIRECTION).toBe('inbound');
    expect(B1_COMMERCIAL_CATALOG_SCOPE_CURRENCY).toBe('NGN');
    expect(B1_COMMERCIAL_CATALOG_SCOPE_ACCOUNTING_UNIT).toBe('CUSTOMER_FUNDS');
    expect(B1_COMMERCIAL_CATALOG_SCOPE_PARTNER_DEPENDENCY).toBe('NIBSS_NIP');
    expect(B1_COMMERCIAL_CATALOG_SCOPE_PRODUCT_DEPENDENCY).toBe('VIRTUAL_ACCOUNT');
    expect(B1_COMMERCIAL_CATALOG_SCOPE_PRODUCT_DEPENDENCY_VERSION).toBe(1);
    expect(B1_COMMERCIAL_CATALOG_SCOPE_RETENTION_DAYS).toBe(365);
  });

  it('exposes the B1 commercial catalog first commercial scope catalog key', () => {
    expect(B1_COMMERCIAL_CATALOG_FIRST_SCOPE_CATALOG_KEY).toBe(
      'b1.commercial-catalog.v1.commercial.virtual-account.inbound-funding',
    );
  });

  it('exposes the B1 commercial catalog state vocabulary', () => {
    expect(B1_COMMERCIAL_CATALOG_STATE_ADMITTED).toBe('COMMERCIAL_DECISION_ADMITTED');
    expect(B1_COMMERCIAL_CATALOG_STATES).toContain('COMMERCIAL_DECISION_PENDING');
    expect(B1_COMMERCIAL_CATALOG_STATES).toContain('COMMERCIAL_DECISION_ADMITTED');
    expect(B1_COMMERCIAL_CATALOG_STATES).toContain('COMMERCIAL_DECISION_SUPPRESSED');
    expect(B1_COMMERCIAL_CATALOG_STATES).toContain('COMMERCIAL_DECISION_FAILED');
    expect(B1_COMMERCIAL_CATALOG_STATES).toContain('COMMERCIAL_DECISION_REPLAYED');
    expect(B1_COMMERCIAL_CATALOG_STATES).toContain('COMMERCIAL_DECISION_DISABLED');
  });

  it('exposes the B1 commercial catalog capability vocabulary', () => {
    expect(B1_COMMERCIAL_CATALOG_CAPABILITY_FEE).toBe(
      'commercial.virtual-account.inbound-funding.fee',
    );
    expect(B1_COMMERCIAL_CATALOG_CAPABILITY_COMMISSION).toBe(
      'commercial.virtual-account.inbound-funding.commission',
    );
    expect(B1_COMMERCIAL_CATALOG_CAPABILITIES).toHaveLength(2);
  });

  it('exposes the B1 commercial catalog plan, tier, entitlement, package, and bundle keys', () => {
    expect(B1_COMMERCIAL_CATALOG_PLAN_KEY_FEE).toBe(
      'commercial.virtual-account.inbound-funding.fee.v1.plan.standard',
    );
    expect(B1_COMMERCIAL_CATALOG_PLAN_KEY_COMMISSION).toBe(
      'commercial.virtual-account.inbound-funding.commission.v1.plan.standard',
    );
    expect(B1_COMMERCIAL_CATALOG_PLAN_KEYS).toHaveLength(2);
    expect(B1_COMMERCIAL_CATALOG_CUSTOMER_TIER_KEY).toBe('commercial.customer.tier.standard.v1');
    expect(B1_COMMERCIAL_CATALOG_MERCHANT_TIER_KEY).toBe('commercial.merchant.tier.standard.v1');
    expect(B1_COMMERCIAL_CATALOG_PARTNER_TIER_KEY).toBe('commercial.partner.tier.standard.v1');
    expect(B1_COMMERCIAL_CATALOG_PRODUCT_ENTITLEMENT_KEYS).toHaveLength(2);
    expect(B1_COMMERCIAL_CATALOG_PACKAGE_KEY).toBe(
      'commercial.virtual-account.inbound-funding.package.fee.commission.v1',
    );
    expect(B1_COMMERCIAL_CATALOG_BUNDLE_KEY).toBe(
      'commercial.virtual-account.inbound-funding.bundle.fee.commission.v1',
    );
    expect(B1_COMMERCIAL_CATALOG_SUBSCRIPTION_PLAN_KEY).toBe(
      'commercial.virtual-account.inbound-funding.subscription.standard.v1',
    );
    expect(B1_COMMERCIAL_CATALOG_SUBSCRIPTION_PLAN_KEYS).toContain(
      B1_COMMERCIAL_CATALOG_SUBSCRIPTION_PLAN_KEY,
    );
    expect(B1_COMMERCIAL_CATALOG_PACKAGE_KEYS).toContain(B1_COMMERCIAL_CATALOG_PACKAGE_KEY);
    expect(B1_COMMERCIAL_CATALOG_BUNDLE_KEYS).toContain(B1_COMMERCIAL_CATALOG_BUNDLE_KEY);
    expect(B1_COMMERCIAL_CATALOG_CUSTOMER_TIER_KEYS).toContain(
      B1_COMMERCIAL_CATALOG_CUSTOMER_TIER_KEY,
    );
    expect(B1_COMMERCIAL_CATALOG_MERCHANT_TIER_KEYS).toContain(
      B1_COMMERCIAL_CATALOG_MERCHANT_TIER_KEY,
    );
    expect(B1_COMMERCIAL_CATALOG_PARTNER_TIER_KEYS).toContain(
      B1_COMMERCIAL_CATALOG_PARTNER_TIER_KEY,
    );
  });

  it('exposes the B1 commercial catalog feature flag and dynamic limit keys', () => {
    expect(B1_COMMERCIAL_CATALOG_FEATURE_FLAG_FEE).toBe(
      'commercial.virtual-account.inbound-funding.fee.enabled',
    );
    expect(B1_COMMERCIAL_CATALOG_FEATURE_FLAG_COMMISSION).toBe(
      'commercial.virtual-account.inbound-funding.commission.enabled',
    );
    expect(B1_COMMERCIAL_CATALOG_FEATURE_FLAG_KEYS).toHaveLength(2);
    expect(B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT_FEE).toBe(
      'commercial.virtual-account.inbound-funding.fee.dynamic-limit.daily',
    );
    expect(B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT_COMMISSION).toBe(
      'commercial.virtual-account.inbound-funding.commission.dynamic-limit.daily',
    );
    expect(B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT_KEYS).toHaveLength(2);
    expect(B1_COMMERCIAL_CATALOG_PRICING_KEYS).toHaveLength(2);
  });

  it('exposes the B1 commercial catalog billing cycle and plan type vocabulary', () => {
    expect(B1_COMMERCIAL_CATALOG_BILLING_CYCLE_PER_TRANSACTION).toBe('PER_TRANSACTION');
    expect(B1_COMMERCIAL_CATALOG_PLAN_TYPES).toContain('FEE');
    expect(B1_COMMERCIAL_CATALOG_PLAN_TYPES).toContain('COMMISSION');
  });

  it('exposes the B1 commercial catalog classification and data control classification vocabularies', () => {
    expect(B1_COMMERCIAL_CATALOG_CLASSIFICATION_LEVELS).toContain('PUBLIC');
    expect(B1_COMMERCIAL_CATALOG_CLASSIFICATION_LEVELS).toContain('INTERNAL');
    expect(B1_COMMERCIAL_CATALOG_CLASSIFICATION_LEVELS).toContain('CONFIDENTIAL');
    expect(B1_COMMERCIAL_CATALOG_CLASSIFICATION_LEVELS).toContain('RESTRICTED');
    expect(B1_COMMERCIAL_CATALOG_CLASSIFICATION_LEVELS).toContain('HIGHLY_RESTRICTED');
    expect(B1_COMMERCIAL_CATALOG_DATA_CONTROL_CLASSIFICATIONS).toEqual(
      B1_COMMERCIAL_CATALOG_CLASSIFICATION_LEVELS,
    );
  });

  it('exposes the B1 commercial catalog lookup kind vocabulary', () => {
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('CATALOG');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('PLAN');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('CUSTOMER_TIER');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('MERCHANT_TIER');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('PARTNER_TIER');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('PRODUCT_ENTITLEMENT');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('PACKAGE');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('BUNDLE');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('SUBSCRIPTION_PLAN');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('FEATURE_FLAG');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('DYNAMIC_LIMIT');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('PRICING_CATALOG');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('CAPABILITY_PLANS');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('CAPABILITY_PACKAGES');
    expect(B1_COMMERCIAL_CATALOG_LOOKUP_KINDS).toContain('CAPABILITY_BUNDLES');
  });

  it('exposes the B1 commercial catalog failure code vocabulary', () => {
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(
      B1_COMMERCIAL_CATALOG_FAILURE_QUERY_UNAVAILABLE,
    );
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(
      B1_COMMERCIAL_CATALOG_FAILURE_INCOMPATIBLE,
    );
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(B1_COMMERCIAL_CATALOG_FAILURE_MALFORMED);
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(
      B1_COMMERCIAL_CATALOG_FAILURE_WRONG_VERSION,
    );
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(B1_COMMERCIAL_CATALOG_FAILURE_PROHIBITED);
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(
      B1_COMMERCIAL_CATALOG_FAILURE_UNSUPPORTED_CAPABILITY,
    );
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(
      B1_COMMERCIAL_CATALOG_FAILURE_MISSING_PLAN,
    );
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(
      B1_COMMERCIAL_CATALOG_FAILURE_MISSING_PACKAGE,
    );
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(
      B1_COMMERCIAL_CATALOG_FAILURE_MISSING_BUNDLE,
    );
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(
      B1_COMMERCIAL_CATALOG_FAILURE_MISSING_TIER,
    );
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(
      B1_COMMERCIAL_CATALOG_FAILURE_MISSING_ENTITLEMENT,
    );
    expect(B1_COMMERCIAL_CATALOG_FAILURE_CODES).toContain(
      B1_COMMERCIAL_CATALOG_FAILURE_INVALID_COMMAND,
    );
  });

  it('exposes the B1 commercial catalog prohibited adjacent scopes, prohibited dependencies, and declared dependencies', () => {
    expect(B1_COMMERCIAL_CATALOG_PROHIBITED_ADJACENT_SCOPES.length).toBeGreaterThan(0);
    expect(B1_COMMERCIAL_CATALOG_PROHIBITED_DEPENDENCIES.length).toBeGreaterThan(0);
    expect(B1_COMMERCIAL_CATALOG_DECLARED_DEPENDENCIES).toContain('A1-CANONICAL-IDENTITY');
    expect(B1_COMMERCIAL_CATALOG_DECLARED_DEPENDENCIES).toContain('A2-AUTHORIZATION-CONTEXT');
    expect(B1_COMMERCIAL_CATALOG_DECLARED_DEPENDENCIES).toContain(
      'A3-CUSTOMER-FINANCIAL-ACCOUNT-BINDING',
    );
    expect(B1_COMMERCIAL_CATALOG_DECLARED_DEPENDENCIES).toContain('A4-PRODUCT-POLICY-DECISION');
    expect(B1_COMMERCIAL_CATALOG_DECLARED_DEPENDENCIES).toContain('A5-LEDGER');
    expect(B1_COMMERCIAL_CATALOG_DECLARED_DEPENDENCIES).toContain('A6-PARTNER-ADAPTER');
    expect(B1_COMMERCIAL_CATALOG_DECLARED_DEPENDENCIES).toContain('A7-PRODUCT-CATALOG');
  });

  it('exposes the B1 commercial catalog compatibility, consumer contract, version negotiation, and replay rule identifiers', () => {
    expect(B1_COMMERCIAL_CATALOG_COMPATIBILITY_RULE_IDS.length).toBeGreaterThan(0);
    expect(B1_COMMERCIAL_CATALOG_CONSUMER_CONTRACT_IDS.length).toBeGreaterThan(0);
    expect(B1_COMMERCIAL_CATALOG_VERSION_NEGOTIATION_RULE_IDS.length).toBeGreaterThan(0);
    expect(B1_COMMERCIAL_CATALOG_REPLAY_RULE_IDS.length).toBeGreaterThan(0);
  });

  it('exposes the B1 commercial catalog internal idempotency scope and retention', () => {
    expect(B1_COMMERCIAL_CATALOG_INTERNAL_IDEMPOTENCY_SCOPE).toBe(
      'b1.commercial-catalog.idempotency.v1',
    );
    expect(B1_COMMERCIAL_CATALOG_IDEMPOTENCY_RETENTION_SECONDS).toBe(86_400);
  });

  it('exposes the B1 commercial catalog audit, outbox, metric, and reference prefix', () => {
    expect(B1_COMMERCIAL_CATALOG_AUDIT_ACTOR).toBe('b1-commercial-catalog');
    expect(B1_COMMERCIAL_CATALOG_AUDIT_ENTITY_TYPE).toBe('B1_COMMERCIAL_CATALOG');
    expect(B1_COMMERCIAL_CATALOG_OUTBOX_EVENT_TYPE).toBe('B1CommercialCatalogRegistered');
    expect(B1_COMMERCIAL_CATALOG_METRIC_LOOKUP).toBe('b1.commercial-catalog.lookup');
    expect(B1_COMMERCIAL_CATALOG_METRIC_REPLAYED).toBe('b1.commercial-catalog.replayed');
    expect(B1_COMMERCIAL_CATALOG_METRIC_INCOMPATIBLE).toBe('b1.commercial-catalog.incompatible');
    expect(B1_COMMERCIAL_CATALOG_REFERENCE_PREFIX).toBe('b1-commercial-catalog');
  });
});
