import {
  B1_FEE_ENGINE_AUDIT_ACTOR,
  B1_FEE_ENGINE_AUDIT_ENTITY_TYPE,
  B1_FEE_ENGINE_CLASSIFICATION_LEVELS,
  B1_FEE_ENGINE_COMPATIBILITY_RULE_IDS,
  B1_FEE_ENGINE_CONSUMER_CONTRACT_IDS,
  B1_FEE_ENGINE_CONTRACT_NAME,
  B1_FEE_ENGINE_CONTRACT_VERSION,
  B1_FEE_ENGINE_DATA_CONTROL_CLASSIFICATIONS,
  B1_FEE_ENGINE_DECISION_KIND_COMMISSION,
  B1_FEE_ENGINE_DECISION_KIND_FEE,
  B1_FEE_ENGINE_DECISION_KIND_REVENUE_SHARING,
  B1_FEE_ENGINE_DECISION_KINDS,
  B1_FEE_ENGINE_DECISION_OUTCOME_ADMITTED,
  B1_FEE_ENGINE_DECISION_OUTCOMES,
  B1_FEE_ENGINE_DECLARED_DEPENDENCIES,
  B1_FEE_ENGINE_FAILURE_CODES,
  B1_FEE_ENGINE_FAILURE_INCOMPATIBLE,
  B1_FEE_ENGINE_FAILURE_INVALID_COMMAND,
  B1_FEE_ENGINE_IDEMPOTENCY_RETENTION_SECONDS,
  B1_FEE_ENGINE_INTERNAL_IDEMPOTENCY_SCOPE,
  B1_FEE_ENGINE_LOOKUP_KINDS,
  B1_FEE_ENGINE_METRICS,
  B1_FEE_ENGINE_OUTBOX_EVENT_TYPE,
  B1_FEE_ENGINE_PROHIBITED_ADJACENT_SCOPES,
  B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES,
  B1_FEE_ENGINE_REFERENCE_PREFIX,
  B1_FEE_ENGINE_REPLAY_RULE_IDS,
  B1_FEE_ENGINE_RETENTION_DAYS,
  B1_FEE_ENGINE_ROUNDING_POLICIES,
  B1_FEE_ENGINE_RULE_KINDS,
  B1_FEE_ENGINE_RULE_OUTCOMES,
  B1_FEE_ENGINE_SCOPE_ACCOUNTING_UNIT,
  B1_FEE_ENGINE_SCOPE_CURRENCY,
  B1_FEE_ENGINE_SCOPE_DIRECTION,
  B1_FEE_ENGINE_SCOPE_KEY,
  B1_FEE_ENGINE_SCOPE_PARTNER_DEPENDENCY,
  B1_FEE_ENGINE_SCOPE_PRODUCT_DEPENDENCY,
  B1_FEE_ENGINE_SCOPE_VERSION,
  B1_FEE_ENGINE_VERSION_NEGOTIATION_RULE_IDS,
} from '../src/policy/b1-fee-engine.constants';

describe('B1 fee engine types (B1T04)', () => {
  it('exposes the B1 fee engine contract name and version', () => {
    expect(B1_FEE_ENGINE_CONTRACT_NAME).toBe('B1-FEE-ENGINE');
    expect(B1_FEE_ENGINE_CONTRACT_VERSION).toBe(1);
  });

  it('exposes the B1 fee engine first commercial scope identity', () => {
    expect(B1_FEE_ENGINE_SCOPE_KEY).toBe('commercial.virtual-account.inbound-funding');
    expect(B1_FEE_ENGINE_SCOPE_VERSION).toBe(1);
    expect(B1_FEE_ENGINE_SCOPE_DIRECTION).toBe('inbound');
    expect(B1_FEE_ENGINE_SCOPE_CURRENCY).toBe('NGN');
    expect(B1_FEE_ENGINE_SCOPE_ACCOUNTING_UNIT).toBe('CUSTOMER_FUNDS');
    expect(B1_FEE_ENGINE_SCOPE_PARTNER_DEPENDENCY).toBe('NIBSS_NIP');
    expect(B1_FEE_ENGINE_SCOPE_PRODUCT_DEPENDENCY).toBe('VIRTUAL_ACCOUNT');
  });

  it('exposes the B1 fee engine decision kind vocabulary', () => {
    expect(B1_FEE_ENGINE_DECISION_KIND_FEE).toBe('FEE');
    expect(B1_FEE_ENGINE_DECISION_KIND_COMMISSION).toBe('COMMISSION');
    expect(B1_FEE_ENGINE_DECISION_KIND_REVENUE_SHARING).toBe('REVENUE_SHARING');
    expect(B1_FEE_ENGINE_DECISION_KINDS).toHaveLength(3);
  });

  it('exposes the B1 fee engine decision outcome vocabulary', () => {
    expect(B1_FEE_ENGINE_DECISION_OUTCOME_ADMITTED).toBe('COMMERCIAL_DECISION_ADMITTED');
    expect(B1_FEE_ENGINE_DECISION_OUTCOMES).toContain('COMMERCIAL_DECISION_ADMITTED');
    expect(B1_FEE_ENGINE_DECISION_OUTCOMES).toContain('COMMERCIAL_DECISION_SUPPRESSED');
    expect(B1_FEE_ENGINE_DECISION_OUTCOMES).toContain('COMMERCIAL_DECISION_DISABLED');
    expect(B1_FEE_ENGINE_DECISION_OUTCOMES).toContain('COMMERCIAL_DECISION_FAILED');
  });

  it('exposes the B1 fee engine rule outcome vocabulary', () => {
    expect(B1_FEE_ENGINE_RULE_OUTCOMES).toContain('PASS');
    expect(B1_FEE_ENGINE_RULE_OUTCOMES).toContain('FAIL');
    expect(B1_FEE_ENGINE_RULE_OUTCOMES).toContain('SKIP');
    expect(B1_FEE_ENGINE_RULE_OUTCOMES).toContain('NOT_APPLICABLE');
  });

  it('exposes the B1 fee engine rule kind vocabulary', () => {
    expect(B1_FEE_ENGINE_RULE_KINDS.length).toBeGreaterThan(20);
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A4_POLICY_LIMIT');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A4_POLICY_OBLIGATION');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A4_POLICY_CURRENTNESS');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A4_POLICY_REEVALUATION');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A3_BINDING_RECHECK');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A5_LEDGER_ACCOUNT_STATE');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A5_LEDGER_POSTING_BOUNDARY');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A5_FINANCIAL_INVARIANTS');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A6_PARTNER_STATE');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A6_PARTNER_CAPABILITY_VERSION');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A6T08_SETTLEMENT_SUSPENSE_COMPENSATING');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A6T09_EXTERNAL_RECONCILIATION');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A7_PRODUCT_CATALOG');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A7_PRODUCT_BOUNDARY');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A7T04_PRODUCT_CUSTOMER_BINDING');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A7T05_PRODUCT_COMMAND_OPERATION');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A7T06_PRODUCT_NOTIFICATION');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A7T07_PRODUCT_LIFECYCLE');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A7T08_PRODUCT_FINANCIAL_EFFECT');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A7T09_PRODUCT_RECONCILIATION');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('A7T10_PRODUCT_DATA_MINIMIZATION');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('B1_COMMERCIAL_CATALOG_LOOKUP');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('B1_COMMERCIAL_CATALOG_COMPATIBILITY');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('B1_COMMERCIAL_CATALOG_PLAN');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('B1_COMMERCIAL_CATALOG_TIER');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('B1_COMMERCIAL_CATALOG_ENTITLEMENT');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('B1_COMMERCIAL_CATALOG_PACKAGE');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('B1_COMMERCIAL_CATALOG_BUNDLE');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('B1_COMMERCIAL_CATALOG_SUBSCRIPTION');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('B1_COMMERCIAL_CATALOG_FEATURE_FLAG');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT');
    expect(B1_FEE_ENGINE_RULE_KINDS).toContain('B1_COMMERCIAL_CATALOG_PRICING');
  });

  it('exposes the B1 fee engine failure code vocabulary', () => {
    expect(B1_FEE_ENGINE_FAILURE_INVALID_COMMAND).toBe('B1_FEE_ENGINE_INVALID_COMMAND');
    expect(B1_FEE_ENGINE_FAILURE_INCOMPATIBLE).toBe('B1_FEE_ENGINE_INCOMPATIBLE');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_INVALID_COMMAND');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_INCOMPATIBLE');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_QUERY_UNAVAILABLE');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_PROHIBITED');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_A4_POLICY_DENIED');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_A3_BINDING_INVALID');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_A5_LEDGER_INVARIANT_BROKEN');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_A6_PARTNER_INCOMPATIBLE');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_A7_PRODUCT_INCOMPATIBLE');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_B1_CATALOG_INCOMPATIBLE');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_B1_CATALOG_MISSING');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_FEATURE_FLAG_DISABLED');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_DYNAMIC_LIMIT_EXCEEDED');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_REPLAY_CONFLICT');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_REPLAY_EXPIRED');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_IN_PROGRESS');
    expect(B1_FEE_ENGINE_FAILURE_CODES).toContain('B1_FEE_ENGINE_BREAK_GLASS_DENIED');
  });

  it('exposes the B1 fee engine internal idempotency scope and retention', () => {
    expect(B1_FEE_ENGINE_INTERNAL_IDEMPOTENCY_SCOPE).toBe('b1.commercial-decision.idempotency.v1');
    expect(B1_FEE_ENGINE_IDEMPOTENCY_RETENTION_SECONDS).toBe(86_400);
  });

  it('exposes the B1 fee engine audit, outbox, metric, and reference prefix', () => {
    expect(B1_FEE_ENGINE_AUDIT_ACTOR).toBe('b1-fee-engine');
    expect(B1_FEE_ENGINE_AUDIT_ENTITY_TYPE).toBe('B1_COMMERCIAL_DECISION');
    expect(B1_FEE_ENGINE_OUTBOX_EVENT_TYPE).toBe('B1CommercialDecisionDecided');
    expect(B1_FEE_ENGINE_METRICS).toContain('b1.commercial-decision.evaluate');
    expect(B1_FEE_ENGINE_METRICS).toContain('b1.commercial-decision.replayed');
    expect(B1_FEE_ENGINE_METRICS).toContain('b1.commercial-decision.conflict');
    expect(B1_FEE_ENGINE_REFERENCE_PREFIX).toBe('b1-commercial-decision');
  });

  it('exposes the B1 fee engine retention, rounding, classification, data control, and lookup kind vocabularies', () => {
    expect(B1_FEE_ENGINE_RETENTION_DAYS).toBe(365);
    expect(B1_FEE_ENGINE_ROUNDING_POLICIES).toContain('BANKERS_ROUND');
    expect(B1_FEE_ENGINE_ROUNDING_POLICIES).toContain('TRUNCATE');
    expect(B1_FEE_ENGINE_ROUNDING_POLICIES).toContain('CEIL');
    expect(B1_FEE_ENGINE_CLASSIFICATION_LEVELS).toContain('PUBLIC');
    expect(B1_FEE_ENGINE_CLASSIFICATION_LEVELS).toContain('INTERNAL');
    expect(B1_FEE_ENGINE_CLASSIFICATION_LEVELS).toContain('CONFIDENTIAL');
    expect(B1_FEE_ENGINE_CLASSIFICATION_LEVELS).toContain('RESTRICTED');
    expect(B1_FEE_ENGINE_CLASSIFICATION_LEVELS).toContain('HIGHLY_RESTRICTED');
    expect(B1_FEE_ENGINE_DATA_CONTROL_CLASSIFICATIONS).toEqual(B1_FEE_ENGINE_CLASSIFICATION_LEVELS);
    expect(B1_FEE_ENGINE_LOOKUP_KINDS).toContain('CATALOG');
    expect(B1_FEE_ENGINE_LOOKUP_KINDS).toContain('PLAN');
    expect(B1_FEE_ENGINE_LOOKUP_KINDS).toContain('CUSTOMER_TIER');
    expect(B1_FEE_ENGINE_LOOKUP_KINDS).toContain('PARTNER_TIER');
  });

  it('exposes the B1 fee engine prohibited adjacent scopes, prohibited dependencies, and declared dependencies', () => {
    expect(B1_FEE_ENGINE_PROHIBITED_ADJACENT_SCOPES.length).toBeGreaterThan(0);
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_BILLING_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_INVOICE_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_STATEMENT_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_CAMPAIGN_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_PROMOTION_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_COUPON_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_REFERRAL_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_CASHBACK_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_LOYALTY_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_REVENUE_RECOGNITION_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_TAX_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_COST_ACCOUNTING_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_PROFITABILITY_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_ANALYTICS_ENGINE');
    expect(B1_FEE_ENGINE_PROHIBITED_DEPENDENCIES).toContain('B1_COMMERCIAL_RECONCILIATION_ENGINE');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('A1-CANONICAL-IDENTITY');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('A2-AUTHORIZATION-CONTEXT');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('A3-CUSTOMER-FINANCIAL-ACCOUNT-BINDING');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('A4-PRODUCT-POLICY-DECISION');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('A5-LEDGER');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('A6-PARTNER-ADAPTER');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('A6T05-EXTERNAL-OPERATION');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('A6T08-SETTLEMENT-SUSPENSE-COMPENSATING');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('A6T09-EXTERNAL-RECONCILIATION');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('A6T10-DATA-CLASSIFICATION');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('A7-PRODUCT-CATALOG');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-COMMERCIAL-CATALOG');
    expect(B1_FEE_ENGINE_DECLARED_DEPENDENCIES).toContain('CUSTOMER-PREFERENCE');
  });

  it('exposes the B1 fee engine compatibility, consumer contract, version negotiation, and replay rule identifiers', () => {
    expect(B1_FEE_ENGINE_COMPATIBILITY_RULE_IDS.length).toBeGreaterThan(0);
    expect(B1_FEE_ENGINE_CONSUMER_CONTRACT_IDS.length).toBeGreaterThan(0);
    expect(B1_FEE_ENGINE_VERSION_NEGOTIATION_RULE_IDS.length).toBeGreaterThan(0);
    expect(B1_FEE_ENGINE_REPLAY_RULE_IDS.length).toBeGreaterThan(0);
  });
});
