import {
  B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASES,
  B1_REVENUE_RECOGNITION_ENGINE_AUDIT_ACTOR,
  B1_REVENUE_RECOGNITION_ENGINE_AUDIT_ENTITY_TYPE,
  B1_REVENUE_RECOGNITION_ENGINE_CASHBACK_IDEMPOTENCY_SCOPE_NOTE,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_IDEMPOTENCY_SCOPE,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATES,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHODS,
  B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORIES,
  B1_REVENUE_RECOGNITION_ENGINE_CLASSIFICATION_LEVELS,
  B1_REVENUE_RECOGNITION_ENGINE_COMPATIBILITY_RULE_IDS,
  B1_REVENUE_RECOGNITION_ENGINE_CONSUMER_CONTRACT_IDS,
  B1_REVENUE_RECOGNITION_ENGINE_CONTRACT_DOCUMENT,
  B1_REVENUE_RECOGNITION_ENGINE_CONTRACT_NAME,
  B1_REVENUE_RECOGNITION_ENGINE_CONTRACT_VERSION,
  B1_REVENUE_RECOGNITION_ENGINE_DATA_CONTROL_CLASSIFICATIONS,
  B1_REVENUE_RECOGNITION_ENGINE_DECISION_KINDS,
  B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOMES,
  B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KINDS,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_CODES,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_INVALID_COMMAND,
  B1_REVENUE_RECOGNITION_ENGINE_IDEMPOTENCY_RETENTION_SECONDS,
  B1_REVENUE_RECOGNITION_ENGINE_LOYALTY_IDEMPOTENCY_SCOPE_NOTE,
  B1_REVENUE_RECOGNITION_ENGINE_OUTBOX_EVENT_CLASSIFICATION,
  B1_REVENUE_RECOGNITION_ENGINE_OUTBOX_EVENT_RETENTION_CLASS,
  B1_REVENUE_RECOGNITION_ENGINE_OUTBOX_EVENT_TYPE,
  B1_REVENUE_RECOGNITION_ENGINE_PERIOD_KEY,
  B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED_ADJACENT_SCOPES,
  B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED_DEPENDENCIES,
  B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHODS,
  B1_REVENUE_RECOGNITION_ENGINE_REFERENCE_PREFIX,
  B1_REVENUE_RECOGNITION_ENGINE_REFERRAL_IDEMPOTENCY_SCOPE_NOTE,
  B1_REVENUE_RECOGNITION_ENGINE_REPLAY_RULE_IDS,
  B1_REVENUE_RECOGNITION_ENGINE_RETENTION_DAYS,
  B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_IDEMPOTENCY_SCOPE,
  B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATES,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KINDS,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOMES,
  B1_REVENUE_RECOGNITION_ENGINE_SCOPE_ACCOUNTING_UNIT,
  B1_REVENUE_RECOGNITION_ENGINE_SCOPE_CURRENCY,
  B1_REVENUE_RECOGNITION_ENGINE_SCOPE_DIRECTION,
  B1_REVENUE_RECOGNITION_ENGINE_SCOPE_KEY,
  B1_REVENUE_RECOGNITION_ENGINE_SCOPE_PARTNER_DEPENDENCY,
  B1_REVENUE_RECOGNITION_ENGINE_SCOPE_PRODUCT_DEPENDENCY,
  B1_REVENUE_RECOGNITION_ENGINE_SCOPE_PRODUCT_DEPENDENCY_VERSION,
  B1_REVENUE_RECOGNITION_ENGINE_SCOPE_VERSION,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORIES,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTIONS,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_IDEMPOTENCY_SCOPE,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATES,
  B1_REVENUE_RECOGNITION_ENGINE_VERSION_NEGOTIATION_RULE_IDS,
} from '../src/policy/b1-revenue-recognition-engine.constants';

describe('B1 revenue-recognition engine types (B1T08)', () => {
  it('exposes the B1 revenue-recognition engine contract name and version', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_CONTRACT_NAME).toBe('B1-REVENUE-RECOGNITION-ENGINE');
    expect(B1_REVENUE_RECOGNITION_ENGINE_CONTRACT_VERSION).toBe(1);
  });

  it('exposes the B1 revenue-recognition engine contract document path', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_CONTRACT_DOCUMENT).toBe(
      'docs/B1-REVENUE-RECOGNITION-CONTRACT.md',
    );
  });

  it('exposes the B1 revenue-recognition engine first commercial scope identity', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_SCOPE_KEY).toBe(
      'commercial.virtual-account.inbound-funding',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_SCOPE_VERSION).toBe(1);
    expect(B1_REVENUE_RECOGNITION_ENGINE_SCOPE_DIRECTION).toBe('inbound');
    expect(B1_REVENUE_RECOGNITION_ENGINE_SCOPE_CURRENCY).toBe('NGN');
    expect(B1_REVENUE_RECOGNITION_ENGINE_SCOPE_ACCOUNTING_UNIT).toBe('CUSTOMER_FUNDS');
    expect(B1_REVENUE_RECOGNITION_ENGINE_SCOPE_PARTNER_DEPENDENCY).toBe('NIBSS_NIP');
    expect(B1_REVENUE_RECOGNITION_ENGINE_SCOPE_PRODUCT_DEPENDENCY).toBe('VIRTUAL_ACCOUNT');
    expect(B1_REVENUE_RECOGNITION_ENGINE_SCOPE_PRODUCT_DEPENDENCY_VERSION).toBe(1);
  });

  it('exposes the B1 revenue-recognition engine period identity', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_PERIOD_KEY).toBe(
      'commercial.virtual-account.inbound-funding.revenue-recognition-period.per-flow.v1',
    );
  });

  it('exposes the B1 revenue-recognition engine accounting basis vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASES).toContain('CASH_BASIS');
    expect(B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASES).toContain('ACCRUAL_BASIS');
    expect(B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASES).toContain('MODIFIED_ACCRUAL_BASIS');
    expect(B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASES).toContain('REVENUE_RECOGNITION_BASIS');
  });

  it('exposes the B1 revenue-recognition engine decision kind vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECISION_KINDS).toContain('REVENUE_RECOGNITION');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECISION_KINDS).toContain('TAX_VAT');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECISION_KINDS).toContain('COST_ACCOUNTING');
  });

  it('exposes the B1 revenue-recognition engine decision outcome vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOMES).toContain('ELIGIBLE');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOMES).toContain('APPLIED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOMES).toContain('REJECTED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOMES).toContain('REPLAYED');
  });

  it('exposes the B1 revenue-recognition engine revenue-recognition state vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATES).toContain('DRAFT');
    expect(B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATES).toContain('PENDING');
    expect(B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATES).toContain('RECOGNIZED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATES).toContain('DEFERRED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATES).toContain('CANCELLED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATES).toContain('RETIRED');
  });

  it('exposes the B1 revenue-recognition engine tax / VAT state vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATES).toContain('DRAFT');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATES).toContain('PENDING');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATES).toContain('ASSESSED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATES).toContain('EXEMPTED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATES).toContain('DECLARED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATES).toContain('CANCELLED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATES).toContain('RETIRED');
  });

  it('exposes the B1 revenue-recognition engine cost-accounting state vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATES).toContain('DRAFT');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATES).toContain('PENDING');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATES).toContain('ALLOCATED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATES).toContain('RECOGNIZED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATES).toContain('AMORTIZED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATES).toContain('CANCELLED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATES).toContain('RETIRED');
  });

  it('exposes the B1 revenue-recognition engine document kind vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KINDS.length).toBe(22);
  });

  it('exposes the B1 revenue-recognition engine recognition method vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHODS).toContain('POINT_IN_TIME');
    expect(B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHODS).toContain('OVER_TIME');
    expect(B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHODS).toContain('MILESTONE_BASED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHODS).toContain('PERCENTAGE_OF_COMPLETION');
    expect(B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHODS).toContain('INSTALLMENT');
    expect(B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHODS).toContain('DEFERRED');
  });

  it('exposes the B1 revenue-recognition engine tax category vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORIES).toContain('VAT');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORIES).toContain('SALES_TAX');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORIES).toContain('WITHHOLDING_TAX');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORIES).toContain('SERVICE_TAX');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORIES).toContain('EXCISE_TAX');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORIES).toContain('EXEMPT');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORIES).toContain('ZERO_RATED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORIES).toContain('OUT_OF_SCOPE');
  });

  it('exposes the B1 revenue-recognition engine tax jurisdiction vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTIONS).toContain('NIGERIA_FEDERAL');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTIONS).toContain('NIGERIA_STATE');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTIONS).toContain('NIGERIA_LGA');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTIONS).toContain('WEST_AFRICA_REGION');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTIONS).toContain('AFRICA_REGION');
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTIONS).toContain('GLOBAL');
  });

  it('exposes the B1 revenue-recognition engine cost category vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORIES).toContain('DIRECT_COST');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORIES).toContain('INDIRECT_COST');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORIES).toContain('ACQUISITION_COST');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORIES).toContain('OPERATIONAL_COST');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORIES).toContain('ALLOCATED_COST');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORIES).toContain('OVERHEAD_COST');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORIES).toContain('SUPPORT_COST');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORIES).toContain('CAPITALIZED_COST');
  });

  it('exposes the B1 revenue-recognition engine cost allocation method vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHODS).toContain('DIRECT_ALLOCATION');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHODS).toContain('STEP_ALLOCATION');
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHODS).toContain(
      'RECIPROCAL_ALLOCATION',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHODS).toContain(
      'PROPORTIONAL_ALLOCATION',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHODS).toContain(
      'ACTIVITY_BASED_COSTING',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHODS).toContain('STANDARD_COSTING');
  });

  it('exposes the B1 revenue-recognition engine failure code vocabulary', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_FAILURE_INVALID_COMMAND).toBe(
      'B1_REVENUE_RECOGNITION_ENGINE_INVALID_COMMAND',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_FAILURE_INCOMPATIBLE).toBe(
      'B1_REVENUE_RECOGNITION_ENGINE_INCOMPATIBLE',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_FAILURE_CODES.length).toBe(26);
  });

  it('exposes the B1 revenue-recognition engine internal idempotency scopes and retention', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_IDEMPOTENCY_SCOPE).toBe(
      'b1.revenue-recognition-engine.revenue-recognition.idempotency.v1',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_IDEMPOTENCY_SCOPE).toBe(
      'b1.revenue-recognition-engine.tax-vat.idempotency.v1',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_IDEMPOTENCY_SCOPE).toBe(
      'b1.revenue-recognition-engine.cost-accounting.idempotency.v1',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_IDEMPOTENCY_RETENTION_SECONDS).toBe(86_400);
  });

  it('exposes the B1 revenue-recognition engine audit, outbox, metric, and reference prefix', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_AUDIT_ACTOR).toBe('b1-revenue-recognition-engine');
    expect(B1_REVENUE_RECOGNITION_ENGINE_AUDIT_ENTITY_TYPE).toBe('B1_REVENUE_RECOGNITION_DECISION');
    expect(B1_REVENUE_RECOGNITION_ENGINE_OUTBOX_EVENT_TYPE).toBe(
      'B1RevenueRecognitionDecisionDecided',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_OUTBOX_EVENT_CLASSIFICATION).toBe('INTERNAL_OPERATIONS');
    expect(B1_REVENUE_RECOGNITION_ENGINE_OUTBOX_EVENT_RETENTION_CLASS).toBe('OPERATIONS_DEFAULT');
    expect(B1_REVENUE_RECOGNITION_ENGINE_REFERENCE_PREFIX).toBe('b1-revenue-recognition-decision');
  });

  it('exposes the B1 revenue-recognition engine retention, classification, and data control classification vocabularies', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_RETENTION_DAYS).toBe(365);
    expect(B1_REVENUE_RECOGNITION_ENGINE_CLASSIFICATION_LEVELS).toContain('PUBLIC');
    expect(B1_REVENUE_RECOGNITION_ENGINE_CLASSIFICATION_LEVELS).toContain('INTERNAL');
    expect(B1_REVENUE_RECOGNITION_ENGINE_CLASSIFICATION_LEVELS).toContain('CONFIDENTIAL');
    expect(B1_REVENUE_RECOGNITION_ENGINE_CLASSIFICATION_LEVELS).toContain('RESTRICTED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_CLASSIFICATION_LEVELS).toContain('HIGHLY_RESTRICTED');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DATA_CONTROL_CLASSIFICATIONS).toEqual(
      B1_REVENUE_RECOGNITION_ENGINE_CLASSIFICATION_LEVELS,
    );
  });

  it('exposes the B1 revenue-recognition engine rule outcome and rule kind vocabularies', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOMES).toContain('PASS');
    expect(B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOMES).toContain('FAIL');
    expect(B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOMES).toContain('SKIP');
    expect(B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOMES).toContain('NOT_APPLICABLE');
    expect(B1_REVENUE_RECOGNITION_ENGINE_RULE_KINDS.length).toBeGreaterThan(50);
  });

  it('exposes the B1 revenue-recognition engine prohibited adjacent scopes, prohibited dependencies, and declared dependencies', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED_ADJACENT_SCOPES.length).toBeGreaterThan(0);
    expect(B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED_DEPENDENCIES).toContain(
      'CASHBACK_REDEMPTION_AUTHORITY',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED_DEPENDENCIES).toContain(
      'LOYALTY_BALANCE_AUTHORITY',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED_DEPENDENCIES).toContain(
      'REFERRAL_REWARD_AUTHORITY',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED_DEPENDENCIES).toContain(
      'REVENUE_RECOGNITION_POSTING_AUTHORITY',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED_DEPENDENCIES).toContain(
      'TAX_VAT_POSTING_AUTHORITY',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED_DEPENDENCIES).toContain(
      'COST_ACCOUNTING_POSTING_AUTHORITY',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain('A1-CANONICAL-IDENTITY');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain(
      'A2-AUTHORIZATION-CONTEXT',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain(
      'A3-CUSTOMER-FINANCIAL-ACCOUNT-BINDING',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain(
      'A4-PRODUCT-POLICY-DECISION',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain('A5-LEDGER');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain('A6-PARTNER-ADAPTER');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain('A7-PRODUCT-CATALOG');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-COMMERCIAL-CATALOG');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-COMMERCIAL-DECISION');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-BILLING-ENGINE');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-CAMPAIGN-ENGINE');
    expect(B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-REFERRAL-ENGINE');
  });

  it('exposes the B1 revenue-recognition engine compatibility, consumer contract, version negotiation, and replay rule identifiers', () => {
    expect(B1_REVENUE_RECOGNITION_ENGINE_COMPATIBILITY_RULE_IDS.length).toBeGreaterThan(0);
    expect(B1_REVENUE_RECOGNITION_ENGINE_CONSUMER_CONTRACT_IDS.length).toBeGreaterThan(0);
    expect(B1_REVENUE_RECOGNITION_ENGINE_VERSION_NEGOTIATION_RULE_IDS.length).toBeGreaterThan(0);
    expect(B1_REVENUE_RECOGNITION_ENGINE_REPLAY_RULE_IDS.length).toBeGreaterThan(0);
  });

  it('asserts the B1 revenue-recognition engine is read-only against cashback / loyalty / referral idempotency scopes (B1T07-owned)', () => {
    // B1T08 NEVER introduces its own cashback / loyalty / referral idempotency
    // scopes. Those are owned by the B1T07 referral engine. The B1 revenue-
    // recognition engine is read-only against those decision references.
    expect(B1_REVENUE_RECOGNITION_ENGINE_CASHBACK_IDEMPOTENCY_SCOPE_NOTE).toBe(
      'B1T07_OWNED_CASHBACK_NOT_B1T08',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_LOYALTY_IDEMPOTENCY_SCOPE_NOTE).toBe(
      'B1T07_OWNED_LOYALTY_NOT_B1T08',
    );
    expect(B1_REVENUE_RECOGNITION_ENGINE_REFERRAL_IDEMPOTENCY_SCOPE_NOTE).toBe(
      'B1T07_OWNED_REFERRAL_NOT_B1T08',
    );
  });
});
