import {
  B1_REFERRAL_ENGINE_AUDIT_ACTOR,
  B1_REFERRAL_ENGINE_AUDIT_ENTITY_TYPE,
  B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASES,
  B1_REFERRAL_ENGINE_CASHBACK_IDEMPOTENCY_SCOPE,
  B1_REFERRAL_ENGINE_CASHBACK_STATES,
  B1_REFERRAL_ENGINE_CLASSIFICATION_LEVELS,
  B1_REFERRAL_ENGINE_COMPATIBILITY_RULE_IDS,
  B1_REFERRAL_ENGINE_CONSUMER_CONTRACT_IDS,
  B1_REFERRAL_ENGINE_CONTRACT_DOCUMENT,
  B1_REFERRAL_ENGINE_CONTRACT_NAME,
  B1_REFERRAL_ENGINE_CONTRACT_VERSION,
  B1_REFERRAL_ENGINE_DATA_CONTROL_CLASSIFICATIONS,
  B1_REFERRAL_ENGINE_DECISION_KINDS,
  B1_REFERRAL_ENGINE_DECISION_OUTCOMES,
  B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES,
  B1_REFERRAL_ENGINE_DOCUMENT_KINDS,
  B1_REFERRAL_ENGINE_FAILURE_CODES,
  B1_REFERRAL_ENGINE_FAILURE_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_FAILURE_INVALID_COMMAND,
  B1_REFERRAL_ENGINE_IDEMPOTENCY_RETENTION_SECONDS,
  B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCES,
  B1_REFERRAL_ENGINE_LOYALTY_IDEMPOTENCY_SCOPE,
  B1_REFERRAL_ENGINE_LOYALTY_STATES,
  B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUSES,
  B1_REFERRAL_ENGINE_OUTBOX_EVENT_CLASSIFICATION,
  B1_REFERRAL_ENGINE_OUTBOX_EVENT_RETENTION_CLASS,
  B1_REFERRAL_ENGINE_OUTBOX_EVENT_TYPE,
  B1_REFERRAL_ENGINE_PERIOD_KEY,
  B1_REFERRAL_ENGINE_PROHIBITED_ADJACENT_SCOPES,
  B1_REFERRAL_ENGINE_PROHIBITED_DEPENDENCIES,
  B1_REFERRAL_ENGINE_QUALIFICATION_STATUSES,
  B1_REFERRAL_ENGINE_REFERENCE_PREFIX,
  B1_REFERRAL_ENGINE_REFERRAL_IDEMPOTENCY_SCOPE,
  B1_REFERRAL_ENGINE_REFERRAL_STATES,
  B1_REFERRAL_ENGINE_RELATIONSHIP_TYPES,
  B1_REFERRAL_ENGINE_REPLAY_RULE_IDS,
  B1_REFERRAL_ENGINE_RETENTION_DAYS,
  B1_REFERRAL_ENGINE_RULE_KINDS,
  B1_REFERRAL_ENGINE_RULE_OUTCOMES,
  B1_REFERRAL_ENGINE_SCOPE_ACCOUNTING_UNIT,
  B1_REFERRAL_ENGINE_SCOPE_CURRENCY,
  B1_REFERRAL_ENGINE_SCOPE_DIRECTION,
  B1_REFERRAL_ENGINE_SCOPE_KEY,
  B1_REFERRAL_ENGINE_SCOPE_PARTNER_DEPENDENCY,
  B1_REFERRAL_ENGINE_SCOPE_PRODUCT_DEPENDENCY,
  B1_REFERRAL_ENGINE_SCOPE_PRODUCT_DEPENDENCY_VERSION,
  B1_REFERRAL_ENGINE_SCOPE_VERSION,
  B1_REFERRAL_ENGINE_VERSION_NEGOTIATION_RULE_IDS,
} from '../src/policy/b1-referral-engine.constants';

describe('B1 referral engine types (B1T07)', () => {
  it('exposes the B1 referral engine contract name and version', () => {
    expect(B1_REFERRAL_ENGINE_CONTRACT_NAME).toBe('B1-REFERRAL-ENGINE');
    expect(B1_REFERRAL_ENGINE_CONTRACT_VERSION).toBe(1);
  });

  it('exposes the B1 referral engine contract document path', () => {
    expect(B1_REFERRAL_ENGINE_CONTRACT_DOCUMENT).toBe('docs/B1-REFERRAL-ENGINE-CONTRACT.md');
  });

  it('exposes the B1 referral engine first commercial scope identity', () => {
    expect(B1_REFERRAL_ENGINE_SCOPE_KEY).toBe('commercial.virtual-account.inbound-funding');
    expect(B1_REFERRAL_ENGINE_SCOPE_VERSION).toBe(1);
    expect(B1_REFERRAL_ENGINE_SCOPE_DIRECTION).toBe('inbound');
    expect(B1_REFERRAL_ENGINE_SCOPE_CURRENCY).toBe('NGN');
    expect(B1_REFERRAL_ENGINE_SCOPE_ACCOUNTING_UNIT).toBe('CUSTOMER_FUNDS');
    expect(B1_REFERRAL_ENGINE_SCOPE_PARTNER_DEPENDENCY).toBe('NIBSS_NIP');
    expect(B1_REFERRAL_ENGINE_SCOPE_PRODUCT_DEPENDENCY).toBe('VIRTUAL_ACCOUNT');
    expect(B1_REFERRAL_ENGINE_SCOPE_PRODUCT_DEPENDENCY_VERSION).toBe(1);
  });

  it('exposes the B1 referral engine period identity', () => {
    expect(B1_REFERRAL_ENGINE_PERIOD_KEY).toBe(
      'commercial.virtual-account.inbound-funding.referral-period.per-flow.v1',
    );
  });

  it('exposes the B1 referral engine decision kind vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_DECISION_KINDS).toContain('REFERRAL');
    expect(B1_REFERRAL_ENGINE_DECISION_KINDS).toContain('CASHBACK');
    expect(B1_REFERRAL_ENGINE_DECISION_KINDS).toContain('LOYALTY');
  });

  it('exposes the B1 referral engine decision outcome vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_DECISION_OUTCOMES).toContain('ELIGIBLE');
    expect(B1_REFERRAL_ENGINE_DECISION_OUTCOMES).toContain('APPLIED');
    expect(B1_REFERRAL_ENGINE_DECISION_OUTCOMES).toContain('REJECTED');
    expect(B1_REFERRAL_ENGINE_DECISION_OUTCOMES).toContain('REPLAYED');
  });

  it('exposes the B1 referral engine referral state vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_REFERRAL_STATES).toContain('DRAFT');
    expect(B1_REFERRAL_ENGINE_REFERRAL_STATES).toContain('ACTIVE');
    expect(B1_REFERRAL_ENGINE_REFERRAL_STATES).toContain('PAUSED');
    expect(B1_REFERRAL_ENGINE_REFERRAL_STATES).toContain('EXPIRED');
    expect(B1_REFERRAL_ENGINE_REFERRAL_STATES).toContain('RETIRED');
  });

  it('exposes the B1 referral engine cashback state vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_CASHBACK_STATES).toContain('CREATED');
    expect(B1_REFERRAL_ENGINE_CASHBACK_STATES).toContain('ACTIVE');
    expect(B1_REFERRAL_ENGINE_CASHBACK_STATES).toContain('PAUSED');
    expect(B1_REFERRAL_ENGINE_CASHBACK_STATES).toContain('EXPIRED');
    expect(B1_REFERRAL_ENGINE_CASHBACK_STATES).toContain('CANCELLED');
  });

  it('exposes the B1 referral engine loyalty state vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_LOYALTY_STATES).toContain('DRAFT');
    expect(B1_REFERRAL_ENGINE_LOYALTY_STATES).toContain('ACTIVE');
    expect(B1_REFERRAL_ENGINE_LOYALTY_STATES).toContain('SUSPENDED');
    expect(B1_REFERRAL_ENGINE_LOYALTY_STATES).toContain('RETIRED');
    expect(B1_REFERRAL_ENGINE_LOYALTY_STATES).toContain('ARCHIVED');
  });

  it('exposes the B1 referral engine document kind vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_DOCUMENT_KINDS.length).toBe(15);
  });

  it('exposes the B1 referral engine relationship type vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_RELATIONSHIP_TYPES).toContain('PARENT');
    expect(B1_REFERRAL_ENGINE_RELATIONSHIP_TYPES).toContain('CHILD');
    expect(B1_REFERRAL_ENGINE_RELATIONSHIP_TYPES).toContain('SIBLING');
    expect(B1_REFERRAL_ENGINE_RELATIONSHIP_TYPES).toContain('SPONSOR');
    expect(B1_REFERRAL_ENGINE_RELATIONSHIP_TYPES).toContain('REFEREE');
    expect(B1_REFERRAL_ENGINE_RELATIONSHIP_TYPES).toContain('CIRCLE');
    expect(B1_REFERRAL_ENGINE_RELATIONSHIP_TYPES).toContain('NETWORK');
  });

  it('exposes the B1 referral engine qualification status vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_QUALIFICATION_STATUSES).toContain('NOT_QUALIFIED');
    expect(B1_REFERRAL_ENGINE_QUALIFICATION_STATUSES).toContain('PENDING_VERIFICATION');
    expect(B1_REFERRAL_ENGINE_QUALIFICATION_STATUSES).toContain('QUALIFIED');
    expect(B1_REFERRAL_ENGINE_QUALIFICATION_STATUSES).toContain('OVER_QUALIFIED');
    expect(B1_REFERRAL_ENGINE_QUALIFICATION_STATUSES).toContain('EXPIRED_QUALIFICATION');
  });

  it('exposes the B1 referral engine loyalty tier status vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUSES).toContain('TIER_PENDING');
    expect(B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUSES).toContain('TIER_BRONZE');
    expect(B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUSES).toContain('TIER_SILVER');
    expect(B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUSES).toContain('TIER_GOLD');
    expect(B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUSES).toContain('TIER_PLATINUM');
    expect(B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUSES).toContain('TIER_DIAMOND');
  });

  it('exposes the B1 referral engine loyalty earning source vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCES).toContain('PURCHASE');
    expect(B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCES).toContain('BILLING');
    expect(B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCES).toContain('CAMPAIGN');
    expect(B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCES).toContain('PROMOTION');
    expect(B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCES).toContain('COUPON');
    expect(B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCES).toContain('REFERRAL');
    expect(B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCES).toContain('CASHBACK');
    expect(B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCES).toContain('MANUAL_ADJUSTMENT');
  });

  it('exposes the B1 referral engine cashback calculation basis vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASES).toContain('FIXED_AMOUNT');
    expect(B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASES).toContain('PERCENTAGE_OF_BILLING');
    expect(B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASES).toContain('PERCENTAGE_OF_FEE');
    expect(B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASES).toContain('TIER_MULTIPLIER');
    expect(B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASES).toContain('CAMPAIGN_OVERRIDE');
  });

  it('exposes the B1 referral engine failure code vocabulary', () => {
    expect(B1_REFERRAL_ENGINE_FAILURE_INVALID_COMMAND).toBe('B1_REFERRAL_ENGINE_INVALID_COMMAND');
    expect(B1_REFERRAL_ENGINE_FAILURE_INCOMPATIBLE).toBe('B1_REFERRAL_ENGINE_INCOMPATIBLE');
    expect(B1_REFERRAL_ENGINE_FAILURE_CODES.length).toBe(32);
  });

  it('exposes the B1 referral engine internal idempotency scopes and retention', () => {
    expect(B1_REFERRAL_ENGINE_REFERRAL_IDEMPOTENCY_SCOPE).toBe(
      'b1.referral-engine.referral.idempotency.v1',
    );
    expect(B1_REFERRAL_ENGINE_CASHBACK_IDEMPOTENCY_SCOPE).toBe(
      'b1.referral-engine.cashback.idempotency.v1',
    );
    expect(B1_REFERRAL_ENGINE_LOYALTY_IDEMPOTENCY_SCOPE).toBe(
      'b1.referral-engine.loyalty.idempotency.v1',
    );
    expect(B1_REFERRAL_ENGINE_IDEMPOTENCY_RETENTION_SECONDS).toBe(86_400);
  });

  it('exposes the B1 referral engine audit, outbox, metric, and reference prefix', () => {
    expect(B1_REFERRAL_ENGINE_AUDIT_ACTOR).toBe('b1-referral-engine');
    expect(B1_REFERRAL_ENGINE_AUDIT_ENTITY_TYPE).toBe('B1_REFERRAL_DECISION');
    expect(B1_REFERRAL_ENGINE_OUTBOX_EVENT_TYPE).toBe('B1ReferralDecisionDecided');
    expect(B1_REFERRAL_ENGINE_OUTBOX_EVENT_CLASSIFICATION).toBe('INTERNAL_OPERATIONS');
    expect(B1_REFERRAL_ENGINE_OUTBOX_EVENT_RETENTION_CLASS).toBe('OPERATIONS_DEFAULT');
    expect(B1_REFERRAL_ENGINE_REFERENCE_PREFIX).toBe('b1-referral-decision');
  });

  it('exposes the B1 referral engine retention, classification, and data control classification vocabularies', () => {
    expect(B1_REFERRAL_ENGINE_RETENTION_DAYS).toBe(365);
    expect(B1_REFERRAL_ENGINE_CLASSIFICATION_LEVELS).toContain('PUBLIC');
    expect(B1_REFERRAL_ENGINE_CLASSIFICATION_LEVELS).toContain('INTERNAL');
    expect(B1_REFERRAL_ENGINE_CLASSIFICATION_LEVELS).toContain('CONFIDENTIAL');
    expect(B1_REFERRAL_ENGINE_CLASSIFICATION_LEVELS).toContain('RESTRICTED');
    expect(B1_REFERRAL_ENGINE_CLASSIFICATION_LEVELS).toContain('HIGHLY_RESTRICTED');
    expect(B1_REFERRAL_ENGINE_DATA_CONTROL_CLASSIFICATIONS).toEqual(
      B1_REFERRAL_ENGINE_CLASSIFICATION_LEVELS,
    );
  });

  it('exposes the B1 referral engine rule outcome and rule kind vocabularies', () => {
    expect(B1_REFERRAL_ENGINE_RULE_OUTCOMES).toContain('PASS');
    expect(B1_REFERRAL_ENGINE_RULE_OUTCOMES).toContain('FAIL');
    expect(B1_REFERRAL_ENGINE_RULE_OUTCOMES).toContain('SKIP');
    expect(B1_REFERRAL_ENGINE_RULE_OUTCOMES).toContain('NOT_APPLICABLE');
    expect(B1_REFERRAL_ENGINE_RULE_KINDS.length).toBeGreaterThan(50);
  });

  it('exposes the B1 referral engine prohibited adjacent scopes, prohibited dependencies, and declared dependencies', () => {
    expect(B1_REFERRAL_ENGINE_PROHIBITED_ADJACENT_SCOPES.length).toBeGreaterThan(0);
    expect(B1_REFERRAL_ENGINE_PROHIBITED_DEPENDENCIES).toContain('CASHBACK_REDEMPTION_AUTHORITY');
    expect(B1_REFERRAL_ENGINE_PROHIBITED_DEPENDENCIES).toContain('LOYALTY_BALANCE_AUTHORITY');
    expect(B1_REFERRAL_ENGINE_PROHIBITED_DEPENDENCIES).toContain('REFERRAL_REWARD_AUTHORITY');
    expect(B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES).toContain('A1-CANONICAL-IDENTITY');
    expect(B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES).toContain('A2-AUTHORIZATION-CONTEXT');
    expect(B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES).toContain(
      'A3-CUSTOMER-FINANCIAL-ACCOUNT-BINDING',
    );
    expect(B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES).toContain('A4-PRODUCT-POLICY-DECISION');
    expect(B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES).toContain('A5-LEDGER');
    expect(B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES).toContain('A6-PARTNER-ADAPTER');
    expect(B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES).toContain('A7-PRODUCT-CATALOG');
    expect(B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-COMMERCIAL-CATALOG');
    expect(B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-COMMERCIAL-DECISION');
    expect(B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-BILLING-ENGINE');
    expect(B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES).toContain('B1-CAMPAIGN-ENGINE');
  });

  it('exposes the B1 referral engine compatibility, consumer contract, version negotiation, and replay rule identifiers', () => {
    expect(B1_REFERRAL_ENGINE_COMPATIBILITY_RULE_IDS.length).toBeGreaterThan(0);
    expect(B1_REFERRAL_ENGINE_CONSUMER_CONTRACT_IDS.length).toBeGreaterThan(0);
    expect(B1_REFERRAL_ENGINE_VERSION_NEGOTIATION_RULE_IDS.length).toBeGreaterThan(0);
    expect(B1_REFERRAL_ENGINE_REPLAY_RULE_IDS.length).toBeGreaterThan(0);
  });
});
