export enum ComplianceCaseCategory {
  KYC = 'KYC',
  AML = 'AML',
  SANCTIONS = 'SANCTIONS',
  FRAUD = 'FRAUD',
  PEP = 'PEP',
  DOCUMENT = 'DOCUMENT',
  ACCOUNT_REVIEW = 'ACCOUNT_REVIEW',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
  OTHER = 'OTHER',
}

export enum ComplianceCaseSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ComplianceCaseStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PENDING_CUSTOMER = 'PENDING_CUSTOMER',
  ESCALATED = 'ESCALATED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum ComplianceCaseHistoryAction {
  CASE_CREATED = 'CASE_CREATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  ASSIGNMENT_CHANGED = 'ASSIGNMENT_CHANGED',
  CASE_CLOSED = 'CASE_CLOSED',
  RESOLUTION_UPDATED = 'RESOLUTION_UPDATED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  EVIDENCE_ADDED = 'EVIDENCE_ADDED',
}
