export enum PaymentType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
}

export enum SettlementAccountRole {
  SETTLEMENT_ASSET = 'SETTLEMENT_ASSET',
  SETTLEMENT_CLEARING = 'SETTLEMENT_CLEARING',
  SYSTEM_SUSPENSE = 'SYSTEM_SUSPENSE',
}

export enum PaymentLifecycleState {
  CREATED = 'CREATED',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
