export enum ExternalReconciliationDiscrepancyCode {
  OPERATION_NOT_FOUND = 'OPERATION_NOT_FOUND',
  ORPHAN_OPERATION = 'ORPHAN_OPERATION',
  OPERATION_CURRENCY_MISMATCH = 'OPERATION_CURRENCY_MISMATCH',
  OPERATION_ACCOUNTING_UNIT_MISMATCH = 'OPERATION_ACCOUNTING_UNIT_MISMATCH',
  AMOUNT_MISMATCH = 'AMOUNT_MISMATCH',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  ACCOUNTING_UNIT_MISMATCH = 'ACCOUNTING_UNIT_MISMATCH',
  PARTNER_CAPABILITY_MISMATCH = 'PARTNER_CAPABILITY_MISMATCH',
  CUSTOMER_ACCOUNT_MAPPING_MISMATCH = 'CUSTOMER_ACCOUNT_MAPPING_MISMATCH',
  LIFECYCLE_NOT_VERIFIED = 'LIFECYCLE_NOT_VERIFIED',
  LIFECYCLE_TERMINAL = 'LIFECYCLE_TERMINAL',
  LIFECYCLE_FAILED = 'LIFECYCLE_FAILED',
  LIFECYCLE_CANCELLED = 'LIFECYCLE_CANCELLED',
  MISSING_PROVIDER_REFERENCE = 'MISSING_PROVIDER_REFERENCE',
  DUPLICATE_PROVIDER_REFERENCE = 'DUPLICATE_PROVIDER_REFERENCE',
  PROVIDER_REFERENCE_NAMESPACE_MISMATCH = 'PROVIDER_REFERENCE_NAMESPACE_MISMATCH',
  PROVIDER_REFERENCE_MAPPING_MISMATCH = 'PROVIDER_REFERENCE_MAPPING_MISMATCH',
  MISSING_CALLBACK_RECEIPT = 'MISSING_CALLBACK_RECEIPT',
  DUPLICATE_CALLBACK_RECEIPT = 'DUPLICATE_CALLBACK_RECEIPT',
  CALLBACK_AUTHENTICITY_REJECTED = 'CALLBACK_AUTHENTICITY_REJECTED',
  CALLBACK_REPLAY = 'CALLBACK_REPLAY',
  CALLBACK_AMOUNT_MISMATCH = 'CALLBACK_AMOUNT_MISMATCH',
  CALLBACK_CURRENCY_MISMATCH = 'CALLBACK_CURRENCY_MISMATCH',
  CALLBACK_REFERENCE_MISMATCH = 'CALLBACK_REFERENCE_MISMATCH',
  MISSING_SETTLEMENT = 'MISSING_SETTLEMENT',
  DUPLICATE_SETTLEMENT = 'DUPLICATE_SETTLEMENT',
  SETTLEMENT_NOT_POSTED = 'SETTLEMENT_NOT_POSTED',
  SETTLEMENT_AMOUNT_MISMATCH = 'SETTLEMENT_AMOUNT_MISMATCH',
  SETTLEMENT_CURRENCY_MISMATCH = 'SETTLEMENT_CURRENCY_MISMATCH',
  SETTLEMENT_ACCOUNTING_UNIT_MISMATCH = 'SETTLEMENT_ACCOUNTING_UNIT_MISMATCH',
  SETTLEMENT_EVIDENCE_MISMATCH = 'SETTLEMENT_EVIDENCE_MISMATCH',
  SETTLEMENT_CORRELATION_MISMATCH = 'SETTLEMENT_CORRELATION_MISMATCH',
  SETTLEMENT_REVERSAL_ORPHAN = 'SETTLEMENT_REVERSAL_ORPHAN',
  SETTLEMENT_REVERSAL_DUPLICATE = 'SETTLEMENT_REVERSAL_DUPLICATE',
  MISSING_JOURNAL = 'MISSING_JOURNAL',
  JOURNAL_CORRELATION_MISMATCH = 'JOURNAL_CORRELATION_MISMATCH',
  JOURNAL_BALANCE_MISMATCH = 'JOURNAL_BALANCE_MISMATCH',
  JOURNAL_REVERSAL_ORPHAN = 'JOURNAL_REVERSAL_ORPHAN',
  JOURNAL_REVERSAL_DUPLICATE = 'JOURNAL_REVERSAL_DUPLICATE',
  MISSING_SUSPENSE_ENTRY = 'MISSING_SUSPENSE_ENTRY',
  SUSPENSE_REVERSAL_DUPLICATE = 'SUSPENSE_REVERSAL_DUPLICATE',
  SUSPENSE_REVERSAL_MISSING = 'SUSPENSE_REVERSAL_MISSING',
  SUSPENSE_AGED_OPEN = 'SUSPENSE_AGED_OPEN',
  SUSPENSE_AGED_HELD = 'SUSPENSE_AGED_HELD',
  MISSING_AUDIT_EVIDENCE = 'MISSING_AUDIT_EVIDENCE',
  DUPLICATE_AUDIT_EVIDENCE = 'DUPLICATE_AUDIT_EVIDENCE',
  AUDIT_CORRELATION_MISMATCH = 'AUDIT_CORRELATION_MISMATCH',
  MISSING_OUTBOX_FACT = 'MISSING_OUTBOX_FACT',
  DUPLICATE_OUTBOX_FACT = 'DUPLICATE_OUTBOX_FACT',
  OUTBOX_CORRELATION_MISMATCH = 'OUTBOX_CORRELATION_MISMATCH',
  OUTBOX_PAYLOAD_MISMATCH = 'OUTBOX_PAYLOAD_MISMATCH',
  MISSING_IDEMPOTENCY_REPLAY = 'MISSING_IDEMPOTENCY_REPLAY',
  IDEMPOTENCY_HASH_MISMATCH = 'IDEMPOTENCY_HASH_MISMATCH',
  QUERY_UNAVAILABLE = 'QUERY_UNAVAILABLE',
}

export const EXTERNAL_RECONCILIATION_DISCREPANCY_CODES = Object.values(
  ExternalReconciliationDiscrepancyCode,
);

export const EXTERNAL_RECONCILIATION_EXPECTED_CHECKS = [
  'external_operation_loaded',
  'operation_currency_consistent',
  'operation_accounting_unit_consistent',
  'partner_capability_consistent',
  'lifecycle_state_consistent',
  'provider_reference_present',
  'provider_reference_unique',
  'callback_receipt_present',
  'callback_authenticity_consistent',
  'callback_reference_consistent',
  'callback_amount_consistent',
  'settlement_record_present',
  'settlement_unique',
  'settlement_amount_consistent',
  'settlement_currency_consistent',
  'settlement_accounting_unit_consistent',
  'settlement_evidence_consistent',
  'settlement_correlation_consistent',
  'settlement_reversal_consistent',
  'journal_correlation_consistent',
  'journal_balance_consistent',
  'journal_reversal_consistent',
  'suspense_reversal_consistent',
  'suspense_aging_consistent',
  'audit_evidence_present',
  'audit_correlation_consistent',
  'outbox_fact_present',
  'outbox_correlation_consistent',
  'outbox_payload_consistent',
  'idempotency_replay_consistent',
];

export const EXTERNAL_RECONCILIATION_PARTNER_KEY = 'NIBSS_NIP' as const;
export const EXTERNAL_RECONCILIATION_CAPABILITY_KEY =
  'external.wallet.withdrawal.settlement' as const;
export const EXTERNAL_RECONCILIATION_CAPABILITY_VERSION = '1' as const;
export const EXTERNAL_RECONCILIATION_ADAPTER_VERSION = 'a6-adapter-1' as const;
export const EXTERNAL_RECONCILIATION_CONTRACT_NAME = 'A6-EXTERNAL-RECONCILIATION' as const;
export const EXTERNAL_RECONCILIATION_CONTRACT_VERSION = 1 as const;
export const EXTERNAL_RECONCILIATION_CONTRACT_REFERENCE =
  'docs/ADR/ADR-0053-Independent-External-Reconciliation.md' as const;
export const EXTERNAL_RECONCILIATION_CONTRACT_DOCUMENT =
  'docs/A6-EXTERNAL-RECONCILIATION-CONTRACT.md' as const;
export const EXTERNAL_RECONCILIATION_SUSPENSE_AGED_HOURS = 24;
