export enum CustomerEligibilityStatus {
  PENDING = 'PENDING',
  ELIGIBLE = 'ELIGIBLE',
  INELIGIBLE = 'INELIGIBLE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
}

export enum CustomerProductEnrollmentStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  CLOSED = 'CLOSED',
}

export enum CustomerOperatingPermissionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  TRANSFER = 'TRANSFER',
  PAYMENT = 'PAYMENT',
  BILL_PAYMENT = 'BILL_PAYMENT',
  AIRTIME = 'AIRTIME',
  CARD = 'CARD',
  VIRTUAL_ACCOUNT = 'VIRTUAL_ACCOUNT',
  QR_PAYMENT = 'QR_PAYMENT',
  USSD = 'USSD',
  API = 'API',
}

export enum CustomerRestrictionType {
  NONE = 'NONE',
  LIMITED = 'LIMITED',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
  FROZEN = 'FROZEN',
  BLACKLISTED = 'BLACKLISTED',
}

export enum CustomerLimitType {
  DAILY_TRANSACTION_COUNT = 'DAILY_TRANSACTION_COUNT',
  DAILY_TRANSACTION_AMOUNT = 'DAILY_TRANSACTION_AMOUNT',
  SINGLE_TRANSACTION_AMOUNT = 'SINGLE_TRANSACTION_AMOUNT',
  MONTHLY_TRANSACTION_AMOUNT = 'MONTHLY_TRANSACTION_AMOUNT',
  WALLET_BALANCE = 'WALLET_BALANCE',
}

export type CustomerOperatingStatus =
  | 'OPERABLE'
  | 'RESTRICTED'
  | 'INELIGIBLE'
  | 'SUSPENDED'
  | 'FROZEN'
  | 'BLACKLISTED'
  | 'REVOKED';
