export enum AuthenticationCredentialStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
}

export enum AuthenticationCredentialType {
  PASSWORD = 'PASSWORD',
}

export enum PasswordHashAlgorithm {
  ARGON2ID = 'ARGON2ID',
  BCRYPT = 'BCRYPT',
  SCRYPT = 'SCRYPT',
  PBKDF2 = 'PBKDF2',
}

export enum PasswordResetRequestStatus {
  REQUESTED = 'REQUESTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}

export enum PasswordResetTokenStatus {
  ACTIVE = 'ACTIVE',
  USED = 'USED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum MfaEnrollmentStatus {
  PENDING = 'PENDING',
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED',
  REVOKED = 'REVOKED',
}

export enum MfaMethodType {
  TOTP = 'TOTP',
  AUTHENTICATOR_APP = 'AUTHENTICATOR_APP',
  SECURITY_KEY = 'SECURITY_KEY',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
}

export enum MfaMethodStatus {
  PENDING = 'PENDING',
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED',
  REVOKED = 'REVOKED',
}

export enum TrustedDeviceStatus {
  PENDING = 'PENDING',
  TRUSTED = 'TRUSTED',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
}

export enum RecoveryCodeStatus {
  AVAILABLE = 'AVAILABLE',
  USED = 'USED',
  REVOKED = 'REVOKED',
}

export enum SecurityEventType {
  CREDENTIAL_CREATED = 'CREDENTIAL_CREATED',
  CREDENTIAL_UPDATED = 'CREDENTIAL_UPDATED',
  PASSWORD_ROTATED = 'PASSWORD_ROTATED',
  PASSWORD_EXPIRED = 'PASSWORD_EXPIRED',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_TOKEN_ISSUED = 'PASSWORD_RESET_TOKEN_ISSUED',
  PASSWORD_RESET_TOKEN_UPDATED = 'PASSWORD_RESET_TOKEN_UPDATED',
  PASSWORD_RESET_STATUS_CHANGED = 'PASSWORD_RESET_STATUS_CHANGED',
  MFA_ENROLLMENT_CREATED = 'MFA_ENROLLMENT_CREATED',
  MFA_ENROLLMENT_UPDATED = 'MFA_ENROLLMENT_UPDATED',
  MFA_METHOD_ADDED = 'MFA_METHOD_ADDED',
  MFA_METHOD_UPDATED = 'MFA_METHOD_UPDATED',
  TRUSTED_DEVICE_REGISTERED = 'TRUSTED_DEVICE_REGISTERED',
  TRUSTED_DEVICE_UPDATED = 'TRUSTED_DEVICE_UPDATED',
  RECOVERY_CODE_CREATED = 'RECOVERY_CODE_CREATED',
  RECOVERY_CODE_UPDATED = 'RECOVERY_CODE_UPDATED',
}

export enum PasswordHistoryAction {
  CREATED = 'CREATED',
  ROTATED = 'ROTATED',
}
