export enum PrivilegedActionApprovalStatus {
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  CONSUMED = 'CONSUMED',
  EXPIRED = 'EXPIRED',
  EMERGENCY_ACTIVE = 'EMERGENCY_ACTIVE',
  EMERGENCY_REVOKED = 'EMERGENCY_REVOKED',
}
