export enum CapabilityDomain {
  CUSTOMER = 'CUSTOMER',
  AGENT = 'AGENT',
  AGGREGATOR = 'AGGREGATOR',
  ADMIN = 'ADMIN',
  PLATFORM = 'PLATFORM',
  WALLET = 'WALLET',
  LEDGER = 'LEDGER',
  NOTIFICATION = 'NOTIFICATION',
  SUPPORT = 'SUPPORT',
  RECONCILIATION = 'RECONCILIATION',
  COMMERCIAL = 'COMMERCIAL',
  SECURITY = 'SECURITY',
  IDENTITY = 'IDENTITY',
  FUNDING = 'FUNDING',
  OUTLET = 'OUTLET',
}

export enum CapabilityProductScope {
  V1 = 'V1',
  V2 = 'V2',
}

export enum CapabilityLifecycle {
  PLANNED = 'PLANNED',
  DESIGNED = 'DESIGNED',
  BACKEND_IMPLEMENTED = 'BACKEND_IMPLEMENTED',
  API_READY = 'API_READY',
  ADMIN_UI_READY = 'ADMIN_UI_READY',
  CUSTOMER_UI_READY = 'CUSTOMER_UI_READY',
  AGENT_UI_READY = 'AGENT_UI_READY',
  FULLY_ENABLED = 'FULLY_ENABLED',
  DISABLED = 'DISABLED',
  BLOCKED = 'BLOCKED',
  DEPRECATED = 'DEPRECATED',
}

export enum CapabilityBackendStatus {
  PLANNED = 'PLANNED',
  DESIGNED = 'DESIGNED',
  BACKEND_IMPLEMENTED = 'BACKEND_IMPLEMENTED',
  DISABLED = 'DISABLED',
  DEPRECATED = 'DEPRECATED',
  BLOCKED = 'BLOCKED',
}

export enum CapabilityApiStatus {
  NOT_EXPOSED = 'NOT_EXPOSED',
  API_READY = 'API_READY',
  DEPRECATED = 'DEPRECATED',
}

export enum CapabilityAdminUiStatus {
  NOT_EXPOSED = 'NOT_EXPOSED',
  ADMIN_UI_READY = 'ADMIN_UI_READY',
  DEPRECATED = 'DEPRECATED',
}

export enum CapabilityCustomerUiStatus {
  NOT_EXPOSED = 'NOT_EXPOSED',
  CUSTOMER_UI_READY = 'CUSTOMER_UI_READY',
  DEPRECATED = 'DEPRECATED',
}

export enum CapabilityAgentUiStatus {
  NOT_EXPOSED = 'NOT_EXPOSED',
  AGENT_UI_READY = 'AGENT_UI_READY',
  DEPRECATED = 'DEPRECATED',
}

export enum CapabilityConfigurationStatus {
  NOT_CONFIGURED = 'NOT_CONFIGURED',
  CONFIGURED = 'CONFIGURED',
  DISABLED = 'DISABLED',
}

export enum CapabilityBlockerType {
  NONE = 'NONE',
  PRODUCT_DECISION = 'PRODUCT_DECISION',
  ACCOUNTING_DECISION = 'ACCOUNTING_DECISION',
  EXTERNAL_DEPENDENCY = 'EXTERNAL_DEPENDENCY',
  V2 = 'V2',
}
