export enum LimitFailureCode {
  LIMIT_MIN_AMOUNT_NOT_MET = 'LIMIT_MIN_AMOUNT_NOT_MET',
  LIMIT_MAX_AMOUNT_EXCEEDED = 'LIMIT_MAX_AMOUNT_EXCEEDED',
  LIMIT_DAILY_AMOUNT_EXCEEDED = 'LIMIT_DAILY_AMOUNT_EXCEEDED',
  LIMIT_WEEKLY_AMOUNT_EXCEEDED = 'LIMIT_WEEKLY_AMOUNT_EXCEEDED',
  LIMIT_MONTHLY_AMOUNT_EXCEEDED = 'LIMIT_MONTHLY_AMOUNT_EXCEEDED',
  LIMIT_YEARLY_AMOUNT_EXCEEDED = 'LIMIT_YEARLY_AMOUNT_EXCEEDED',
  LIMIT_DAILY_COUNT_EXCEEDED = 'LIMIT_DAILY_COUNT_EXCEEDED',
  LIMIT_WEEKLY_COUNT_EXCEEDED = 'LIMIT_WEEKLY_COUNT_EXCEEDED',
  LIMIT_MONTHLY_COUNT_EXCEEDED = 'LIMIT_MONTHLY_COUNT_EXCEEDED',
  LIMIT_YEARLY_COUNT_EXCEEDED = 'LIMIT_YEARLY_COUNT_EXCEEDED',
  LIMIT_WALLET_BALANCE_EXCEEDED = 'LIMIT_WALLET_BALANCE_EXCEEDED',
  LIMIT_PROFILE_MISSING = 'LIMIT_PROFILE_MISSING',
  LIMIT_RULE_INVALID = 'LIMIT_RULE_INVALID',
  LIMIT_CONFIGURATION_INVALID = 'LIMIT_CONFIGURATION_INVALID',
  LIMIT_RESERVATION_FAILED = 'LIMIT_RESERVATION_FAILED',
}

export function dimensionToFailureCode(dimension: string, exceeded: boolean): LimitFailureCode {
  const d = dimension.toUpperCase();
  if (d === 'MIN_AMOUNT_PER_TX') return LimitFailureCode.LIMIT_MIN_AMOUNT_NOT_MET;
  if (d === 'MAX_AMOUNT_PER_TX') return LimitFailureCode.LIMIT_MAX_AMOUNT_EXCEEDED;
  if (d === 'DAILY_AMOUNT') return LimitFailureCode.LIMIT_DAILY_AMOUNT_EXCEEDED;
  if (d === 'WEEKLY_AMOUNT') return LimitFailureCode.LIMIT_WEEKLY_AMOUNT_EXCEEDED;
  if (d === 'MONTHLY_AMOUNT') return LimitFailureCode.LIMIT_MONTHLY_AMOUNT_EXCEEDED;
  if (d === 'YEARLY_AMOUNT') return LimitFailureCode.LIMIT_YEARLY_AMOUNT_EXCEEDED;
  if (d === 'DAILY_COUNT') return LimitFailureCode.LIMIT_DAILY_COUNT_EXCEEDED;
  if (d === 'WEEKLY_COUNT') return LimitFailureCode.LIMIT_WEEKLY_COUNT_EXCEEDED;
  if (d === 'MONTHLY_COUNT') return LimitFailureCode.LIMIT_MONTHLY_COUNT_EXCEEDED;
  if (d === 'YEARLY_COUNT') return LimitFailureCode.LIMIT_YEARLY_COUNT_EXCEEDED;
  if (d === 'WALLET_BALANCE_MAX') return LimitFailureCode.LIMIT_WALLET_BALANCE_EXCEEDED;
  return LimitFailureCode.LIMIT_CONFIGURATION_INVALID;
}
