import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  VersionColumn,
} from 'typeorm';

import { AgentStatus } from './agent.enums';

/**
 * Canonical V1 Agent identity (ADR-0093 §8, Stage 1).
 *
 * Agent is a first-class domain aggregate, distinct from Customer. `Agent.id`
 * is the canonical identity and is generated by the Agent domain; it is never
 * derived from a `Customer.id`, and it is never an alias, a phone number or a
 * MonieNaija number.
 *
 * DELIBERATE STAGE 1 BOUNDARY — this aggregate carries NO financial identity.
 * There is no wallet, no WalletAccount reference, no LedgerAccount reference,
 * no financial binding, no balance, no MonieNaija number, no credential and no
 * PIN. Those belong to Stages 2-4 and remain blocked on Finance decisions F-1
 * to F-4 and on the number-allocation strategy. Nothing in this file may be
 * extended to imply financial ownership.
 *
 * `reference` is a caller-supplied registry/correlation string following the
 * same convention as `Customer.reference`. It is explicitly NOT the "Agent
 * Code": the Agent Code is the Agent login identity, recorded as open product
 * decision C1/O3 in `ADR-0093-V1-AGENT-IDENTITY-DECISION-RESOLUTION.md` §6,
 * and no login identity is created by Stage 1.
 */
@Entity({ name: 'agents' })
@Index('uq_agents_reference', ['reference'], { unique: true })
@Index('idx_agents_status', ['status'])
@Index('idx_agents_operator_customer', ['operatorCustomerId'])
export class Agent {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ type: 'varchar', length: 160 })
  reference!: string;

  @Column({ type: 'varchar', length: 20 })
  status!: AgentStatus;

  /**
   * Optional, non-authoritative trace to a Customer record (ADR-0093 §8.5).
   *
   * Nullable: an Agent can exist without a Customer. Not unique: one Customer
   * may operate multiple Agents. It confers NO identity, wallet, number,
   * credential or permission on the Agent, and Agent status is never driven by
   * Customer status.
   */
  @Column({ name: 'operator_customer_id', type: 'uuid', nullable: true })
  operatorCustomerId!: string | null;

  @VersionColumn({ type: 'integer', default: 1 })
  version!: number;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;

  @DeleteDateColumn({ name: 'deleted_at', type: 'timestamptz', nullable: true })
  deletedAt!: Date | null;
}
