/**
 * A7T09 — A7 product reconciliation, certification, and support
 * trace frozen constants for the A7 first product.
 *
 * The A7 first product is `VIRTUAL_ACCOUNT` v1 (per
 * `docs/A7-PRODUCT-EXPANSION-BASELINE.md` and
 * `docs/A7-PRODUCT-CATALOG-CONTRACT.md`). The A7 product
 * reconciliation contract is the runtime independent read-only
 * product reconciliation, certification, and support-trace
 * implementation for the A7 first product.
 *
 * The A7 product reconciliation contract composes the existing
 * A2 authorization, A3 customer-to-financial-account binding, A4
 * product-policy decision, A5 Ledger / journal / line, A6T05
 * external-operation identity, A6T07 lifecycle, A6T08 settlement /
 * suspense / compensating-entry, A6T09 external reconciliation,
 * A6T10 data-classification, A6T11 integration, A7 product
 * catalog, A7 product-policy profile, A7T04 product
 * customer-binding, A7T05 product command/operation, A7T06
 * product notification delivery, A7T07 product lifecycle, and
 * A7T08 product financial effect, and the shared Operations
 * audit, idempotency, outbox, metrics, and diagnostics services.
 *
 * The A7 product reconciliation contract is a read-only contract
 * against the shared Operations `DiagnosticsService` and the
 * existing A6T09 `ExternalReconciliationService`. The A7 product
 * reconciliation contract does NOT introduce a second
 * reconciliation engine, a second Ledger authority, a second
 * settlement authority, a second suspense authority, a second
 * compensating-entry authority, a second financial-invariants
 * engine, a second audit authority, a second idempotency
 * authority, a second outbox authority, a second metrics
 * authority, a second diagnostics authority, a second
 * customer-binding authority, a second policy authority, a second
 * authorization authority, a second notification authority, a new
 * product identity, or a new product financial identity. The
 * existing A6T09 external reconciliation service remains the only
 * external reconciliation authority. The existing A5 Ledger
 * service remains the only financial value authority. The
 * existing A6T08 ExternalSettlementService remains the only
 * settlement / suspense / compensating authority.
 *
 * No Ledger redesign, no unauthorized chart expansion, no FX, no
 * fees/commissions, no savings interest, no lending, no customer
 * credit beyond approved product limits, no automatic suspense
 * clearing, no auto-repair, and no external financial correction
 * outside Ledger/Finance ownership is introduced by A7T09.
 */

import { NIBSS_NIP_PARTNER_KEY } from '../partner/partner-adapter.types';

/**
 * A7 product reconciliation contract name (frozen by
 * `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §2.2).
 */
export const A7_PRODUCT_RECONCILIATION_CONTRACT_NAME = 'A7-PRODUCT-RECONCILIATION' as const;

/**
 * A7 product reconciliation contract version (frozen by
 * `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §2.2).
 */
export const A7_PRODUCT_RECONCILIATION_CONTRACT_VERSION = 1 as const;

/**
 * A7 product reconciliation identity namespace.
 */
export const A7_PRODUCT_RECONCILIATION_IDENTITY_NAMESPACE = 'A7-PRODUCT-RECONCILIATION' as const;

/**
 * A7 product reconciliation internal idempotency scope (frozen
 * by `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §6).
 *
 * The A7 product reconciliation internal idempotency scope is a
 * separate namespace from the A7T05 internal idempotency scope
 * (`A7-PRODUCT-IDEMPOTENCY.v1`), the A7T06 internal idempotency
 * scope (`a7.notification-dispatch.idempotency.v1`), the A7T07
 * internal idempotency scope
 * (`a7.product-lifecycle.idempotency.v1`), the A7T08 internal
 * idempotency scope
 * (`a7.product-financial-effect.idempotency.v1`), and the A6T05
 * internal idempotency scope
 * (`external.partner.operation.v1`). The A7 product
 * reconciliation contract does NOT generate or maintain a separate
 * A7 provider idempotency scope; the A7 product reconciliation
 * contract reads the A6T05 provider idempotency scope/key from
 * the A6T05 `ExternalOperation` record and references it inside
 * the A7 product reconciliation report payload as correlation
 * metadata per ADR-0049.
 */
export const A7_PRODUCT_RECONCILIATION_INTERNAL_IDEMPOTENCY_SCOPE =
  'a7.product-reconciliation.idempotency.v1' as const;

/**
 * A7 product reconciliation provider idempotency scope (frozen
 * by `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §2.2).
 *
 * The A7 product reconciliation provider idempotency scope is
 * sourced from the A6T05 provider idempotency scope per ADR-0049.
 * The A7 product reconciliation contract does NOT generate or
 * maintain a separate A7 provider idempotency scope.
 */
export const A7_PRODUCT_RECONCILIATION_PROVIDER_IDEMPOTENCY_SCOPE =
  'nibss.nip.external-operation.v1' as const;

/**
 * A7 product reconciliation retention interval (24 hours; aligned
 * with the shared Operations `IdempotencyService` default and the
 * A6T05 `ExternalSettlementService` default).
 */
export const A7_PRODUCT_RECONCILIATION_RETENTION_SECONDS = 86_400 as const;

/**
 * A7 product reconciliation audit entity type (reused by the
 * shared Operations `AuditService`; the A7 product reconciliation
 * audit fact is recorded against the
 * `A7_PRODUCT_RECONCILIATION` entity type).
 */
export const A7_PRODUCT_RECONCILIATION_AUDIT_ENTITY_TYPE = 'A7_PRODUCT_RECONCILIATION' as const;

/**
 * A7 product reconciliation audit actor (reused by the shared
 * Operations `AuditService`).
 */
export const A7_PRODUCT_RECONCILIATION_AUDIT_ACTOR = 'a7-product-reconciliation' as const;

/**
 * A7 product reconciliation audit action codes. The A7 product
 * reconciliation audit facts are recorded through the shared
 * Operations `AuditService`; the `action` is one of the A7
 * product reconciliation audit action codes.
 */
export const A7_PRODUCT_RECONCILIATION_AUDIT_ACTION_PRODUCT_RECONCILED =
  'A7_PRODUCT_RECONCILIATION_PRODUCT_RECONCILED' as const;
export const A7_PRODUCT_RECONCILIATION_AUDIT_ACTION_BATCH_RECONCILED =
  'A7_PRODUCT_RECONCILIATION_BATCH_RECONCILED' as const;
export const A7_PRODUCT_RECONCILIATION_AUDIT_ACTION_SUPPORT_TRACE_EMITTED =
  'A7_PRODUCT_RECONCILIATION_SUPPORT_TRACE_EMITTED' as const;
export const A7_PRODUCT_RECONCILIATION_AUDIT_ACTION_CERTIFICATION_EMITTED =
  'A7_PRODUCT_RECONCILIATION_CERTIFICATION_EMITTED' as const;
export const A7_PRODUCT_RECONCILIATION_AUDIT_ACTION_QUERY_UNAVAILABLE =
  'A7_PRODUCT_RECONCILIATION_QUERY_UNAVAILABLE' as const;
export const A7_PRODUCT_RECONCILIATION_AUDIT_ACTION_NO_DISCREPANCY =
  'A7_PRODUCT_RECONCILIATION_NO_DISCREPANCY' as const;
export const A7_PRODUCT_RECONCILIATION_AUDIT_ACTION_DISCREPANCY_REPORTED =
  'A7_PRODUCT_RECONCILIATION_DISCREPANCY_REPORTED' as const;

/**
 * A7 product reconciliation check vocabulary (frozen by
 * `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §4.1). The A7
 * product reconciliation check vocabulary is a read-only product
 * reconciliation vocabulary. The vocabulary extends, but does NOT
 * replace, the A6T09 external reconciliation check vocabulary.
 */
export const A7_PRODUCT_RECONCILIATION_CHECKS: readonly string[] = Object.freeze([
  'PRODUCT_OPERATION_PRESENT',
  'PRODUCT_OPERATION_KEY_CONSISTENT',
  'PRODUCT_OPERATION_CAPABILITY_CONSISTENT',
  'PRODUCT_OPERATION_AMOUNT_CONSISTENT',
  'PRODUCT_OPERATION_CURRENCY_CONSISTENT',
  'PRODUCT_OPERATION_ACCOUNTING_UNIT_CONSISTENT',
  'PRODUCT_OPERATION_STATE_CONSISTENT',
  'PRODUCT_LIFECYCLE_VERIFIED',
  'PRODUCT_COMMAND_PRESENT',
  'PRODUCT_COMMAND_AMOUNT_CONSISTENT',
  'PRODUCT_COMMAND_CURRENCY_CONSISTENT',
  'PRODUCT_COMMAND_ACCOUNTING_UNIT_CONSISTENT',
  'PRODUCT_COMMAND_BINDING_CONSISTENT',
  'PRODUCT_CUSTOMER_BINDING_PRESENT',
  'PRODUCT_CUSTOMER_BINDING_ACTIVE',
  'PRODUCT_CUSTOMER_BINDING_AMOUNT_CONSISTENT',
  'PRODUCT_CUSTOMER_BINDING_CURRENCY_CONSISTENT',
  'PRODUCT_CUSTOMER_BINDING_ACCOUNTING_UNIT_CONSISTENT',
  'A2_AUTHORIZATION_PRESENT',
  'A2_AUTHORIZATION_NOT_EXPIRED',
  'A4_PRODUCT_POLICY_DECISION_PRESENT',
  'A4_PRODUCT_POLICY_DECISION_NOT_EXPIRED',
  'A4_PRODUCT_POLICY_DECISION_EXECUTABLE',
  'A5_LEDGER_JOURNAL_CORRELATION_CONSISTENT',
  'A5_LEDGER_JOURNAL_BALANCE_CONSISTENT',
  'A5_LEDGER_REVERSAL_CONSISTENT',
  'A6_EXTERNAL_OPERATION_PRESENT',
  'A6_EXTERNAL_OPERATION_PARTNER_CONSISTENT',
  'A6_EXTERNAL_OPERATION_CAPABILITY_CONSISTENT',
  'A6_EXTERNAL_OPERATION_LIFECYCLE_VERIFIED',
  'A6_CALLBACK_RECEIPT_PRESENT',
  'A6_CALLBACK_RECEIPT_AUTHENTIC',
  'A6_CALLBACK_RECEIPT_UNIQUE',
  'A6_CALLBACK_RECEIPT_AMOUNT_CONSISTENT',
  'A6_CALLBACK_RECEIPT_CURRENCY_CONSISTENT',
  'A6_SETTLEMENT_PRESENT',
  'A6_SETTLEMENT_AMOUNT_CONSISTENT',
  'A6_SETTLEMENT_CURRENCY_CONSISTENT',
  'A6_SETTLEMENT_ACCOUNTING_UNIT_CONSISTENT',
  'A6_SUSPENSE_PRESENT',
  'A6_SUSPENSE_AMOUNT_CONSISTENT',
  'A6_SUSPENSE_CURRENCY_CONSISTENT',
  'A6_SUSPENSE_ACCOUNTING_UNIT_CONSISTENT',
  'A6_SUSPENSE_AGING_CONSISTENT',
  'A6_PROVIDER_REFERENCE_PRESENT',
  'A6_PROVIDER_REFERENCE_UNIQUE',
  'A6_PARTNER_OUTAGE_NONE',
  'A6_REPORT_AVAILABLE',
  'NOTIFICATION_DISPATCH_FACT_PRESENT',
  'NOTIFICATION_DISPATCH_AUDIENCE_CONSISTENT',
  'NOTIFICATION_DISPATCH_DELIVERY_LIFECYCLE_CONSISTENT',
  'NOTIFICATION_DISPATCH_REDACTION_CONSISTENT',
  'OPERATIONS_AUDIT_FACT_PRESENT',
  'OPERATIONS_AUDIT_CORRELATION_CONSISTENT',
  'OPERATIONS_IDEMPOTENCY_RECORD_PRESENT',
  'OPERATIONS_IDEMPOTENCY_HASH_CONSISTENT',
  'OPERATIONS_OUTBOX_FACT_PRESENT',
  'OPERATIONS_OUTBOX_CORRELATION_CONSISTENT',
  'OPERATIONS_DIAGNOSTICS_FACT_PRESENT',
]);

/**
 * A7 product reconciliation expected checks vocabulary. The A7
 * product reconciliation expected checks vocabulary is the closed
 * set of check keys that the A7 product reconciliation evaluator
 * is REQUIRED to evaluate. The A7 product reconciliation expected
 * checks vocabulary is frozen by
 * `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §4.1.
 */
export const A7_PRODUCT_RECONCILIATION_EXPECTED_CHECKS: readonly string[] = Object.freeze([
  'PRODUCT_OPERATION_PRESENT',
  'PRODUCT_LIFECYCLE_VERIFIED',
  'PRODUCT_COMMAND_PRESENT',
  'PRODUCT_CUSTOMER_BINDING_PRESENT',
  'A2_AUTHORIZATION_PRESENT',
  'A4_PRODUCT_POLICY_DECISION_PRESENT',
  'A5_LEDGER_JOURNAL_CORRELATION_CONSISTENT',
  'A6_EXTERNAL_OPERATION_PRESENT',
  'A6_CALLBACK_RECEIPT_PRESENT',
  'A6_SETTLEMENT_PRESENT',
  'A6_SUSPENSE_PRESENT',
  'A6_PROVIDER_REFERENCE_PRESENT',
  'A6_REPORT_AVAILABLE',
  'NOTIFICATION_DISPATCH_FACT_PRESENT',
  'OPERATIONS_AUDIT_FACT_PRESENT',
  'OPERATIONS_IDEMPOTENCY_RECORD_PRESENT',
  'OPERATIONS_OUTBOX_FACT_PRESENT',
  'OPERATIONS_DIAGNOSTICS_FACT_PRESENT',
]);

/**
 * A7 product reconciliation discrepancy code vocabulary (frozen
 * by `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §4.2). The A7
 * product reconciliation discrepancy code vocabulary is a
 * deterministic product-side vocabulary. Each discrepancy code
 * is mapped to a fixed severity, owner, and recovery state by
 * the A7 product reconciliation discrepancy severity mapping in
 * `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §4.6.
 */
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_PRODUCT_OPERATION =
  'A7_PRODUCT_RECONCILIATION_MISSING_PRODUCT_OPERATION' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_PRODUCT_LIFECYCLE =
  'A7_PRODUCT_RECONCILIATION_MISSING_PRODUCT_LIFECYCLE' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_PRODUCT_COMMAND =
  'A7_PRODUCT_RECONCILIATION_MISSING_PRODUCT_COMMAND' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_PRODUCT_CUSTOMER_BINDING =
  'A7_PRODUCT_RECONCILIATION_MISSING_PRODUCT_CUSTOMER_BINDING' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A2_AUTHORIZATION =
  'A7_PRODUCT_RECONCILIATION_MISSING_A2_AUTHORIZATION' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A4_PRODUCT_POLICY_DECISION =
  'A7_PRODUCT_RECONCILIATION_MISSING_A4_PRODUCT_POLICY_DECISION' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A5_LEDGER_JOURNAL =
  'A7_PRODUCT_RECONCILIATION_MISSING_A5_LEDGER_JOURNAL' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_EXTERNAL_OPERATION =
  'A7_PRODUCT_RECONCILIATION_MISSING_A6_EXTERNAL_OPERATION' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_CALLBACK_RECEIPT =
  'A7_PRODUCT_RECONCILIATION_MISSING_A6_CALLBACK_RECEIPT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_SETTLEMENT =
  'A7_PRODUCT_RECONCILIATION_MISSING_A6_SETTLEMENT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_SUSPENSE =
  'A7_PRODUCT_RECONCILIATION_MISSING_A6_SUSPENSE' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_PROVIDER_REFERENCE =
  'A7_PRODUCT_RECONCILIATION_MISSING_A6_PROVIDER_REFERENCE' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_NOTIFICATION_DISPATCH_FACT =
  'A7_PRODUCT_RECONCILIATION_MISSING_NOTIFICATION_DISPATCH_FACT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_OPERATIONS_AUDIT_FACT =
  'A7_PRODUCT_RECONCILIATION_MISSING_OPERATIONS_AUDIT_FACT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_OPERATIONS_IDEMPOTENCY_RECORD =
  'A7_PRODUCT_RECONCILIATION_MISSING_OPERATIONS_IDEMPOTENCY_RECORD' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_OPERATIONS_OUTBOX_FACT =
  'A7_PRODUCT_RECONCILIATION_MISSING_OPERATIONS_OUTBOX_FACT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_OPERATIONS_DIAGNOSTICS_FACT =
  'A7_PRODUCT_RECONCILIATION_MISSING_OPERATIONS_DIAGNOSTICS_FACT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_REPORT =
  'A7_PRODUCT_RECONCILIATION_MISSING_A6_REPORT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_PRODUCT_OPERATION =
  'A7_PRODUCT_RECONCILIATION_DUPLICATE_PRODUCT_OPERATION' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_PRODUCT_COMMAND =
  'A7_PRODUCT_RECONCILIATION_DUPLICATE_PRODUCT_COMMAND' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_A6_CALLBACK_RECEIPT =
  'A7_PRODUCT_RECONCILIATION_DUPLICATE_A6_CALLBACK_RECEIPT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_A6_SETTLEMENT =
  'A7_PRODUCT_RECONCILIATION_DUPLICATE_A6_SETTLEMENT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_A6_PROVIDER_REFERENCE =
  'A7_PRODUCT_RECONCILIATION_DUPLICATE_A6_PROVIDER_REFERENCE' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_NOTIFICATION_DISPATCH_FACT =
  'A7_PRODUCT_RECONCILIATION_DUPLICATE_NOTIFICATION_DISPATCH_FACT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_OPERATIONS_AUDIT_FACT =
  'A7_PRODUCT_RECONCILIATION_DUPLICATE_OPERATIONS_AUDIT_FACT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_OPERATIONS_OUTBOX_FACT =
  'A7_PRODUCT_RECONCILIATION_DUPLICATE_OPERATIONS_OUTBOX_FACT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_ORPHAN_PRODUCT_OPERATION =
  'A7_PRODUCT_RECONCILIATION_ORPHAN_PRODUCT_OPERATION' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_ORPHAN_A6_SETTLEMENT =
  'A7_PRODUCT_RECONCILIATION_ORPHAN_A6_SETTLEMENT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_ORPHAN_A6_SUSPENSE =
  'A7_PRODUCT_RECONCILIATION_ORPHAN_A6_SUSPENSE' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_ORPHAN_A6_CALLBACK_RECEIPT =
  'A7_PRODUCT_RECONCILIATION_ORPHAN_A6_CALLBACK_RECEIPT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_ORPHAN_NOTIFICATION_DISPATCH_FACT =
  'A7_PRODUCT_RECONCILIATION_ORPHAN_NOTIFICATION_DISPATCH_FACT' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_AMOUNT_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_AMOUNT_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_CURRENCY_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_CURRENCY_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_ACCOUNTING_UNIT_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_ACCOUNTING_UNIT_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_BINDING_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_BINDING_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_CAPABILITY_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_CAPABILITY_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_PARTNER_KEY_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_PARTNER_KEY_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_LIFECYCLE_NOT_VERIFIED =
  'A7_PRODUCT_RECONCILIATION_LIFECYCLE_NOT_VERIFIED' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_LIFECYCLE_FAILED =
  'A7_PRODUCT_RECONCILIATION_LIFECYCLE_FAILED' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_LIFECYCLE_CANCELLED =
  'A7_PRODUCT_RECONCILIATION_LIFECYCLE_CANCELLED' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_LIFECYCLE_TERMINAL =
  'A7_PRODUCT_RECONCILIATION_LIFECYCLE_TERMINAL' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A2_AUTHORIZATION_EXPIRED =
  'A7_PRODUCT_RECONCILIATION_A2_AUTHORIZATION_EXPIRED' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A4_PRODUCT_POLICY_DECISION_EXPIRED =
  'A7_PRODUCT_RECONCILIATION_A4_PRODUCT_POLICY_DECISION_EXPIRED' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A4_PRODUCT_POLICY_DECISION_NOT_EXECUTABLE =
  'A7_PRODUCT_RECONCILIATION_A4_PRODUCT_POLICY_DECISION_NOT_EXECUTABLE' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A5_LEDGER_JOURNAL_BALANCE_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_A5_LEDGER_JOURNAL_BALANCE_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A5_LEDGER_JOURNAL_CORRELATION_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_A5_LEDGER_JOURNAL_CORRELATION_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A5_LEDGER_REVERSAL_ORPHAN =
  'A7_PRODUCT_RECONCILIATION_A5_LEDGER_REVERSAL_ORPHAN' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A5_LEDGER_REVERSAL_DUPLICATE =
  'A7_PRODUCT_RECONCILIATION_A5_LEDGER_REVERSAL_DUPLICATE' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_CALLBACK_RECEIPT_AMOUNT_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_A6_CALLBACK_RECEIPT_AMOUNT_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_CALLBACK_RECEIPT_CURRENCY_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_A6_CALLBACK_RECEIPT_CURRENCY_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_CALLBACK_RECEIPT_REFERENCE_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_A6_CALLBACK_RECEIPT_REFERENCE_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_CALLBACK_REPLAY =
  'A7_PRODUCT_RECONCILIATION_A6_CALLBACK_REPLAY' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_CALLBACK_AUTHENTICITY_REJECTED =
  'A7_PRODUCT_RECONCILIATION_A6_CALLBACK_AUTHENTICITY_REJECTED' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SETTLEMENT_AMOUNT_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_A6_SETTLEMENT_AMOUNT_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SETTLEMENT_CURRENCY_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_A6_SETTLEMENT_CURRENCY_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SETTLEMENT_ACCOUNTING_UNIT_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_A6_SETTLEMENT_ACCOUNTING_UNIT_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SETTLEMENT_NOT_POSTED =
  'A7_PRODUCT_RECONCILIATION_A6_SETTLEMENT_NOT_POSTED' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SUSPENSE_AMOUNT_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_A6_SUSPENSE_AMOUNT_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SUSPENSE_CURRENCY_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_A6_SUSPENSE_CURRENCY_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SUSPENSE_ACCOUNTING_UNIT_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_A6_SUSPENSE_ACCOUNTING_UNIT_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SUSPENSE_AGED =
  'A7_PRODUCT_RECONCILIATION_A6_SUSPENSE_AGED' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_PARTNER_OUTAGE =
  'A7_PRODUCT_RECONCILIATION_A6_PARTNER_OUTAGE' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_REPORT_STALE =
  'A7_PRODUCT_RECONCILIATION_A6_REPORT_STALE' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_REPORT_UNAVAILABLE =
  'A7_PRODUCT_RECONCILIATION_A6_REPORT_UNAVAILABLE' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_NOTIFICATION_DISPATCH_AUDIENCE_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_NOTIFICATION_DISPATCH_AUDIENCE_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_NOTIFICATION_DISPATCH_REDACTION_FAILED =
  'A7_PRODUCT_RECONCILIATION_NOTIFICATION_DISPATCH_REDACTION_FAILED' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_NOTIFICATION_DISPATCH_DELIVERY_LIFECYCLE_BROKEN =
  'A7_PRODUCT_RECONCILIATION_NOTIFICATION_DISPATCH_DELIVERY_LIFECYCLE_BROKEN' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_IDEMPOTENCY_HASH_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_IDEMPOTENCY_HASH_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_OUTBOX_PAYLOAD_MISMATCH =
  'A7_PRODUCT_RECONCILIATION_OUTBOX_PAYLOAD_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_QUERY_UNAVAILABLE =
  'A7_PRODUCT_RECONCILIATION_QUERY_UNAVAILABLE' as const;

/**
 * A7 product reconciliation severity vocabulary (frozen by
 * `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §4.3).
 */
export const A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING = 'WARNING' as const;
export const A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR = 'ERROR' as const;

/**
 * A7 product reconciliation owner vocabulary (frozen by
 * `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §4.4).
 */
export const A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION = 'RECONCILIATION' as const;
export const A7_PRODUCT_RECONCILIATION_OWNER_FINANCE = 'FINANCE' as const;
export const A7_PRODUCT_RECONCILIATION_OWNER_SECURITY = 'SECURITY' as const;
export const A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER = 'PARTNER_OWNER' as const;
export const A7_PRODUCT_RECONCILIATION_OWNER_WALLET = 'WALLET' as const;
export const A7_PRODUCT_RECONCILIATION_OWNER_OPERATIONS = 'OPERATIONS' as const;
export const A7_PRODUCT_RECONCILIATION_OWNER_NOTIFICATION = 'NOTIFICATION' as const;
export const A7_PRODUCT_RECONCILIATION_OWNER_LIFECYCLE = 'LIFECYCLE' as const;

/**
 * A7 product reconciliation recovery state vocabulary (frozen
 * by `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §4.5).
 */
export const A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR =
  'NO_AUTOMATIC_REPAIR' as const;
export const A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED =
  'MANUAL_REVIEW_REQUIRED' as const;

/**
 * A7 product reconciliation severity, owner, and recovery-state
 * classification for each discrepancy code. The classification
 * matrix is frozen by
 * `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §4.6.
 */
export const A7_PRODUCT_RECONCILIATION_DISCREPANCY_CLASSIFICATION: Readonly<
  Record<
    string,
    {
      readonly severity:
        | typeof A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING
        | typeof A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR;
      readonly owner:
        | typeof A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION
        | typeof A7_PRODUCT_RECONCILIATION_OWNER_FINANCE
        | typeof A7_PRODUCT_RECONCILIATION_OWNER_SECURITY
        | typeof A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER
        | typeof A7_PRODUCT_RECONCILIATION_OWNER_WALLET
        | typeof A7_PRODUCT_RECONCILIATION_OWNER_OPERATIONS
        | typeof A7_PRODUCT_RECONCILIATION_OWNER_NOTIFICATION
        | typeof A7_PRODUCT_RECONCILIATION_OWNER_LIFECYCLE;
      readonly recoveryState:
        | typeof A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR
        | typeof A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED;
    }
  >
> = Object.freeze({
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_PRODUCT_OPERATION]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_PRODUCT_LIFECYCLE]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_LIFECYCLE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_PRODUCT_COMMAND]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_PRODUCT_CUSTOMER_BINDING]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A2_AUTHORIZATION]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_SECURITY,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A4_PRODUCT_POLICY_DECISION]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A5_LEDGER_JOURNAL]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_EXTERNAL_OPERATION]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_CALLBACK_RECEIPT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_SETTLEMENT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_SUSPENSE]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_PROVIDER_REFERENCE]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_NOTIFICATION_DISPATCH_FACT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_NOTIFICATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_OPERATIONS_AUDIT_FACT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_OPERATIONS,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_OPERATIONS_IDEMPOTENCY_RECORD]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_OPERATIONS,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_OPERATIONS_OUTBOX_FACT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_OPERATIONS,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_OPERATIONS_DIAGNOSTICS_FACT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_OPERATIONS,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_MISSING_A6_REPORT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_PRODUCT_OPERATION]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_PRODUCT_COMMAND]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_A6_CALLBACK_RECEIPT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_SECURITY,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_A6_SETTLEMENT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_A6_PROVIDER_REFERENCE]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_NOTIFICATION_DISPATCH_FACT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_NOTIFICATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_OPERATIONS_AUDIT_FACT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_OPERATIONS,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_DUPLICATE_OPERATIONS_OUTBOX_FACT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_OPERATIONS,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_ORPHAN_PRODUCT_OPERATION]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_ORPHAN_A6_SETTLEMENT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_ORPHAN_A6_SUSPENSE]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_ORPHAN_A6_CALLBACK_RECEIPT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_ORPHAN_NOTIFICATION_DISPATCH_FACT]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_NOTIFICATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_AMOUNT_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_CURRENCY_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_ACCOUNTING_UNIT_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_BINDING_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_WALLET,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_CAPABILITY_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_PARTNER_KEY_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_LIFECYCLE_NOT_VERIFIED]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_LIFECYCLE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_LIFECYCLE_FAILED]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_LIFECYCLE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_LIFECYCLE_CANCELLED]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_LIFECYCLE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_LIFECYCLE_TERMINAL]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_LIFECYCLE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A2_AUTHORIZATION_EXPIRED]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_SECURITY,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A4_PRODUCT_POLICY_DECISION_EXPIRED]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A4_PRODUCT_POLICY_DECISION_NOT_EXECUTABLE]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A5_LEDGER_JOURNAL_BALANCE_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A5_LEDGER_JOURNAL_CORRELATION_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A5_LEDGER_REVERSAL_ORPHAN]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A5_LEDGER_REVERSAL_DUPLICATE]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_CALLBACK_RECEIPT_AMOUNT_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_CALLBACK_RECEIPT_CURRENCY_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_CALLBACK_RECEIPT_REFERENCE_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_CALLBACK_REPLAY]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_SECURITY,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_CALLBACK_AUTHENTICITY_REJECTED]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_SECURITY,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SETTLEMENT_AMOUNT_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SETTLEMENT_CURRENCY_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SETTLEMENT_ACCOUNTING_UNIT_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SETTLEMENT_NOT_POSTED]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SUSPENSE_AMOUNT_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SUSPENSE_CURRENCY_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SUSPENSE_ACCOUNTING_UNIT_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_SUSPENSE_AGED]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_FINANCE,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_PARTNER_OUTAGE]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_REPORT_STALE]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_A6_REPORT_UNAVAILABLE]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_PARTNER_OWNER,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_NOTIFICATION_DISPATCH_AUDIENCE_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_NOTIFICATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_NOTIFICATION_DISPATCH_REDACTION_FAILED]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_SECURITY,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_NOTIFICATION_DISPATCH_DELIVERY_LIFECYCLE_BROKEN]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_NOTIFICATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_IDEMPOTENCY_HASH_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_OPERATIONS,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_OUTBOX_PAYLOAD_MISMATCH]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_ERROR,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_OPERATIONS,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_MANUAL_REVIEW_REQUIRED,
  },
  [A7_PRODUCT_RECONCILIATION_DISCREPANCY_QUERY_UNAVAILABLE]: {
    severity: A7_PRODUCT_RECONCILIATION_SEVERITY_WARNING,
    owner: A7_PRODUCT_RECONCILIATION_OWNER_RECONCILIATION,
    recoveryState: A7_PRODUCT_RECONCILIATION_RECOVERY_NO_AUTOMATIC_REPAIR,
  },
});

/**
 * A7 product reconciliation certification case vocabulary
 * (frozen by `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §4.7).
 */
export const A7_PRODUCT_RECONCILIATION_CERT_HAPPY_PATH = 'CERT_HAPPY_PATH' as const;
export const A7_PRODUCT_RECONCILIATION_CERT_REJECTION = 'CERT_REJECTION' as const;
export const A7_PRODUCT_RECONCILIATION_CERT_DUPLICATE = 'CERT_DUPLICATE' as const;
export const A7_PRODUCT_RECONCILIATION_CERT_CALLBACK_REPLAY = 'CERT_CALLBACK_REPLAY' as const;
export const A7_PRODUCT_RECONCILIATION_CERT_DELAYED_REPORT = 'CERT_DELAYED_REPORT' as const;
export const A7_PRODUCT_RECONCILIATION_CERT_OUTAGE = 'CERT_OUTAGE' as const;
export const A7_PRODUCT_RECONCILIATION_CERT_TIMEOUT = 'CERT_TIMEOUT' as const;
export const A7_PRODUCT_RECONCILIATION_CERT_SETTLEMENT_MISMATCH =
  'CERT_SETTLEMENT_MISMATCH' as const;
export const A7_PRODUCT_RECONCILIATION_CERT_SUSPENSE = 'CERT_SUSPENSE' as const;
export const A7_PRODUCT_RECONCILIATION_CERT_ROLLBACK = 'CERT_ROLLBACK' as const;

/**
 * A7 product reconciliation certification case vocabulary
 * (frozen array of all allowed certification cases).
 */
export const A7_PRODUCT_RECONCILIATION_CERT_CASES: readonly string[] = Object.freeze([
  A7_PRODUCT_RECONCILIATION_CERT_HAPPY_PATH,
  A7_PRODUCT_RECONCILIATION_CERT_REJECTION,
  A7_PRODUCT_RECONCILIATION_CERT_DUPLICATE,
  A7_PRODUCT_RECONCILIATION_CERT_CALLBACK_REPLAY,
  A7_PRODUCT_RECONCILIATION_CERT_DELAYED_REPORT,
  A7_PRODUCT_RECONCILIATION_CERT_OUTAGE,
  A7_PRODUCT_RECONCILIATION_CERT_TIMEOUT,
  A7_PRODUCT_RECONCILIATION_CERT_SETTLEMENT_MISMATCH,
  A7_PRODUCT_RECONCILIATION_CERT_SUSPENSE,
  A7_PRODUCT_RECONCILIATION_CERT_ROLLBACK,
]);

/**
 * A7 product reconciliation support-trace sensitivity vocabulary
 * (frozen by `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §4.8).
 */
export const A7_PRODUCT_RECONCILIATION_SENSITIVITY_PUBLIC = 'PUBLIC' as const;
export const A7_PRODUCT_RECONCILIATION_SENSITIVITY_INTERNAL = 'INTERNAL' as const;
export const A7_PRODUCT_RECONCILIATION_SENSITIVITY_CONFIDENTIAL = 'CONFIDENTIAL' as const;
export const A7_PRODUCT_RECONCILIATION_SENSITIVITY_RESTRICTED = 'RESTRICTED' as const;

/**
 * A7 product reconciliation handoff scope (single-use,
 * support-traceable, A2-protected internal control surface).
 */
export const A7_PRODUCT_RECONCILIATION_HANDOFF_SCOPE =
  'a7-product-reconciliation-handoff.v1' as const;

/**
 * A7 product reconciliation handoff validity interval.
 */
export const A7_PRODUCT_RECONCILIATION_HANDOFF_VALIDITY_SECONDS = 15 * 60;

/**
 * A7 product reconciliation reference prefixes (frozen by
 * `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §2.1).
 */
export const A7_PRODUCT_RECONCILIATION_REFERENCE_PREFIX = 'a7-product-reconciliation' as const;
export const A7_PRODUCT_RECONCILIATION_BATCH_REFERENCE_PREFIX =
  'a7-product-reconciliation-batch' as const;
export const A7_PRODUCT_RECONCILIATION_SUPPORT_TRACE_REFERENCE_PREFIX =
  'a7-product-support-trace' as const;
export const A7_PRODUCT_RECONCILIATION_CERTIFICATION_REFERENCE_PREFIX =
  'a7-product-certification' as const;
export const A7_PRODUCT_RECONCILIATION_HANDOFF_REFERENCE_PREFIX =
  'a7-product-reconciliation-handoff' as const;

/**
 * A6 partner identity (reused from the A6T05 partner-adapter
 * boundary).
 */
export const A7_PRODUCT_RECONCILIATION_PARTNER_KEY = NIBSS_NIP_PARTNER_KEY;
export const A7_PRODUCT_RECONCILIATION_PARTNER_CAPABILITY =
  'external.wallet.withdrawal.settlement' as const;
export const A7_PRODUCT_RECONCILIATION_PARTNER_OPERATION = 'OUTBOUND_BANK_SETTLEMENT' as const;

/**
 * A7 product reconciliation failure codes (frozen by
 * `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md`). The A7 product
 * reconciliation failure codes are used by the A7 product
 * reconciliation report to record a controlled failure when
 * the A7 product reconciliation query / evaluation / report
 * cannot complete (e.g. data source unavailable).
 */
export const A7_PRODUCT_RECONCILIATION_FAILURE_QUERY_UNAVAILABLE =
  'A7_PRODUCT_RECONCILIATION_QUERY_UNAVAILABLE' as const;
export const A7_PRODUCT_RECONCILIATION_FAILURE_INVALID_COMMAND =
  'A7_PRODUCT_RECONCILIATION_INVALID_COMMAND' as const;
export const A7_PRODUCT_RECONCILIATION_FAILURE_DISCREPANCY_DETECTED =
  'A7_PRODUCT_RECONCILIATION_DISCREPANCY_DETECTED' as const;

/**
 * A7 product reconciliation metric names (frozen by
 * `docs/A7-PRODUCT-RECONCILIATION-CONTRACT.md` §4.9). The A7
 * product reconciliation metrics are recorded through the shared
 * Operations `MetricsService` (the only metrics authority).
 */
export const A7_PRODUCT_RECONCILIATION_METRIC_PRODUCT_RECONCILED =
  'a7.product-reconciliation.product-reconciled' as const;
export const A7_PRODUCT_RECONCILIATION_METRIC_BATCH_RECONCILED =
  'a7.product-reconciliation.batch-reconciled' as const;
export const A7_PRODUCT_RECONCILIATION_METRIC_SUPPORT_TRACE_EMITTED =
  'a7.product-reconciliation.support-trace-emitted' as const;
export const A7_PRODUCT_RECONCILIATION_METRIC_CERTIFICATION_EMITTED =
  'a7.product-reconciliation.certification-emitted' as const;
export const A7_PRODUCT_RECONCILIATION_METRIC_QUERY_UNAVAILABLE =
  'a7.product-reconciliation.query-unavailable' as const;
export const A7_PRODUCT_RECONCILIATION_METRIC_NO_DISCREPANCY =
  'a7.product-reconciliation.no-discrepancy' as const;
export const A7_PRODUCT_RECONCILIATION_METRIC_DISCREPANCY_REPORTED =
  'a7.product-reconciliation.discrepancy-reported' as const;

/**
 * A7 product reconciliation product-state vocabulary (reused
 * from the A7T02 product catalog; the A7 product reconciliation
 * contract does not introduce a new A7 product state).
 */
export const A7_PRODUCT_RECONCILIATION_ASSIGN_STATES: readonly string[] = Object.freeze([
  'ASSIGN_REQUESTED',
  'ASSIGN_PENDING',
  'ASSIGN_ACTIVE',
  'ASSIGN_SUSPENDED',
  'ASSIGN_FAILED',
  'ASSIGN_CLOSED',
]);
export const A7_PRODUCT_RECONCILIATION_FUNDING_STATES: readonly string[] = Object.freeze([
  'FUNDING_REQUESTED',
  'FUNDING_PENDING_VERIFICATION',
  'FUNDING_SETTLED',
  'FUNDING_UNKNOWN',
  'FUNDING_SUSPENDED',
  'FUNDING_FAILED',
  'FUNDING_CLOSED',
]);
export const A7_PRODUCT_RECONCILIATION_ALL_STATES: readonly string[] = Object.freeze([
  ...A7_PRODUCT_RECONCILIATION_ASSIGN_STATES,
  ...A7_PRODUCT_RECONCILIATION_FUNDING_STATES,
]);

/**
 * A7 product reconciliation suspense aging threshold (24 hours;
 * aligned with the A6T09 external reconciliation suspense aging
 * threshold). The A7 product reconciliation suspense aging
 * threshold is used to classify a product-side A6T08 suspense
 * entry as `A6_SUSPENSE_AGED` if the suspense entry has been
 * `OPEN` or `HELD` for more than the threshold.
 */
export const A7_PRODUCT_RECONCILIATION_SUSPENSE_AGED_HOURS = 24;
