/**
 * B1T06 — B1 campaign engine, promotion engine, and coupon engine
 * frozen constants.
 *
 * The B1 campaign engine, promotion engine, and coupon engine is
 * the only B1 commercial-incentive engine for campaigns,
 * promotions, and coupons. The B1 campaign engine, promotion
 * engine, and coupon engine is a read-only contract against the
 * existing A1 canonical identity, A2 authorization, A3 binding,
 * A4 policy decision, A5 Ledger, A6 partner-adapter, A6T05
 * external-operation, A6T08 settlement / suspense / compensating,
 * A6T09 external reconciliation, A6T10 data classification, A7
 * product catalog, A7 product-policy profile, A7T04 product
 * customer-binding, A7T05 product command, A7T06 product
 * notification, A7T07 product lifecycle, A7T08 product financial
 * effect, A7T09 product reconciliation, A7T10 product data
 * minimization, `CustomerPreference`, Wallet, Operations, Outbox,
 * Idempotency, Metrics, Diagnostics, Reconciliation, and
 * `CustomerPreference` authorities.
 */

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * contract name (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_CONTRACT_NAME = 'B1-CAMPAIGN-ENGINE' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * contract version (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_CONTRACT_VERSION = 1 as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * contract document reference.
 */
export const B1_CAMPAIGN_ENGINE_CONTRACT_DOCUMENT = 'docs/B1-CAMPAIGN-ENGINE-CONTRACT.md' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * campaign internal idempotency scope (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_CAMPAIGN_IDEMPOTENCY_SCOPE =
  'b1.campaign-engine.campaign.idempotency.v1' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * promotion internal idempotency scope (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_PROMOTION_IDEMPOTENCY_SCOPE =
  'b1.campaign-engine.promotion.idempotency.v1' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * coupon internal idempotency scope (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_COUPON_IDEMPOTENCY_SCOPE =
  'b1.campaign-engine.coupon.idempotency.v1' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * internal idempotency retention (frozen; 24 hours, aligned with
 * the shared Operations `IdempotencyService` default).
 */
export const B1_CAMPAIGN_ENGINE_IDEMPOTENCY_RETENTION_SECONDS = 86_400 as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine audit
 * entity type (frozen).
 */
export const B1_CAMPAIGN_ENGINE_AUDIT_ENTITY_TYPE = 'B1_CAMPAIGN_DECISION' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine audit
 * actor (frozen).
 */
export const B1_CAMPAIGN_ENGINE_AUDIT_ACTOR = 'b1-campaign-engine' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine outbox
 * event type (frozen).
 */
export const B1_CAMPAIGN_ENGINE_OUTBOX_EVENT_TYPE = 'B1CampaignDecisionDecided' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine outbox
 * event classification (frozen).
 */
export const B1_CAMPAIGN_ENGINE_OUTBOX_EVENT_CLASSIFICATION = 'INTERNAL_OPERATIONS' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine outbox
 * event retention class (frozen).
 */
export const B1_CAMPAIGN_ENGINE_OUTBOX_EVENT_RETENTION_CLASS = 'OPERATIONS_DEFAULT' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * reference prefix (frozen).
 */
export const B1_CAMPAIGN_ENGINE_REFERENCE_PREFIX = 'b1-campaign-decision' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine scope
 * key (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_SCOPE_KEY = 'commercial.virtual-account.inbound-funding' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine scope
 * version (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_SCOPE_VERSION = 1 as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine scope
 * currency (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_SCOPE_CURRENCY = 'NGN' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine scope
 * accounting unit (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_SCOPE_ACCOUNTING_UNIT = 'CUSTOMER_FUNDS' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine scope
 * product dependency (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_SCOPE_PRODUCT_DEPENDENCY = 'VIRTUAL_ACCOUNT' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine scope
 * product dependency version (frozen).
 */
export const B1_CAMPAIGN_ENGINE_SCOPE_PRODUCT_DEPENDENCY_VERSION = 1 as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine scope
 * partner dependency (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_SCOPE_PARTNER_DEPENDENCY = 'NIBSS_NIP' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine scope
 * direction (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_SCOPE_DIRECTION = 'inbound' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine period
 * key (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_PERIOD_KEY =
  'commercial.virtual-account.inbound-funding.campaign-period.per-flow.v1' as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * retention days (frozen; 365 days, aligned with the B1T03
 * catalog retention).
 */
export const B1_CAMPAIGN_ENGINE_RETENTION_DAYS = 365 as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * decision kind vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_DECISION_KIND_CAMPAIGN = 'CAMPAIGN' as const;
export const B1_CAMPAIGN_ENGINE_DECISION_KIND_PROMOTION = 'PROMOTION' as const;
export const B1_CAMPAIGN_ENGINE_DECISION_KIND_COUPON = 'COUPON' as const;

export const B1_CAMPAIGN_ENGINE_DECISION_KINDS = [
  B1_CAMPAIGN_ENGINE_DECISION_KIND_CAMPAIGN,
  B1_CAMPAIGN_ENGINE_DECISION_KIND_PROMOTION,
  B1_CAMPAIGN_ENGINE_DECISION_KIND_COUPON,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * decision outcome vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_DECISION_OUTCOME_ELIGIBLE = 'ELIGIBLE' as const;
export const B1_CAMPAIGN_ENGINE_DECISION_OUTCOME_APPLIED = 'APPLIED' as const;
export const B1_CAMPAIGN_ENGINE_DECISION_OUTCOME_REJECTED = 'REJECTED' as const;
export const B1_CAMPAIGN_ENGINE_DECISION_OUTCOME_REPLAYED = 'REPLAYED' as const;

export const B1_CAMPAIGN_ENGINE_DECISION_OUTCOMES = [
  B1_CAMPAIGN_ENGINE_DECISION_OUTCOME_ELIGIBLE,
  B1_CAMPAIGN_ENGINE_DECISION_OUTCOME_APPLIED,
  B1_CAMPAIGN_ENGINE_DECISION_OUTCOME_REJECTED,
  B1_CAMPAIGN_ENGINE_DECISION_OUTCOME_REPLAYED,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * campaign state vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_CAMPAIGN_STATE_DRAFT = 'DRAFT' as const;
export const B1_CAMPAIGN_ENGINE_CAMPAIGN_STATE_ACTIVE = 'ACTIVE' as const;
export const B1_CAMPAIGN_ENGINE_CAMPAIGN_STATE_PAUSED = 'PAUSED' as const;
export const B1_CAMPAIGN_ENGINE_CAMPAIGN_STATE_EXPIRED = 'EXPIRED' as const;
export const B1_CAMPAIGN_ENGINE_CAMPAIGN_STATE_RETIRED = 'RETIRED' as const;

export const B1_CAMPAIGN_ENGINE_CAMPAIGN_STATES = [
  B1_CAMPAIGN_ENGINE_CAMPAIGN_STATE_DRAFT,
  B1_CAMPAIGN_ENGINE_CAMPAIGN_STATE_ACTIVE,
  B1_CAMPAIGN_ENGINE_CAMPAIGN_STATE_PAUSED,
  B1_CAMPAIGN_ENGINE_CAMPAIGN_STATE_EXPIRED,
  B1_CAMPAIGN_ENGINE_CAMPAIGN_STATE_RETIRED,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * promotion state vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_PROMOTION_STATE_CREATED = 'CREATED' as const;
export const B1_CAMPAIGN_ENGINE_PROMOTION_STATE_ACTIVE = 'ACTIVE' as const;
export const B1_CAMPAIGN_ENGINE_PROMOTION_STATE_EXPIRED = 'EXPIRED' as const;
export const B1_CAMPAIGN_ENGINE_PROMOTION_STATE_CANCELLED = 'CANCELLED' as const;

export const B1_CAMPAIGN_ENGINE_PROMOTION_STATES = [
  B1_CAMPAIGN_ENGINE_PROMOTION_STATE_CREATED,
  B1_CAMPAIGN_ENGINE_PROMOTION_STATE_ACTIVE,
  B1_CAMPAIGN_ENGINE_PROMOTION_STATE_EXPIRED,
  B1_CAMPAIGN_ENGINE_PROMOTION_STATE_CANCELLED,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * coupon state vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_COUPON_STATE_CREATED = 'CREATED' as const;
export const B1_CAMPAIGN_ENGINE_COUPON_STATE_ACTIVE = 'ACTIVE' as const;
export const B1_CAMPAIGN_ENGINE_COUPON_STATE_REDEEMED = 'REDEEMED' as const;
export const B1_CAMPAIGN_ENGINE_COUPON_STATE_EXPIRED = 'EXPIRED' as const;
export const B1_CAMPAIGN_ENGINE_COUPON_STATE_CANCELLED = 'CANCELLED' as const;

export const B1_CAMPAIGN_ENGINE_COUPON_STATES = [
  B1_CAMPAIGN_ENGINE_COUPON_STATE_CREATED,
  B1_CAMPAIGN_ENGINE_COUPON_STATE_ACTIVE,
  B1_CAMPAIGN_ENGINE_COUPON_STATE_REDEEMED,
  B1_CAMPAIGN_ENGINE_COUPON_STATE_EXPIRED,
  B1_CAMPAIGN_ENGINE_COUPON_STATE_CANCELLED,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * document kind vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_CAMPAIGN = 'CAMPAIGN' as const;
export const B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_CAMPAIGN_RULE = 'CAMPAIGN_RULE' as const;
export const B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_PROMOTION = 'PROMOTION' as const;
export const B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_PROMOTION_RULE = 'PROMOTION_RULE' as const;
export const B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_COUPON = 'COUPON' as const;
export const B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_COUPON_REDEMPTION = 'COUPON_REDEMPTION' as const;
export const B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_CAMPAIGN_PERIOD = 'CAMPAIGN_PERIOD' as const;
export const B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_PROMOTION_PERIOD = 'PROMOTION_PERIOD' as const;
export const B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_COUPON_PERIOD = 'COUPON_PERIOD' as const;

export const B1_CAMPAIGN_ENGINE_DOCUMENT_KINDS = [
  B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_CAMPAIGN,
  B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_CAMPAIGN_RULE,
  B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_PROMOTION,
  B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_PROMOTION_RULE,
  B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_COUPON,
  B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_COUPON_REDEMPTION,
  B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_CAMPAIGN_PERIOD,
  B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_PROMOTION_PERIOD,
  B1_CAMPAIGN_ENGINE_DOCUMENT_KIND_COUPON_PERIOD,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * priority vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_PRIORITY_LOW = 'LOW' as const;
export const B1_CAMPAIGN_ENGINE_PRIORITY_MEDIUM = 'MEDIUM' as const;
export const B1_CAMPAIGN_ENGINE_PRIORITY_HIGH = 'HIGH' as const;
export const B1_CAMPAIGN_ENGINE_PRIORITY_CRITICAL = 'CRITICAL' as const;

export const B1_CAMPAIGN_ENGINE_PRIORITIES = [
  B1_CAMPAIGN_ENGINE_PRIORITY_LOW,
  B1_CAMPAIGN_ENGINE_PRIORITY_MEDIUM,
  B1_CAMPAIGN_ENGINE_PRIORITY_HIGH,
  B1_CAMPAIGN_ENGINE_PRIORITY_CRITICAL,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * stacking rule vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_STACKING_RULE_STACKABLE = 'STACKABLE' as const;
export const B1_CAMPAIGN_ENGINE_STACKING_RULE_EXCLUSIVE = 'EXCLUSIVE' as const;
export const B1_CAMPAIGN_ENGINE_STACKING_RULE_OVERRIDABLE = 'OVERRIDABLE' as const;

export const B1_CAMPAIGN_ENGINE_STACKING_RULES = [
  B1_CAMPAIGN_ENGINE_STACKING_RULE_STACKABLE,
  B1_CAMPAIGN_ENGINE_STACKING_RULE_EXCLUSIVE,
  B1_CAMPAIGN_ENGINE_STACKING_RULE_OVERRIDABLE,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * eligibility vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_ELIGIBILITY_CUSTOMER_ELIGIBLE = 'CUSTOMER_ELIGIBLE' as const;
export const B1_CAMPAIGN_ENGINE_ELIGIBILITY_MERCHANT_ELIGIBLE = 'MERCHANT_ELIGIBLE' as const;
export const B1_CAMPAIGN_ENGINE_ELIGIBILITY_PARTNER_ELIGIBLE = 'PARTNER_ELIGIBLE' as const;
export const B1_CAMPAIGN_ENGINE_ELIGIBILITY_PRODUCT_ELIGIBLE = 'PRODUCT_ELIGIBLE' as const;
export const B1_CAMPAIGN_ENGINE_ELIGIBILITY_TIER_ELIGIBLE = 'TIER_ELIGIBLE' as const;
export const B1_CAMPAIGN_ENGINE_ELIGIBILITY_PERIOD_ELIGIBLE = 'PERIOD_ELIGIBLE' as const;
export const B1_CAMPAIGN_ENGINE_ELIGIBILITY_USAGE_LIMIT_ELIGIBLE = 'USAGE_LIMIT_ELIGIBLE' as const;

export const B1_CAMPAIGN_ENGINE_ELIGIBILITIES = [
  B1_CAMPAIGN_ENGINE_ELIGIBILITY_CUSTOMER_ELIGIBLE,
  B1_CAMPAIGN_ENGINE_ELIGIBILITY_MERCHANT_ELIGIBLE,
  B1_CAMPAIGN_ENGINE_ELIGIBILITY_PARTNER_ELIGIBLE,
  B1_CAMPAIGN_ENGINE_ELIGIBILITY_PRODUCT_ELIGIBLE,
  B1_CAMPAIGN_ENGINE_ELIGIBILITY_TIER_ELIGIBLE,
  B1_CAMPAIGN_ENGINE_ELIGIBILITY_PERIOD_ELIGIBLE,
  B1_CAMPAIGN_ENGINE_ELIGIBILITY_USAGE_LIMIT_ELIGIBLE,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * decision failure code vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_FAILURE_INVALID_COMMAND =
  'B1_CAMPAIGN_ENGINE_INVALID_COMMAND' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_INCOMPATIBLE = 'B1_CAMPAIGN_ENGINE_INCOMPATIBLE' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_QUERY_UNAVAILABLE =
  'B1_CAMPAIGN_ENGINE_QUERY_UNAVAILABLE' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_PROHIBITED = 'B1_CAMPAIGN_ENGINE_PROHIBITED' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_DECISION_NOT_FOUND =
  'B1_CAMPAIGN_ENGINE_DECISION_NOT_FOUND' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_DECISION_INCOMPATIBLE =
  'B1_CAMPAIGN_ENGINE_DECISION_INCOMPATIBLE' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_CATALOG_INCOMPATIBLE =
  'B1_CAMPAIGN_ENGINE_CATALOG_INCOMPATIBLE' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_CATALOG_MISSING =
  'B1_CAMPAIGN_ENGINE_CATALOG_MISSING' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_BILLING_DOCUMENT_NOT_FOUND =
  'B1_CAMPAIGN_ENGINE_BILLING_DOCUMENT_NOT_FOUND' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_BILLING_DOCUMENT_INCOMPATIBLE =
  'B1_CAMPAIGN_ENGINE_BILLING_DOCUMENT_INCOMPATIBLE' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_A4_POLICY_DENIED =
  'B1_CAMPAIGN_ENGINE_A4_POLICY_DENIED' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_A3_BINDING_INVALID =
  'B1_CAMPAIGN_ENGINE_A3_BINDING_INVALID' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_A5_LEDGER_INVARIANT_BROKEN =
  'B1_CAMPAIGN_ENGINE_A5_LEDGER_INVARIANT_BROKEN' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_A6_PARTNER_INCOMPATIBLE =
  'B1_CAMPAIGN_ENGINE_A6_PARTNER_INCOMPATIBLE' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_A7_PRODUCT_INCOMPATIBLE =
  'B1_CAMPAIGN_ENGINE_A7_PRODUCT_INCOMPATIBLE' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_REPLAY_CONFLICT =
  'B1_CAMPAIGN_ENGINE_REPLAY_CONFLICT' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_REPLAY_EXPIRED =
  'B1_CAMPAIGN_ENGINE_REPLAY_EXPIRED' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_IN_PROGRESS = 'B1_CAMPAIGN_ENGINE_IN_PROGRESS' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_NUMBER_CONFLICT =
  'B1_CAMPAIGN_ENGINE_NUMBER_CONFLICT' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_EXPIRED = 'B1_CAMPAIGN_ENGINE_EXPIRED' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_USAGE_LIMIT_EXCEEDED =
  'B1_CAMPAIGN_ENGINE_USAGE_LIMIT_EXCEEDED' as const;
export const B1_CAMPAIGN_ENGINE_FAILURE_NOT_APPLICABLE =
  'B1_CAMPAIGN_ENGINE_NOT_APPLICABLE' as const;

export const B1_CAMPAIGN_ENGINE_FAILURE_CODES = [
  B1_CAMPAIGN_ENGINE_FAILURE_INVALID_COMMAND,
  B1_CAMPAIGN_ENGINE_FAILURE_INCOMPATIBLE,
  B1_CAMPAIGN_ENGINE_FAILURE_QUERY_UNAVAILABLE,
  B1_CAMPAIGN_ENGINE_FAILURE_PROHIBITED,
  B1_CAMPAIGN_ENGINE_FAILURE_DECISION_NOT_FOUND,
  B1_CAMPAIGN_ENGINE_FAILURE_DECISION_INCOMPATIBLE,
  B1_CAMPAIGN_ENGINE_FAILURE_CATALOG_INCOMPATIBLE,
  B1_CAMPAIGN_ENGINE_FAILURE_CATALOG_MISSING,
  B1_CAMPAIGN_ENGINE_FAILURE_BILLING_DOCUMENT_NOT_FOUND,
  B1_CAMPAIGN_ENGINE_FAILURE_BILLING_DOCUMENT_INCOMPATIBLE,
  B1_CAMPAIGN_ENGINE_FAILURE_A4_POLICY_DENIED,
  B1_CAMPAIGN_ENGINE_FAILURE_A3_BINDING_INVALID,
  B1_CAMPAIGN_ENGINE_FAILURE_A5_LEDGER_INVARIANT_BROKEN,
  B1_CAMPAIGN_ENGINE_FAILURE_A6_PARTNER_INCOMPATIBLE,
  B1_CAMPAIGN_ENGINE_FAILURE_A7_PRODUCT_INCOMPATIBLE,
  B1_CAMPAIGN_ENGINE_FAILURE_REPLAY_CONFLICT,
  B1_CAMPAIGN_ENGINE_FAILURE_REPLAY_EXPIRED,
  B1_CAMPAIGN_ENGINE_FAILURE_IN_PROGRESS,
  B1_CAMPAIGN_ENGINE_FAILURE_NUMBER_CONFLICT,
  B1_CAMPAIGN_ENGINE_FAILURE_EXPIRED,
  B1_CAMPAIGN_ENGINE_FAILURE_USAGE_LIMIT_EXCEEDED,
  B1_CAMPAIGN_ENGINE_FAILURE_NOT_APPLICABLE,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * metric names (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_METRIC_CAMPAIGN = 'b1.campaign-engine.campaign' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_PROMOTION = 'b1.campaign-engine.promotion' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_COUPON = 'b1.campaign-engine.coupon' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_REPLAYED = 'b1.campaign-engine.replayed' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_CONFLICT = 'b1.campaign-engine.conflict' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_INCOMPATIBLE = 'b1.campaign-engine.incompatible' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_QUERY_UNAVAILABLE =
  'b1.campaign-engine.query-unavailable' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_IN_PROGRESS = 'b1.campaign-engine.in-progress' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_REPLAY_CONFLICT =
  'b1.campaign-engine.replay-conflict' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_REPLAY_EXPIRED =
  'b1.campaign-engine.replay-expired' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_NUMBER_CONFLICT =
  'b1.campaign-engine.number-conflict' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_EXPIRED = 'b1.campaign-engine.expired' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_USAGE_LIMIT_EXCEEDED =
  'b1.campaign-engine.usage-limit-exceeded' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_NOT_APPLICABLE =
  'b1.campaign-engine.not-applicable' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_A4_POLICY_DENIED =
  'b1.campaign-engine.a4-policy-denied' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_A3_BINDING_INVALID =
  'b1.campaign-engine.a3-binding-invalid' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_A5_LEDGER_INVARIANT_BROKEN =
  'b1.campaign-engine.a5-ledger-invariant-broken' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_A6_PARTNER_INCOMPATIBLE =
  'b1.campaign-engine.a6-partner-incompatible' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_A7_PRODUCT_INCOMPATIBLE =
  'b1.campaign-engine.a7-product-incompatible' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_CATALOG_INCOMPATIBLE =
  'b1.campaign-engine.catalog-incompatible' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_CATALOG_MISSING =
  'b1.campaign-engine.catalog-missing' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_DECISION_NOT_FOUND =
  'b1.campaign-engine.decision-not-found' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_DECISION_INCOMPATIBLE =
  'b1.campaign-engine.decision-incompatible' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_BILLING_DOCUMENT_NOT_FOUND =
  'b1.campaign-engine.billing-document-not-found' as const;
export const B1_CAMPAIGN_ENGINE_METRIC_BILLING_DOCUMENT_INCOMPATIBLE =
  'b1.campaign-engine.billing-document-incompatible' as const;

export const B1_CAMPAIGN_ENGINE_METRICS = [
  B1_CAMPAIGN_ENGINE_METRIC_CAMPAIGN,
  B1_CAMPAIGN_ENGINE_METRIC_PROMOTION,
  B1_CAMPAIGN_ENGINE_METRIC_COUPON,
  B1_CAMPAIGN_ENGINE_METRIC_REPLAYED,
  B1_CAMPAIGN_ENGINE_METRIC_CONFLICT,
  B1_CAMPAIGN_ENGINE_METRIC_INCOMPATIBLE,
  B1_CAMPAIGN_ENGINE_METRIC_QUERY_UNAVAILABLE,
  B1_CAMPAIGN_ENGINE_METRIC_IN_PROGRESS,
  B1_CAMPAIGN_ENGINE_METRIC_REPLAY_CONFLICT,
  B1_CAMPAIGN_ENGINE_METRIC_REPLAY_EXPIRED,
  B1_CAMPAIGN_ENGINE_METRIC_NUMBER_CONFLICT,
  B1_CAMPAIGN_ENGINE_METRIC_EXPIRED,
  B1_CAMPAIGN_ENGINE_METRIC_USAGE_LIMIT_EXCEEDED,
  B1_CAMPAIGN_ENGINE_METRIC_NOT_APPLICABLE,
  B1_CAMPAIGN_ENGINE_METRIC_A4_POLICY_DENIED,
  B1_CAMPAIGN_ENGINE_METRIC_A3_BINDING_INVALID,
  B1_CAMPAIGN_ENGINE_METRIC_A5_LEDGER_INVARIANT_BROKEN,
  B1_CAMPAIGN_ENGINE_METRIC_A6_PARTNER_INCOMPATIBLE,
  B1_CAMPAIGN_ENGINE_METRIC_A7_PRODUCT_INCOMPATIBLE,
  B1_CAMPAIGN_ENGINE_METRIC_CATALOG_INCOMPATIBLE,
  B1_CAMPAIGN_ENGINE_METRIC_CATALOG_MISSING,
  B1_CAMPAIGN_ENGINE_METRIC_DECISION_NOT_FOUND,
  B1_CAMPAIGN_ENGINE_METRIC_DECISION_INCOMPATIBLE,
  B1_CAMPAIGN_ENGINE_METRIC_BILLING_DOCUMENT_NOT_FOUND,
  B1_CAMPAIGN_ENGINE_METRIC_BILLING_DOCUMENT_INCOMPATIBLE,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * classification level vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_CLASSIFICATION_LEVELS = [
  'PUBLIC',
  'INTERNAL',
  'CONFIDENTIAL',
  'RESTRICTED',
  'HIGHLY_RESTRICTED',
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * data control classifications (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_DATA_CONTROL_CLASSIFICATIONS = [
  'PUBLIC',
  'INTERNAL',
  'CONFIDENTIAL',
  'RESTRICTED',
  'HIGHLY_RESTRICTED',
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * rule kind vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A3_BINDING_RECHECK = 'A3_BINDING_RECHECK' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A4_POLICY_CURRENTNESS = 'A4_POLICY_CURRENTNESS' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A4_POLICY_OBLIGATION = 'A4_POLICY_OBLIGATION' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A4_POLICY_REEVALUATION =
  'A4_POLICY_REEVALUATION' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A4_POLICY_LIMIT = 'A4_POLICY_LIMIT' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A5_LEDGER_ACCOUNT_STATE =
  'A5_LEDGER_ACCOUNT_STATE' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A5_LEDGER_POSTING_BOUNDARY =
  'A5_LEDGER_POSTING_BOUNDARY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A5_FINANCIAL_INVARIANTS =
  'A5_FINANCIAL_INVARIANTS' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A6_PARTNER_STATE = 'A6_PARTNER_STATE' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A6_PARTNER_CAPABILITY_VERSION =
  'A6_PARTNER_CAPABILITY_VERSION' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A6T08_SETTLEMENT_SUSPENSE_COMPENSATING =
  'A6T08_SETTLEMENT_SUSPENSE_COMPENSATING' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A6T09_EXTERNAL_RECONCILIATION =
  'A6T09_EXTERNAL_RECONCILIATION' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A7_PRODUCT_CATALOG = 'A7_PRODUCT_CATALOG' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A7_PRODUCT_BOUNDARY = 'A7_PRODUCT_BOUNDARY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A7T04_PRODUCT_CUSTOMER_BINDING =
  'A7T04_PRODUCT_CUSTOMER_BINDING' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A7T05_PRODUCT_COMMAND_OPERATION =
  'A7T05_PRODUCT_COMMAND_OPERATION' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A7T06_PRODUCT_NOTIFICATION =
  'A7T06_PRODUCT_NOTIFICATION' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A7T07_PRODUCT_LIFECYCLE =
  'A7T07_PRODUCT_LIFECYCLE' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A7T08_PRODUCT_FINANCIAL_EFFECT =
  'A7T08_PRODUCT_FINANCIAL_EFFECT' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A7T09_PRODUCT_RECONCILIATION =
  'A7T09_PRODUCT_RECONCILIATION' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_A7T10_PRODUCT_DATA_MINIMIZATION =
  'A7T10_PRODUCT_DATA_MINIMIZATION' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_LOOKUP =
  'B1_COMMERCIAL_CATALOG_LOOKUP' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_COMPATIBILITY =
  'B1_COMMERCIAL_CATALOG_COMPATIBILITY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PLAN =
  'B1_COMMERCIAL_CATALOG_PLAN' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_TIER =
  'B1_COMMERCIAL_CATALOG_TIER' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_ENTITLEMENT =
  'B1_COMMERCIAL_CATALOG_ENTITLEMENT' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PACKAGE =
  'B1_COMMERCIAL_CATALOG_PACKAGE' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_BUNDLE =
  'B1_COMMERCIAL_CATALOG_BUNDLE' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_SUBSCRIPTION =
  'B1_COMMERCIAL_CATALOG_SUBSCRIPTION' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_FEATURE_FLAG =
  'B1_COMMERCIAL_CATALOG_FEATURE_FLAG' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT =
  'B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PRICING =
  'B1_COMMERCIAL_CATALOG_PRICING' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_LOOKUP =
  'B1_COMMERCIAL_DECISION_LOOKUP' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_COMPATIBILITY =
  'B1_COMMERCIAL_DECISION_COMPATIBILITY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_REPLAY =
  'B1_COMMERCIAL_DECISION_REPLAY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_LOOKUP =
  'B1_BILLING_ENGINE_DOCUMENT_LOOKUP' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_COMPATIBILITY =
  'B1_BILLING_ENGINE_DOCUMENT_COMPATIBILITY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_REPLAY =
  'B1_BILLING_ENGINE_DOCUMENT_REPLAY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_CUSTOMER_ELIGIBILITY =
  'B1_CAMPAIGN_ENGINE_CUSTOMER_ELIGIBILITY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_MERCHANT_ELIGIBILITY =
  'B1_CAMPAIGN_ENGINE_MERCHANT_ELIGIBILITY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_PARTNER_ELIGIBILITY =
  'B1_CAMPAIGN_ENGINE_PARTNER_ELIGIBILITY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_PRODUCT_ELIGIBILITY =
  'B1_CAMPAIGN_ENGINE_PRODUCT_ELIGIBILITY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_ACTIVATION_RULES =
  'B1_CAMPAIGN_ENGINE_ACTIVATION_RULES' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_PRIORITY =
  'B1_CAMPAIGN_ENGINE_PRIORITY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_STACKING_RULES =
  'B1_CAMPAIGN_ENGINE_STACKING_RULES' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_EXCLUSIVITY_RULES =
  'B1_CAMPAIGN_ENGINE_EXCLUSIVITY_RULES' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_EXPIRATION =
  'B1_CAMPAIGN_ENGINE_EXPIRATION' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_USAGE_LIMITS =
  'B1_CAMPAIGN_ENGINE_USAGE_LIMITS' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_REPLAY_ELIGIBILITY =
  'B1_CAMPAIGN_ENGINE_REPLAY_ELIGIBILITY' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_NUMBER_DETERMINISTIC =
  'B1_CAMPAIGN_ENGINE_NUMBER_DETERMINISTIC' as const;
export const B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_DOCUMENT_VERSION =
  'B1_CAMPAIGN_ENGINE_DOCUMENT_VERSION' as const;

export const B1_CAMPAIGN_ENGINE_RULE_KINDS = [
  B1_CAMPAIGN_ENGINE_RULE_KIND_A4_POLICY_LIMIT,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A4_POLICY_OBLIGATION,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A4_POLICY_CURRENTNESS,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A4_POLICY_REEVALUATION,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A3_BINDING_RECHECK,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A5_LEDGER_ACCOUNT_STATE,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A5_LEDGER_POSTING_BOUNDARY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A5_FINANCIAL_INVARIANTS,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A6_PARTNER_STATE,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A6_PARTNER_CAPABILITY_VERSION,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A6T08_SETTLEMENT_SUSPENSE_COMPENSATING,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A6T09_EXTERNAL_RECONCILIATION,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A7_PRODUCT_CATALOG,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A7_PRODUCT_BOUNDARY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A7T04_PRODUCT_CUSTOMER_BINDING,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A7T05_PRODUCT_COMMAND_OPERATION,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A7T06_PRODUCT_NOTIFICATION,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A7T07_PRODUCT_LIFECYCLE,
  B1_CAMPAIGN_ENGINE_RULE_KIND_A7T08_PRODUCT_FINANCIAL_EFFECT,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_LOOKUP,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_COMPATIBILITY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PLAN,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_TIER,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_ENTITLEMENT,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PACKAGE,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_BUNDLE,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_SUBSCRIPTION,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_FEATURE_FLAG,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PRICING,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_LOOKUP,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_COMPATIBILITY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_REPLAY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_LOOKUP,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_COMPATIBILITY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_REPLAY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_CUSTOMER_ELIGIBILITY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_MERCHANT_ELIGIBILITY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_PARTNER_ELIGIBILITY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_PRODUCT_ELIGIBILITY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_ACTIVATION_RULES,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_PRIORITY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_STACKING_RULES,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_EXCLUSIVITY_RULES,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_EXPIRATION,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_USAGE_LIMITS,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_REPLAY_ELIGIBILITY,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_NUMBER_DETERMINISTIC,
  B1_CAMPAIGN_ENGINE_RULE_KIND_B1_CAMPAIGN_ENGINE_DOCUMENT_VERSION,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * rule outcome vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_RULE_OUTCOME_PASS = 'PASS' as const;
export const B1_CAMPAIGN_ENGINE_RULE_OUTCOME_FAIL = 'FAIL' as const;
export const B1_CAMPAIGN_ENGINE_RULE_OUTCOME_SKIP = 'SKIP' as const;
export const B1_CAMPAIGN_ENGINE_RULE_OUTCOME_NOT_APPLICABLE = 'NOT_APPLICABLE' as const;

export const B1_CAMPAIGN_ENGINE_RULE_OUTCOMES = [
  B1_CAMPAIGN_ENGINE_RULE_OUTCOME_PASS,
  B1_CAMPAIGN_ENGINE_RULE_OUTCOME_FAIL,
  B1_CAMPAIGN_ENGINE_RULE_OUTCOME_SKIP,
  B1_CAMPAIGN_ENGINE_RULE_OUTCOME_NOT_APPLICABLE,
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * compatibility rule identifiers (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_COMPATIBILITY_RULE_IDS = [
  'B1_CAMPAIGN_RULE_SCOPE_KEY_REQUIRED',
  'B1_CAMPAIGN_RULE_SCOPE_VERSION_REQUIRED',
  'B1_CAMPAIGN_RULE_CURRENCY_REQUIRED',
  'B1_CAMPAIGN_RULE_ACCOUNTING_UNIT_REQUIRED',
  'B1_CAMPAIGN_RULE_PRODUCT_DEPENDENCY_REQUIRED',
  'B1_CAMPAIGN_RULE_PARTNER_DEPENDENCY_REQUIRED',
  'B1_CAMPAIGN_RULE_DOCUMENT_VERSION_REQUIRED',
  'B1_CAMPAIGN_RULE_DECISION_REFERENCES_REQUIRED',
  'B1_CAMPAIGN_RULE_BILLING_DOCUMENT_REFERENCE_REQUIRED',
  'B1_CAMPAIGN_RULE_NUMBER_DETERMINISTIC',
  'B1_CAMPAIGN_RULE_NO_CROSS_CATALOG_REFERENCES',
  'B1_CAMPAIGN_RULE_NO_CROSS_SCOPE_NEGOTIATION',
  'B1_CAMPAIGN_RULE_PERIOD_VERSION_REQUIRED',
  'B1_CAMPAIGN_RULE_STACKING_RULES_VALID',
  'B1_CAMPAIGN_RULE_EXCLUSIVITY_RULES_VALID',
  'B1_CAMPAIGN_RULE_USAGE_LIMITS_VALID',
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * consumer contract identifiers (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_CONSUMER_CONTRACT_IDS = [
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A1',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A2',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A3',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A4',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A5',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A6',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A7',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A6T10',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A6T09',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A7T09',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A7T08',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_A7T06',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_B1_COMMERCIAL_CATALOG',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_B1_COMMERCIAL_DECISION',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_B1_BILLING_ENGINE',
  'B1_CAMPAIGN_CONSUMER_CONTRACT_OPERATIONS',
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * version negotiation rule identifiers (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_VERSION_NEGOTIATION_RULE_IDS = [
  'B1_CAMPAIGN_VERSION_RULE_SCOPE_VERSION_EXACT_MATCH',
  'B1_CAMPAIGN_VERSION_RULE_DOCUMENT_VERSION_EXACT_MATCH',
  'B1_CAMPAIGN_VERSION_RULE_PERIOD_VERSION_EXACT_MATCH',
  'B1_CAMPAIGN_VERSION_RULE_NO_CROSS_CATALOG_NEGOTIATION',
  'B1_CAMPAIGN_VERSION_RULE_NO_CROSS_BILLING_ENGINE_NEGOTIATION',
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * replay rule identifiers (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_REPLAY_RULE_IDS = [
  'B1_CAMPAIGN_REPLAY_RULE_WINDOW_86400',
  'B1_CAMPAIGN_REPLAY_RULE_EXACT_MATCH_REQUIRED',
  'B1_CAMPAIGN_REPLAY_RULE_IDEMPOTENT',
  'B1_CAMPAIGN_REPLAY_RULE_AUDIT_TRACED',
  'B1_CAMPAIGN_REPLAY_RULE_EXPIRES_AFTER_WINDOW',
  'B1_CAMPAIGN_REPLAY_RULE_INHERITS_A1_A7',
  'B1_CAMPAIGN_REPLAY_RULE_INHERITS_B1T03',
  'B1_CAMPAIGN_REPLAY_RULE_INHERITS_B1T04',
  'B1_CAMPAIGN_REPLAY_RULE_INHERITS_B1T05',
  'B1_CAMPAIGN_REPLAY_RULE_NUMBER_DETERMINISTIC',
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * declared dependencies (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_DECLARED_DEPENDENCIES = [
  'A1-CANONICAL-IDENTITY',
  'A2-AUTHORIZATION-CONTEXT',
  'A3-CUSTOMER-FINANCIAL-ACCOUNT-BINDING',
  'A4-PRODUCT-POLICY-DECISION',
  'A5-LEDGER',
  'A6-PARTNER-ADAPTER',
  'A6T05-EXTERNAL-OPERATION',
  'A6T08-SETTLEMENT-SUSPENSE-COMPENSATING',
  'A6T09-EXTERNAL-RECONCILIATION',
  'A6T10-DATA-CLASSIFICATION',
  'A7-PRODUCT-CATALOG',
  'A7-PRODUCT-POLICY-PROFILE',
  'A7T04-PRODUCT-CUSTOMER-BINDING',
  'A7T05-PRODUCT-COMMAND-OPERATION',
  'A7T06-PRODUCT-NOTIFICATION-DELIVERY',
  'A7T07-PRODUCT-LIFECYCLE',
  'A7T08-PRODUCT-FINANCIAL-EFFECT',
  'A7T09-PRODUCT-RECONCILIATION',
  'A7T10-PRODUCT-DATA-MINIMIZATION',
  'B1-COMMERCIAL-CATALOG',
  'B1-COMMERCIAL-DECISION',
  'B1-BILLING-ENGINE',
  'CUSTOMER-PREFERENCE',
  'OPERATIONS-AUDIT',
  'OPERATIONS-IDEMPOTENCY',
  'OPERATIONS-OUTBOX',
  'OPERATIONS-METRICS',
  'OPERATIONS-DIAGNOSTICS',
  'WALLET',
  'LEDGER',
  'RECONCILIATION',
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * prohibited dependencies (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06).
 */
export const B1_CAMPAIGN_ENGINE_PROHIBITED_DEPENDENCIES = [
  'B1_REFERRAL_ENGINE',
  'B1_CASHBACK_ENGINE',
  'B1_LOYALTY_ENGINE',
  'B1_REVENUE_RECOGNITION_ENGINE',
  'B1_TAX_ENGINE',
  'B1_COST_ACCOUNTING_ENGINE',
  'B1_PROFITABILITY_ENGINE',
  'B1_ANALYTICS_ENGINE',
  'B1_COMMERCIAL_RECONCILIATION_ENGINE',
  'B1_COMMERCIAL_DATA_CLASSIFICATION_REGISTRY',
  'B1_COMMERCIAL_IDEMPOTENCY_AUTHORITY',
  'B1_COMMERCIAL_AUDIT_AUTHORITY',
  'B1_COMMERCIAL_APPROVAL_AUTHORITY',
  'B1_COMMERCIAL_FEATURE_FLAG_AUTHORITY',
  'B1_COMMERCIAL_RELEASE_GATE',
  'A5_LEDGER_POSTING_AUTHORITY',
  'A5_LEDGER_JOURNAL_AUTHORITY',
  'A5_FINANCIAL_INVARIANTS_OVERRIDE_AUTHORITY',
  'A6T08_SETTLEMENT_AUTHORITY',
  'A6T08_SUSPENSE_AUTHORITY',
  'A6T08_COMPENSATING_AUTHORITY',
  'A6T09_RECONCILIATION_AUTHORITY',
  'A7T06_NOTIFICATION_DISPATCH_AUTHORITY',
  'A7T08_PRODUCT_FINANCIAL_EFFECT_AUTHORITY',
] as const;

/**
 * B1 campaign engine, promotion engine, and coupon engine
 * prohibited adjacent scopes (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T06 and re-asserted from
 * the B1T03 catalog).
 */
export const B1_CAMPAIGN_ENGINE_PROHIBITED_ADJACENT_SCOPES = [
  'commercial.virtual-account.outbound-settlement',
  'commercial.savings.inbound-funding',
  'commercial.lending.inbound-funding',
  'commercial.bills.inbound-funding',
  'commercial.airtime.inbound-funding',
  'commercial.qr-merchant.inbound-funding',
  'commercial.agent-assisted.inbound-funding',
  'commercial.card.inbound-funding',
  'commercial.bulk-payroll.inbound-funding',
  'commercial.fx.inbound-funding',
  'commercial.cross-region.inbound-funding',
  'commercial.cross-currency.inbound-funding',
  'commercial.public-channel.inbound-funding',
  'commercial.marketing-consent.inbound-funding',
] as const;
