/**
 * B1T08 — B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine frozen constants.
 *
 * The B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine is the only B1 commercial-financial-
 * recognition engine for revenue recognition, tax / VAT, and
 * cost accounting. The B1 revenue-recognition engine, tax / VAT
 * engine, and cost-accounting engine is a read-only contract
 * against the existing A1 canonical identity, A2 authorization,
 * A3 binding, A4 policy decision, A5 Ledger, A6 partner-adapter,
 * A6T05 external-operation, A6T08 settlement / suspense /
 * compensating, A6T09 external reconciliation, A6T10 data
 * classification, A7 product catalog, A7 product-policy profile,
 * A7T04 product customer-binding, A7T05 product command, A7T06
 * product notification, A7T07 product lifecycle, A7T08 product
 * financial effect, A7T09 product reconciliation, A7T10 product
 * data minimization, `CustomerPreference`, Wallet, Operations,
 * Outbox, Idempotency, Metrics, Diagnostics, Reconciliation, and
 * `CustomerPreference` authorities.
 */

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine contract name (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_CONTRACT_NAME = 'B1-REVENUE-RECOGNITION-ENGINE' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine contract version (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_CONTRACT_VERSION = 1 as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine contract document reference.
 */
export const B1_REVENUE_RECOGNITION_ENGINE_CONTRACT_DOCUMENT =
  'docs/B1-REVENUE-RECOGNITION-CONTRACT.md' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine revenue-recognition internal
 * idempotency scope (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_IDEMPOTENCY_SCOPE =
  'b1.revenue-recognition-engine.revenue-recognition.idempotency.v1' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine tax / VAT internal idempotency scope
 * (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_IDEMPOTENCY_SCOPE =
  'b1.revenue-recognition-engine.tax-vat.idempotency.v1' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine cost-accounting internal idempotency
 * scope (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_IDEMPOTENCY_SCOPE =
  'b1.revenue-recognition-engine.cost-accounting.idempotency.v1' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine internal idempotency retention
 * (frozen; 24 hours, aligned with the shared Operations
 * `IdempotencyService` default).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_IDEMPOTENCY_RETENTION_SECONDS = 86_400 as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine audit entity type (frozen).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_AUDIT_ENTITY_TYPE =
  'B1_REVENUE_RECOGNITION_DECISION' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine audit actor (frozen).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_AUDIT_ACTOR = 'b1-revenue-recognition-engine' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine outbox event type (frozen).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_OUTBOX_EVENT_TYPE =
  'B1RevenueRecognitionDecisionDecided' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine outbox event classification (frozen).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_OUTBOX_EVENT_CLASSIFICATION =
  'INTERNAL_OPERATIONS' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine outbox event retention class (frozen).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_OUTBOX_EVENT_RETENTION_CLASS =
  'OPERATIONS_DEFAULT' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine reference prefix (frozen).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_REFERENCE_PREFIX =
  'b1-revenue-recognition-decision' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine scope key (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_SCOPE_KEY =
  'commercial.virtual-account.inbound-funding' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine scope version (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_SCOPE_VERSION = 1 as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine scope currency (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_SCOPE_CURRENCY = 'NGN' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine scope accounting unit (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_SCOPE_ACCOUNTING_UNIT = 'CUSTOMER_FUNDS' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine scope product dependency (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_SCOPE_PRODUCT_DEPENDENCY = 'VIRTUAL_ACCOUNT' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine scope product dependency version
 * (frozen).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_SCOPE_PRODUCT_DEPENDENCY_VERSION = 1 as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine scope partner dependency (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_SCOPE_PARTNER_DEPENDENCY = 'NIBSS_NIP' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine scope direction (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_SCOPE_DIRECTION = 'inbound' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine period key (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_PERIOD_KEY =
  'commercial.virtual-account.inbound-funding.revenue-recognition-period.per-flow.v1' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine retention days (frozen; 365 days,
 * aligned with the B1T03 catalog retention).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_RETENTION_DAYS = 365 as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine accounting basis vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASIS_CASH = 'CASH_BASIS' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASIS_ACCRUAL = 'ACCRUAL_BASIS' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASIS_MODIFIED_ACCRUAL =
  'MODIFIED_ACCRUAL_BASIS' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASIS_REVENUE_RECOGNITION =
  'REVENUE_RECOGNITION_BASIS' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASES = [
  B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASIS_CASH,
  B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASIS_ACCRUAL,
  B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASIS_MODIFIED_ACCRUAL,
  B1_REVENUE_RECOGNITION_ENGINE_ACCOUNTING_BASIS_REVENUE_RECOGNITION,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine decision kind vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_DECISION_KIND_REVENUE_RECOGNITION =
  'REVENUE_RECOGNITION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DECISION_KIND_TAX_VAT = 'TAX_VAT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DECISION_KIND_COST_ACCOUNTING =
  'COST_ACCOUNTING' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_DECISION_KINDS = [
  B1_REVENUE_RECOGNITION_ENGINE_DECISION_KIND_REVENUE_RECOGNITION,
  B1_REVENUE_RECOGNITION_ENGINE_DECISION_KIND_TAX_VAT,
  B1_REVENUE_RECOGNITION_ENGINE_DECISION_KIND_COST_ACCOUNTING,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine decision outcome vocabulary (frozen
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOME_ELIGIBLE = 'ELIGIBLE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOME_APPLIED = 'APPLIED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOME_REJECTED = 'REJECTED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOME_REPLAYED = 'REPLAYED' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOMES = [
  B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOME_ELIGIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOME_APPLIED,
  B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOME_REJECTED,
  B1_REVENUE_RECOGNITION_ENGINE_DECISION_OUTCOME_REPLAYED,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine revenue-recognition state vocabulary
 * (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_DRAFT = 'DRAFT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_PENDING = 'PENDING' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_RECOGNIZED =
  'RECOGNIZED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_DEFERRED = 'DEFERRED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_CANCELLED =
  'CANCELLED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_RETIRED = 'RETIRED' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATES = [
  B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_DRAFT,
  B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_PENDING,
  B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_RECOGNIZED,
  B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_DEFERRED,
  B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_CANCELLED,
  B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_STATE_RETIRED,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine tax / VAT state vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_DRAFT = 'DRAFT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_PENDING = 'PENDING' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_ASSESSED = 'ASSESSED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_EXEMPTED = 'EXEMPTED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_DECLARED = 'DECLARED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_CANCELLED = 'CANCELLED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_RETIRED = 'RETIRED' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATES = [
  B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_DRAFT,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_PENDING,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_ASSESSED,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_EXEMPTED,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_DECLARED,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_CANCELLED,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_STATE_RETIRED,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine cost-accounting state vocabulary
 * (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_DRAFT = 'DRAFT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_PENDING = 'PENDING' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_ALLOCATED = 'ALLOCATED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_RECOGNIZED = 'RECOGNIZED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_AMORTIZED = 'AMORTIZED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_CANCELLED = 'CANCELLED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_RETIRED = 'RETIRED' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATES = [
  B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_DRAFT,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_PENDING,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_ALLOCATED,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_RECOGNIZED,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_AMORTIZED,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_CANCELLED,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_STATE_RETIRED,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine document kind vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_REVENUE_RECOGNITION =
  'REVENUE_RECOGNITION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_REVENUE_RECOGNITION_POLICY =
  'REVENUE_RECOGNITION_POLICY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_REVENUE_RECOGNITION_SCHEDULE =
  'REVENUE_RECOGNITION_SCHEDULE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_REVENUE_RECOGNITION_EVENT =
  'REVENUE_RECOGNITION_EVENT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_DEFERRED_REVENUE =
  'DEFERRED_REVENUE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_RECOGNIZED_REVENUE =
  'RECOGNIZED_REVENUE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_VAT = 'TAX_VAT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_VAT_POLICY = 'TAX_VAT_POLICY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_JURISDICTION =
  'TAX_JURISDICTION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_CATEGORY = 'TAX_CATEGORY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_EXEMPTION = 'TAX_EXEMPTION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_DECISION = 'TAX_DECISION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_EVIDENCE = 'TAX_EVIDENCE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_COST_ACCOUNTING =
  'COST_ACCOUNTING' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_COST_ACCOUNTING_POLICY =
  'COST_ACCOUNTING_POLICY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_DIRECT_COST = 'DIRECT_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_INDIRECT_COST = 'INDIRECT_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_ACQUISITION_COST =
  'ACQUISITION_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_OPERATIONAL_COST =
  'OPERATIONAL_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_ALLOCATED_COST = 'ALLOCATED_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_COST_CATEGORY = 'COST_CATEGORY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_COST_DECISION = 'COST_DECISION' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KINDS = [
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_REVENUE_RECOGNITION,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_REVENUE_RECOGNITION_POLICY,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_REVENUE_RECOGNITION_SCHEDULE,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_REVENUE_RECOGNITION_EVENT,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_DEFERRED_REVENUE,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_RECOGNIZED_REVENUE,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_VAT,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_VAT_POLICY,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_JURISDICTION,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_CATEGORY,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_EXEMPTION,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_DECISION,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_TAX_EVIDENCE,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_COST_ACCOUNTING,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_COST_ACCOUNTING_POLICY,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_DIRECT_COST,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_INDIRECT_COST,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_ACQUISITION_COST,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_OPERATIONAL_COST,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_ALLOCATED_COST,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_COST_CATEGORY,
  B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_KIND_COST_DECISION,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine recognition method vocabulary
 * (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_POINT_IN_TIME =
  'POINT_IN_TIME' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_OVER_TIME = 'OVER_TIME' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_MILESTONE_BASED =
  'MILESTONE_BASED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_PERCENTAGE_OF_COMPLETION =
  'PERCENTAGE_OF_COMPLETION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_INSTALLMENT = 'INSTALLMENT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_DEFERRED = 'DEFERRED' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHODS = [
  B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_POINT_IN_TIME,
  B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_OVER_TIME,
  B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_MILESTONE_BASED,
  B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_PERCENTAGE_OF_COMPLETION,
  B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_INSTALLMENT,
  B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_METHOD_DEFERRED,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine tax category vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_VAT = 'VAT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_SALES_TAX = 'SALES_TAX' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_WITHHOLDING_TAX =
  'WITHHOLDING_TAX' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_SERVICE_TAX = 'SERVICE_TAX' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_EXCISE_TAX = 'EXCISE_TAX' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_EXEMPT = 'EXEMPT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_ZERO_RATED = 'ZERO_RATED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_OUT_OF_SCOPE = 'OUT_OF_SCOPE' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORIES = [
  B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_VAT,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_SALES_TAX,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_WITHHOLDING_TAX,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_SERVICE_TAX,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_EXCISE_TAX,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_EXEMPT,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_ZERO_RATED,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY_OUT_OF_SCOPE,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine tax jurisdiction vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_NIGERIA_FEDERAL =
  'NIGERIA_FEDERAL' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_NIGERIA_STATE =
  'NIGERIA_STATE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_NIGERIA_LGA = 'NIGERIA_LGA' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_WEST_AFRICA_REGION =
  'WEST_AFRICA_REGION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_AFRICA_REGION =
  'AFRICA_REGION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_GLOBAL = 'GLOBAL' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTIONS = [
  B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_NIGERIA_FEDERAL,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_NIGERIA_STATE,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_NIGERIA_LGA,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_WEST_AFRICA_REGION,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_AFRICA_REGION,
  B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_GLOBAL,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine cost category vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_DIRECT_COST = 'DIRECT_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_INDIRECT_COST = 'INDIRECT_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_ACQUISITION_COST =
  'ACQUISITION_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_OPERATIONAL_COST =
  'OPERATIONAL_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_ALLOCATED_COST = 'ALLOCATED_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_OVERHEAD_COST = 'OVERHEAD_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_SUPPORT_COST = 'SUPPORT_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_CAPITALIZED_COST =
  'CAPITALIZED_COST' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORIES = [
  B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_DIRECT_COST,
  B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_INDIRECT_COST,
  B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_ACQUISITION_COST,
  B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_OPERATIONAL_COST,
  B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_ALLOCATED_COST,
  B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_OVERHEAD_COST,
  B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_SUPPORT_COST,
  B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY_CAPITALIZED_COST,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine cost allocation method vocabulary
 * (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_DIRECT =
  'DIRECT_ALLOCATION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_STEP = 'STEP_ALLOCATION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_RECIPROCAL =
  'RECIPROCAL_ALLOCATION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_PROPORTIONAL =
  'PROPORTIONAL_ALLOCATION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_ACTIVITY_BASED =
  'ACTIVITY_BASED_COSTING' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_STANDARD =
  'STANDARD_COSTING' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHODS = [
  B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_DIRECT,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_STEP,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_RECIPROCAL,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_PROPORTIONAL,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_ACTIVITY_BASED,
  B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_METHOD_STANDARD,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine decision failure code vocabulary
 * (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_INVALID_COMMAND =
  'B1_REVENUE_RECOGNITION_ENGINE_INVALID_COMMAND' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_INCOMPATIBLE =
  'B1_REVENUE_RECOGNITION_ENGINE_INCOMPATIBLE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_QUERY_UNAVAILABLE =
  'B1_REVENUE_RECOGNITION_ENGINE_QUERY_UNAVAILABLE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_PROHIBITED =
  'B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_DECISION_NOT_FOUND =
  'B1_REVENUE_RECOGNITION_ENGINE_DECISION_NOT_FOUND' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_DECISION_INCOMPATIBLE =
  'B1_REVENUE_RECOGNITION_ENGINE_DECISION_INCOMPATIBLE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_CATALOG_INCOMPATIBLE =
  'B1_REVENUE_RECOGNITION_ENGINE_CATALOG_INCOMPATIBLE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_CATALOG_MISSING =
  'B1_REVENUE_RECOGNITION_ENGINE_CATALOG_MISSING' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_BILLING_DOCUMENT_NOT_FOUND =
  'B1_REVENUE_RECOGNITION_ENGINE_BILLING_DOCUMENT_NOT_FOUND' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_BILLING_DOCUMENT_INCOMPATIBLE =
  'B1_REVENUE_RECOGNITION_ENGINE_BILLING_DOCUMENT_INCOMPATIBLE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_A4_POLICY_DENIED =
  'B1_REVENUE_RECOGNITION_ENGINE_A4_POLICY_DENIED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_A3_BINDING_INVALID =
  'B1_REVENUE_RECOGNITION_ENGINE_A3_BINDING_INVALID' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_A5_LEDGER_INVARIANT_BROKEN =
  'B1_REVENUE_RECOGNITION_ENGINE_A5_LEDGER_INVARIANT_BROKEN' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_A6_PARTNER_INCOMPATIBLE =
  'B1_REVENUE_RECOGNITION_ENGINE_A6_PARTNER_INCOMPATIBLE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_A7_PRODUCT_INCOMPATIBLE =
  'B1_REVENUE_RECOGNITION_ENGINE_A7_PRODUCT_INCOMPATIBLE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_REPLAY_CONFLICT =
  'B1_REVENUE_RECOGNITION_ENGINE_REPLAY_CONFLICT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_REPLAY_EXPIRED =
  'B1_REVENUE_RECOGNITION_ENGINE_REPLAY_EXPIRED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_IN_PROGRESS =
  'B1_REVENUE_RECOGNITION_ENGINE_IN_PROGRESS' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_NUMBER_CONFLICT =
  'B1_REVENUE_RECOGNITION_ENGINE_NUMBER_CONFLICT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_EXPIRED =
  'B1_REVENUE_RECOGNITION_ENGINE_EXPIRED' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_RECOGNITION_BASIS_INVALID =
  'B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_BASIS_INVALID' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_NOT_APPLICABLE =
  'B1_REVENUE_RECOGNITION_ENGINE_NOT_APPLICABLE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_RECOGNITION_POLICY_MISSING =
  'B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_POLICY_MISSING' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_TAX_JURISDICTION_INVALID =
  'B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION_INVALID' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_COST_ALLOCATION_INVALID =
  'B1_REVENUE_RECOGNITION_ENGINE_COST_ALLOCATION_INVALID' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_DEFERRED_REVENUE_INVALID =
  'B1_REVENUE_RECOGNITION_ENGINE_DEFERRED_REVENUE_INVALID' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_FAILURE_CODES = [
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_INVALID_COMMAND,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_QUERY_UNAVAILABLE,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_PROHIBITED,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_DECISION_NOT_FOUND,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_DECISION_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_CATALOG_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_CATALOG_MISSING,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_BILLING_DOCUMENT_NOT_FOUND,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_BILLING_DOCUMENT_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_A4_POLICY_DENIED,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_A3_BINDING_INVALID,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_A5_LEDGER_INVARIANT_BROKEN,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_A6_PARTNER_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_A7_PRODUCT_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_REPLAY_CONFLICT,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_REPLAY_EXPIRED,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_IN_PROGRESS,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_NUMBER_CONFLICT,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_EXPIRED,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_RECOGNITION_BASIS_INVALID,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_NOT_APPLICABLE,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_RECOGNITION_POLICY_MISSING,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_TAX_JURISDICTION_INVALID,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_COST_ALLOCATION_INVALID,
  B1_REVENUE_RECOGNITION_ENGINE_FAILURE_DEFERRED_REVENUE_INVALID,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine metric names (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_REVENUE_RECOGNITION =
  'b1.revenue-recognition-engine.revenue-recognition' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_TAX_VAT =
  'b1.revenue-recognition-engine.tax-vat' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_COST_ACCOUNTING =
  'b1.revenue-recognition-engine.cost-accounting' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_REPLAYED =
  'b1.revenue-recognition-engine.replayed' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_CONFLICT =
  'b1.revenue-recognition-engine.conflict' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_INCOMPATIBLE =
  'b1.revenue-recognition-engine.incompatible' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_QUERY_UNAVAILABLE =
  'b1.revenue-recognition-engine.query-unavailable' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_IN_PROGRESS =
  'b1.revenue-recognition-engine.in-progress' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_REPLAY_CONFLICT =
  'b1.revenue-recognition-engine.replay-conflict' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_REPLAY_EXPIRED =
  'b1.revenue-recognition-engine.replay-expired' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_NUMBER_CONFLICT =
  'b1.revenue-recognition-engine.number-conflict' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_EXPIRED =
  'b1.revenue-recognition-engine.expired' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_RECOGNITION_BASIS_INVALID =
  'b1.revenue-recognition-engine.recognition-basis-invalid' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_NOT_APPLICABLE =
  'b1.revenue-recognition-engine.not-applicable' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_RECOGNITION_POLICY_MISSING =
  'b1.revenue-recognition-engine.recognition-policy-missing' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_TAX_JURISDICTION_INVALID =
  'b1.revenue-recognition-engine.tax-jurisdiction-invalid' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_COST_ALLOCATION_INVALID =
  'b1.revenue-recognition-engine.cost-allocation-invalid' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_DEFERRED_REVENUE_INVALID =
  'b1.revenue-recognition-engine.deferred-revenue-invalid' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_A4_POLICY_DENIED =
  'b1.revenue-recognition-engine.a4-policy-denied' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_A3_BINDING_INVALID =
  'b1.revenue-recognition-engine.a3-binding-invalid' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_A5_LEDGER_INVARIANT_BROKEN =
  'b1.revenue-recognition-engine.a5-ledger-invariant-broken' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_A6_PARTNER_INCOMPATIBLE =
  'b1.revenue-recognition-engine.a6-partner-incompatible' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_A7_PRODUCT_INCOMPATIBLE =
  'b1.revenue-recognition-engine.a7-product-incompatible' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_CATALOG_INCOMPATIBLE =
  'b1.revenue-recognition-engine.catalog-incompatible' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_CATALOG_MISSING =
  'b1.revenue-recognition-engine.catalog-missing' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_DECISION_NOT_FOUND =
  'b1.revenue-recognition-engine.decision-not-found' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_DECISION_INCOMPATIBLE =
  'b1.revenue-recognition-engine.decision-incompatible' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_BILLING_DOCUMENT_NOT_FOUND =
  'b1.revenue-recognition-engine.billing-document-not-found' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_METRIC_BILLING_DOCUMENT_INCOMPATIBLE =
  'b1.revenue-recognition-engine.billing-document-incompatible' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_METRICS = [
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_REVENUE_RECOGNITION,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_TAX_VAT,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_COST_ACCOUNTING,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_REPLAYED,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_CONFLICT,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_QUERY_UNAVAILABLE,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_IN_PROGRESS,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_REPLAY_CONFLICT,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_REPLAY_EXPIRED,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_NUMBER_CONFLICT,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_EXPIRED,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_RECOGNITION_BASIS_INVALID,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_NOT_APPLICABLE,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_RECOGNITION_POLICY_MISSING,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_TAX_JURISDICTION_INVALID,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_COST_ALLOCATION_INVALID,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_DEFERRED_REVENUE_INVALID,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_A4_POLICY_DENIED,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_A3_BINDING_INVALID,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_A5_LEDGER_INVARIANT_BROKEN,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_A6_PARTNER_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_A7_PRODUCT_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_CATALOG_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_CATALOG_MISSING,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_DECISION_NOT_FOUND,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_DECISION_INCOMPATIBLE,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_BILLING_DOCUMENT_NOT_FOUND,
  B1_REVENUE_RECOGNITION_ENGINE_METRIC_BILLING_DOCUMENT_INCOMPATIBLE,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine classification level vocabulary
 * (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_CLASSIFICATION_LEVELS = [
  'PUBLIC',
  'INTERNAL',
  'CONFIDENTIAL',
  'RESTRICTED',
  'HIGHLY_RESTRICTED',
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine data control classifications (frozen
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_DATA_CONTROL_CLASSIFICATIONS = [
  'PUBLIC',
  'INTERNAL',
  'CONFIDENTIAL',
  'RESTRICTED',
  'HIGHLY_RESTRICTED',
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine rule kind vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A3_BINDING_RECHECK =
  'A3_BINDING_RECHECK' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A4_POLICY_CURRENTNESS =
  'A4_POLICY_CURRENTNESS' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A4_POLICY_OBLIGATION =
  'A4_POLICY_OBLIGATION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A4_POLICY_REEVALUATION =
  'A4_POLICY_REEVALUATION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A4_POLICY_LIMIT = 'A4_POLICY_LIMIT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A5_LEDGER_ACCOUNT_STATE =
  'A5_LEDGER_ACCOUNT_STATE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A5_LEDGER_POSTING_BOUNDARY =
  'A5_LEDGER_POSTING_BOUNDARY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A5_FINANCIAL_INVARIANTS =
  'A5_FINANCIAL_INVARIANTS' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A6_PARTNER_STATE = 'A6_PARTNER_STATE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A6_PARTNER_CAPABILITY_VERSION =
  'A6_PARTNER_CAPABILITY_VERSION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A6T08_SETTLEMENT_SUSPENSE_COMPENSATING =
  'A6T08_SETTLEMENT_SUSPENSE_COMPENSATING' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A6T09_EXTERNAL_RECONCILIATION =
  'A6T09_EXTERNAL_RECONCILIATION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7_PRODUCT_CATALOG =
  'A7_PRODUCT_CATALOG' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7_PRODUCT_BOUNDARY =
  'A7_PRODUCT_BOUNDARY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T04_PRODUCT_CUSTOMER_BINDING =
  'A7T04_PRODUCT_CUSTOMER_BINDING' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T05_PRODUCT_COMMAND_OPERATION =
  'A7T05_PRODUCT_COMMAND_OPERATION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T06_PRODUCT_NOTIFICATION =
  'A7T06_PRODUCT_NOTIFICATION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T07_PRODUCT_LIFECYCLE =
  'A7T07_PRODUCT_LIFECYCLE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T08_PRODUCT_FINANCIAL_EFFECT =
  'A7T08_PRODUCT_FINANCIAL_EFFECT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T09_PRODUCT_RECONCILIATION =
  'A7T09_PRODUCT_RECONCILIATION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T10_PRODUCT_DATA_MINIMIZATION =
  'A7T10_PRODUCT_DATA_MINIMIZATION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_LOOKUP =
  'B1_COMMERCIAL_CATALOG_LOOKUP' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_COMPATIBILITY =
  'B1_COMMERCIAL_CATALOG_COMPATIBILITY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PLAN =
  'B1_COMMERCIAL_CATALOG_PLAN' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_TIER =
  'B1_COMMERCIAL_CATALOG_TIER' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_ENTITLEMENT =
  'B1_COMMERCIAL_CATALOG_ENTITLEMENT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PACKAGE =
  'B1_COMMERCIAL_CATALOG_PACKAGE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_BUNDLE =
  'B1_COMMERCIAL_CATALOG_BUNDLE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_SUBSCRIPTION =
  'B1_COMMERCIAL_CATALOG_SUBSCRIPTION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_FEATURE_FLAG =
  'B1_COMMERCIAL_CATALOG_FEATURE_FLAG' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT =
  'B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PRICING =
  'B1_COMMERCIAL_CATALOG_PRICING' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_LOOKUP =
  'B1_COMMERCIAL_DECISION_LOOKUP' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_COMPATIBILITY =
  'B1_COMMERCIAL_DECISION_COMPATIBILITY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_REPLAY =
  'B1_COMMERCIAL_DECISION_REPLAY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_LOOKUP =
  'B1_BILLING_ENGINE_DOCUMENT_LOOKUP' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_COMPATIBILITY =
  'B1_BILLING_ENGINE_DOCUMENT_COMPATIBILITY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_REPLAY =
  'B1_BILLING_ENGINE_DOCUMENT_REPLAY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_LOOKUP =
  'B1_CAMPAIGN_DECISION_LOOKUP' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_COMPATIBILITY =
  'B1_CAMPAIGN_DECISION_COMPATIBILITY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_REPLAY =
  'B1_CAMPAIGN_DECISION_REPLAY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_LOOKUP =
  'B1_PROMOTION_DECISION_LOOKUP' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_COMPATIBILITY =
  'B1_PROMOTION_DECISION_COMPATIBILITY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_REPLAY =
  'B1_PROMOTION_DECISION_REPLAY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COUPON_DECISION_LOOKUP =
  'B1_COUPON_DECISION_LOOKUP' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COUPON_DECISION_COMPATIBILITY =
  'B1_COUPON_DECISION_COMPATIBILITY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COUPON_DECISION_REPLAY =
  'B1_COUPON_DECISION_REPLAY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REFERRAL_DECISION_LOOKUP =
  'B1_REFERRAL_DECISION_LOOKUP' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REFERRAL_DECISION_COMPATIBILITY =
  'B1_REFERRAL_DECISION_COMPATIBILITY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REFERRAL_DECISION_REPLAY =
  'B1_REFERRAL_DECISION_REPLAY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CASHBACK_DECISION_LOOKUP =
  'B1_CASHBACK_DECISION_LOOKUP' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CASHBACK_DECISION_COMPATIBILITY =
  'B1_CASHBACK_DECISION_COMPATIBILITY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CASHBACK_DECISION_REPLAY =
  'B1_CASHBACK_DECISION_REPLAY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_LOYALTY_DECISION_LOOKUP =
  'B1_LOYALTY_DECISION_LOOKUP' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_LOYALTY_DECISION_COMPATIBILITY =
  'B1_LOYALTY_DECISION_COMPATIBILITY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_LOYALTY_DECISION_REPLAY =
  'B1_LOYALTY_DECISION_REPLAY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_POLICY =
  'B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_POLICY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_SCHEDULE =
  'B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_SCHEDULE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_EVENT =
  'B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_EVENT' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_BASIS =
  'B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_BASIS' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_DEFERRED_REVENUE =
  'B1_REVENUE_RECOGNITION_ENGINE_DEFERRED_REVENUE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_RECOGNIZED_REVENUE =
  'B1_REVENUE_RECOGNITION_ENGINE_RECOGNIZED_REVENUE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_POLICY =
  'B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_POLICY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION =
  'B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY =
  'B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_EXEMPTION =
  'B1_REVENUE_RECOGNITION_ENGINE_TAX_EXEMPTION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_DECISION =
  'B1_REVENUE_RECOGNITION_ENGINE_TAX_DECISION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_EVIDENCE =
  'B1_REVENUE_RECOGNITION_ENGINE_TAX_EVIDENCE' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_POLICY =
  'B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_POLICY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_DIRECT_COST =
  'B1_REVENUE_RECOGNITION_ENGINE_DIRECT_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_INDIRECT_COST =
  'B1_REVENUE_RECOGNITION_ENGINE_INDIRECT_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_ACQUISITION_COST =
  'B1_REVENUE_RECOGNITION_ENGINE_ACQUISITION_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_OPERATIONAL_COST =
  'B1_REVENUE_RECOGNITION_ENGINE_OPERATIONAL_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_ALLOCATED_COST =
  'B1_REVENUE_RECOGNITION_ENGINE_ALLOCATED_COST' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY =
  'B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_COST_DECISION =
  'B1_REVENUE_RECOGNITION_ENGINE_COST_DECISION' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_NUMBER_DETERMINISTIC =
  'B1_REVENUE_RECOGNITION_ENGINE_NUMBER_DETERMINISTIC' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_VERSION =
  'B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_VERSION' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_RULE_KINDS = [
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A4_POLICY_LIMIT,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A4_POLICY_OBLIGATION,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A4_POLICY_CURRENTNESS,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A4_POLICY_REEVALUATION,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A3_BINDING_RECHECK,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A5_LEDGER_ACCOUNT_STATE,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A5_LEDGER_POSTING_BOUNDARY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A5_FINANCIAL_INVARIANTS,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A6_PARTNER_STATE,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A6_PARTNER_CAPABILITY_VERSION,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A6T08_SETTLEMENT_SUSPENSE_COMPENSATING,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A6T09_EXTERNAL_RECONCILIATION,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7_PRODUCT_CATALOG,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7_PRODUCT_BOUNDARY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T04_PRODUCT_CUSTOMER_BINDING,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T05_PRODUCT_COMMAND_OPERATION,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T06_PRODUCT_NOTIFICATION,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T07_PRODUCT_LIFECYCLE,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_A7T08_PRODUCT_FINANCIAL_EFFECT,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_LOOKUP,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_COMPATIBILITY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PLAN,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_TIER,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_ENTITLEMENT,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PACKAGE,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_BUNDLE,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_SUBSCRIPTION,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_FEATURE_FLAG,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PRICING,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_LOOKUP,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_COMPATIBILITY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_REPLAY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_LOOKUP,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_COMPATIBILITY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_REPLAY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_LOOKUP,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_COMPATIBILITY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_REPLAY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_LOOKUP,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_COMPATIBILITY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_REPLAY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COUPON_DECISION_LOOKUP,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COUPON_DECISION_COMPATIBILITY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_COUPON_DECISION_REPLAY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REFERRAL_DECISION_LOOKUP,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REFERRAL_DECISION_COMPATIBILITY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REFERRAL_DECISION_REPLAY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CASHBACK_DECISION_LOOKUP,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CASHBACK_DECISION_COMPATIBILITY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_CASHBACK_DECISION_REPLAY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_LOYALTY_DECISION_LOOKUP,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_LOYALTY_DECISION_COMPATIBILITY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_LOYALTY_DECISION_REPLAY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_REVENUE_RECOGNITION_POLICY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_SCHEDULE,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_EVENT,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_RECOGNITION_BASIS,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_DEFERRED_REVENUE,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_RECOGNIZED_REVENUE,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_VAT_POLICY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_JURISDICTION,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_CATEGORY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_EXEMPTION,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_DECISION,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_TAX_EVIDENCE,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_COST_ACCOUNTING_POLICY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_DIRECT_COST,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_INDIRECT_COST,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_ACQUISITION_COST,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_OPERATIONAL_COST,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_ALLOCATED_COST,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_COST_CATEGORY,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_COST_DECISION,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_NUMBER_DETERMINISTIC,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_KIND_B1_REVENUE_RECOGNITION_ENGINE_DOCUMENT_VERSION,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine rule outcome vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOME_PASS = 'PASS' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOME_FAIL = 'FAIL' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOME_SKIP = 'SKIP' as const;
export const B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOME_NOT_APPLICABLE = 'NOT_APPLICABLE' as const;

export const B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOMES = [
  B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOME_PASS,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOME_FAIL,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOME_SKIP,
  B1_REVENUE_RECOGNITION_ENGINE_RULE_OUTCOME_NOT_APPLICABLE,
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine compatibility rule identifiers
 * (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_COMPATIBILITY_RULE_IDS = [
  'B1_REVENUE_RECOGNITION_RULE_SCOPE_KEY_REQUIRED',
  'B1_REVENUE_RECOGNITION_RULE_SCOPE_VERSION_REQUIRED',
  'B1_REVENUE_RECOGNITION_RULE_CURRENCY_REQUIRED',
  'B1_REVENUE_RECOGNITION_RULE_ACCOUNTING_UNIT_REQUIRED',
  'B1_REVENUE_RECOGNITION_RULE_PRODUCT_DEPENDENCY_REQUIRED',
  'B1_REVENUE_RECOGNITION_RULE_PARTNER_DEPENDENCY_REQUIRED',
  'B1_REVENUE_RECOGNITION_RULE_DOCUMENT_VERSION_REQUIRED',
  'B1_REVENUE_RECOGNITION_RULE_DECISION_REFERENCES_REQUIRED',
  'B1_REVENUE_RECOGNITION_RULE_BILLING_DOCUMENT_REFERENCE_REQUIRED',
  'B1_REVENUE_RECOGNITION_RULE_NUMBER_DETERMINISTIC',
  'B1_REVENUE_RECOGNITION_RULE_NO_CROSS_CATALOG_REFERENCES',
  'B1_REVENUE_RECOGNITION_RULE_NO_CROSS_SCOPE_NEGOTIATION',
  'B1_REVENUE_RECOGNITION_RULE_PERIOD_VERSION_REQUIRED',
  'B1_REVENUE_RECOGNITION_RULE_RECOGNITION_BASIS_VALID',
  'B1_REVENUE_RECOGNITION_RULE_TAX_JURISDICTION_VALID',
  'B1_REVENUE_RECOGNITION_RULE_COST_ALLOCATION_VALID',
  'B1_REVENUE_RECOGNITION_RULE_RECOGNITION_POLICY_VALID',
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine consumer contract identifiers (frozen
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_CONSUMER_CONTRACT_IDS = [
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A1',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A2',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A3',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A4',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A5',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A6',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A7',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A6T10',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A6T09',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A7T09',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A7T08',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_A7T06',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_B1_COMMERCIAL_CATALOG',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_B1_COMMERCIAL_DECISION',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_B1_BILLING_ENGINE',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_B1_CAMPAIGN_ENGINE',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_B1_REFERRAL_ENGINE',
  'B1_REVENUE_RECOGNITION_CONSUMER_CONTRACT_OPERATIONS',
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine version negotiation rule identifiers
 * (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_VERSION_NEGOTIATION_RULE_IDS = [
  'B1_REVENUE_RECOGNITION_VERSION_RULE_SCOPE_VERSION_EXACT_MATCH',
  'B1_REVENUE_RECOGNITION_VERSION_RULE_DOCUMENT_VERSION_EXACT_MATCH',
  'B1_REVENUE_RECOGNITION_VERSION_RULE_PERIOD_VERSION_EXACT_MATCH',
  'B1_REVENUE_RECOGNITION_VERSION_RULE_NO_CROSS_CATALOG_NEGOTIATION',
  'B1_REVENUE_RECOGNITION_VERSION_RULE_NO_CROSS_BILLING_ENGINE_NEGOTIATION',
  'B1_REVENUE_RECOGNITION_VERSION_RULE_NO_CROSS_CAMPAIGN_ENGINE_NEGOTIATION',
  'B1_REVENUE_RECOGNITION_VERSION_RULE_NO_CROSS_REFERRAL_ENGINE_NEGOTIATION',
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine replay rule identifiers (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_REPLAY_RULE_IDS = [
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_WINDOW_86400',
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_EXACT_MATCH_REQUIRED',
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_IDEMPOTENT',
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_AUDIT_TRACED',
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_EXPIRES_AFTER_WINDOW',
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_INHERITS_A1_A7',
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_INHERITS_B1T03',
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_INHERITS_B1T04',
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_INHERITS_B1T05',
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_INHERITS_B1T06',
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_INHERITS_B1T07',
  'B1_REVENUE_RECOGNITION_REPLAY_RULE_NUMBER_DETERMINISTIC',
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine declared dependencies (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_DECLARED_DEPENDENCIES = [
  'A1-CANONICAL-IDENTITY',
  'A2-AUTHORIZATION-CONTEXT',
  'A3-CUSTOMER-FINANCIAL-ACCOUNT-BINDING',
  'A4-PRODUCT-POLICY-DECISION',
  'A5-LEDGER',
  'A6-PARTNER-ADAPTER',
  'A6T05-EXTERNAL-OPERATION',
  'A6T08-SETTLEMENT-SUSPENSE-COMPENSATING',
  'A6T09-EXTERNAL-RECONCILIATION',
  'A6T10-DATA-CLASSIFICATION',
  'A7-PRODUCT-CATALOG',
  'A7-PRODUCT-POLICY-PROFILE',
  'A7T04-PRODUCT-CUSTOMER-BINDING',
  'A7T05-PRODUCT-COMMAND-OPERATION',
  'A7T06-PRODUCT-NOTIFICATION-DELIVERY',
  'A7T07-PRODUCT-LIFECYCLE',
  'A7T08-PRODUCT-FINANCIAL-EFFECT',
  'A7T09-PRODUCT-RECONCILIATION',
  'A7T10-PRODUCT-DATA-MINIMIZATION',
  'B1-COMMERCIAL-CATALOG',
  'B1-COMMERCIAL-DECISION',
  'B1-BILLING-ENGINE',
  'B1-CAMPAIGN-ENGINE',
  'B1-REFERRAL-ENGINE',
  'CUSTOMER-PREFERENCE',
  'OPERATIONS-AUDIT',
  'OPERATIONS-IDEMPOTENCY',
  'OPERATIONS-OUTBOX',
  'OPERATIONS-METRICS',
  'OPERATIONS-DIAGNOSTICS',
  'WALLET',
  'LEDGER',
  'RECONCILIATION',
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine prohibited dependencies (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED_DEPENDENCIES = [
  'B1_PROFITABILITY_ENGINE',
  'B1_ANALYTICS_ENGINE',
  'B1_COMMERCIAL_RECONCILIATION_ENGINE',
  'B1_COMMERCIAL_DATA_CLASSIFICATION_REGISTRY',
  'B1_COMMERCIAL_IDEMPOTENCY_AUTHORITY',
  'B1_COMMERCIAL_AUDIT_AUTHORITY',
  'B1_COMMERCIAL_APPROVAL_AUTHORITY',
  'B1_COMMERCIAL_FEATURE_FLAG_AUTHORITY',
  'B1_COMMERCIAL_RELEASE_GATE',
  'A5_LEDGER_POSTING_AUTHORITY',
  'A5_LEDGER_JOURNAL_AUTHORITY',
  'A5_FINANCIAL_INVARIANTS_OVERRIDE_AUTHORITY',
  'A6T08_SETTLEMENT_AUTHORITY',
  'A6T08_SUSPENSE_AUTHORITY',
  'A6T08_COMPENSATING_AUTHORITY',
  'A6T09_RECONCILIATION_AUTHORITY',
  'A7T06_NOTIFICATION_DISPATCH_AUTHORITY',
  'A7T08_PRODUCT_FINANCIAL_EFFECT_AUTHORITY',
  'REVENUE_RECOGNITION_POSTING_AUTHORITY',
  'TAX_VAT_POSTING_AUTHORITY',
  'COST_ACCOUNTING_POSTING_AUTHORITY',
  'CASHBACK_REDEMPTION_AUTHORITY',
  'LOYALTY_BALANCE_AUTHORITY',
  'REFERRAL_REWARD_AUTHORITY',
] as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine cashback idempotency scope note (frozen
 * documentation reference). The B1T07 referral engine owns the
 * cashback idempotency scope. The B1T08 revenue-recognition engine
 * is read-only against the B1T07 commercial-rewards decision
 * references and does NOT introduce cashback / loyalty / referral
 * idempotency scopes of its own.
 */
export const B1_REVENUE_RECOGNITION_ENGINE_CASHBACK_IDEMPOTENCY_SCOPE_NOTE =
  'B1T07_OWNED_CASHBACK_NOT_B1T08' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine loyalty idempotency scope note (frozen
 * documentation reference). The B1T07 referral engine owns the
 * loyalty idempotency scope.
 */
export const B1_REVENUE_RECOGNITION_ENGINE_LOYALTY_IDEMPOTENCY_SCOPE_NOTE =
  'B1T07_OWNED_LOYALTY_NOT_B1T08' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine referral idempotency scope note (frozen
 * documentation reference). The B1T07 referral engine owns the
 * referral idempotency scope.
 */
export const B1_REVENUE_RECOGNITION_ENGINE_REFERRAL_IDEMPOTENCY_SCOPE_NOTE =
  'B1T07_OWNED_REFERRAL_NOT_B1T08' as const;

/**
 * B1 revenue-recognition engine, tax / VAT engine, and
 * cost-accounting engine prohibited adjacent scopes (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T08 and re-asserted from
 * the B1T03 catalog).
 */
export const B1_REVENUE_RECOGNITION_ENGINE_PROHIBITED_ADJACENT_SCOPES = [
  'commercial.virtual-account.outbound-settlement',
  'commercial.savings.inbound-funding',
  'commercial.lending.inbound-funding',
  'commercial.bills.inbound-funding',
  'commercial.airtime.inbound-funding',
  'commercial.qr-merchant.inbound-funding',
  'commercial.agent-assisted.inbound-funding',
  'commercial.card.inbound-funding',
  'commercial.bulk-payroll.inbound-funding',
  'commercial.fx.inbound-funding',
  'commercial.cross-region.inbound-funding',
  'commercial.cross-currency.inbound-funding',
  'commercial.public-channel.inbound-funding',
  'commercial.marketing-consent.inbound-funding',
] as const;
