/**
 * B1T07 — B1 referral engine, cashback engine, and loyalty engine
 * frozen constants.
 *
 * The B1 referral engine, cashback engine, and loyalty engine is
 * the only B1 commercial-rewards engine for referrals, cashback,
 * and loyalty. The B1 referral engine, cashback engine, and
 * loyalty engine is a read-only contract against the existing
 * A1 canonical identity, A2 authorization, A3 binding, A4 policy
 * decision, A5 Ledger, A6 partner-adapter, A6T05 external-
 * operation, A6T08 settlement / suspense / compensating, A6T09
 * external reconciliation, A6T10 data classification, A7 product
 * catalog, A7 product-policy profile, A7T04 product customer-
 * binding, A7T05 product command, A7T06 product notification,
 * A7T07 product lifecycle, A7T08 product financial effect,
 * A7T09 product reconciliation, A7T10 product data minimization,
 * `CustomerPreference`, Wallet, Operations, Outbox, Idempotency,
 * Metrics, Diagnostics, Reconciliation, and `CustomerPreference`
 * authorities.
 */

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * contract name (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_CONTRACT_NAME = 'B1-REFERRAL-ENGINE' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * contract version (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_CONTRACT_VERSION = 1 as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * contract document reference.
 */
export const B1_REFERRAL_ENGINE_CONTRACT_DOCUMENT = 'docs/B1-REFERRAL-ENGINE-CONTRACT.md' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * referral internal idempotency scope (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_REFERRAL_IDEMPOTENCY_SCOPE =
  'b1.referral-engine.referral.idempotency.v1' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * cashback internal idempotency scope (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_CASHBACK_IDEMPOTENCY_SCOPE =
  'b1.referral-engine.cashback.idempotency.v1' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * loyalty internal idempotency scope (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_LOYALTY_IDEMPOTENCY_SCOPE =
  'b1.referral-engine.loyalty.idempotency.v1' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * internal idempotency retention (frozen; 24 hours, aligned with
 * the shared Operations `IdempotencyService` default).
 */
export const B1_REFERRAL_ENGINE_IDEMPOTENCY_RETENTION_SECONDS = 86_400 as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine audit
 * entity type (frozen).
 */
export const B1_REFERRAL_ENGINE_AUDIT_ENTITY_TYPE = 'B1_REFERRAL_DECISION' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine audit
 * actor (frozen).
 */
export const B1_REFERRAL_ENGINE_AUDIT_ACTOR = 'b1-referral-engine' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine outbox
 * event type (frozen).
 */
export const B1_REFERRAL_ENGINE_OUTBOX_EVENT_TYPE = 'B1ReferralDecisionDecided' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine outbox
 * event classification (frozen).
 */
export const B1_REFERRAL_ENGINE_OUTBOX_EVENT_CLASSIFICATION = 'INTERNAL_OPERATIONS' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine outbox
 * event retention class (frozen).
 */
export const B1_REFERRAL_ENGINE_OUTBOX_EVENT_RETENTION_CLASS = 'OPERATIONS_DEFAULT' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * reference prefix (frozen).
 */
export const B1_REFERRAL_ENGINE_REFERENCE_PREFIX = 'b1-referral-decision' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine scope
 * key (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_SCOPE_KEY = 'commercial.virtual-account.inbound-funding' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine scope
 * version (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_SCOPE_VERSION = 1 as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine scope
 * currency (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_SCOPE_CURRENCY = 'NGN' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine scope
 * accounting unit (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_SCOPE_ACCOUNTING_UNIT = 'CUSTOMER_FUNDS' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine scope
 * product dependency (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_SCOPE_PRODUCT_DEPENDENCY = 'VIRTUAL_ACCOUNT' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine scope
 * product dependency version (frozen).
 */
export const B1_REFERRAL_ENGINE_SCOPE_PRODUCT_DEPENDENCY_VERSION = 1 as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine scope
 * partner dependency (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_SCOPE_PARTNER_DEPENDENCY = 'NIBSS_NIP' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine scope
 * direction (frozen by
 * `docs/B1-COMMERCIAL-CATALOG-CONTRACT.md` §4.1 and re-asserted
 * by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_SCOPE_DIRECTION = 'inbound' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine period
 * key (frozen by `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_PERIOD_KEY =
  'commercial.virtual-account.inbound-funding.referral-period.per-flow.v1' as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * retention days (frozen; 365 days, aligned with the B1T03 catalog
 * retention).
 */
export const B1_REFERRAL_ENGINE_RETENTION_DAYS = 365 as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * decision kind vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_DECISION_KIND_REFERRAL = 'REFERRAL' as const;
export const B1_REFERRAL_ENGINE_DECISION_KIND_CASHBACK = 'CASHBACK' as const;
export const B1_REFERRAL_ENGINE_DECISION_KIND_LOYALTY = 'LOYALTY' as const;

export const B1_REFERRAL_ENGINE_DECISION_KINDS = [
  B1_REFERRAL_ENGINE_DECISION_KIND_REFERRAL,
  B1_REFERRAL_ENGINE_DECISION_KIND_CASHBACK,
  B1_REFERRAL_ENGINE_DECISION_KIND_LOYALTY,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * decision outcome vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_DECISION_OUTCOME_ELIGIBLE = 'ELIGIBLE' as const;
export const B1_REFERRAL_ENGINE_DECISION_OUTCOME_APPLIED = 'APPLIED' as const;
export const B1_REFERRAL_ENGINE_DECISION_OUTCOME_REJECTED = 'REJECTED' as const;
export const B1_REFERRAL_ENGINE_DECISION_OUTCOME_REPLAYED = 'REPLAYED' as const;

export const B1_REFERRAL_ENGINE_DECISION_OUTCOMES = [
  B1_REFERRAL_ENGINE_DECISION_OUTCOME_ELIGIBLE,
  B1_REFERRAL_ENGINE_DECISION_OUTCOME_APPLIED,
  B1_REFERRAL_ENGINE_DECISION_OUTCOME_REJECTED,
  B1_REFERRAL_ENGINE_DECISION_OUTCOME_REPLAYED,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * referral state vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_REFERRAL_STATE_DRAFT = 'DRAFT' as const;
export const B1_REFERRAL_ENGINE_REFERRAL_STATE_ACTIVE = 'ACTIVE' as const;
export const B1_REFERRAL_ENGINE_REFERRAL_STATE_PAUSED = 'PAUSED' as const;
export const B1_REFERRAL_ENGINE_REFERRAL_STATE_EXPIRED = 'EXPIRED' as const;
export const B1_REFERRAL_ENGINE_REFERRAL_STATE_RETIRED = 'RETIRED' as const;

export const B1_REFERRAL_ENGINE_REFERRAL_STATES = [
  B1_REFERRAL_ENGINE_REFERRAL_STATE_DRAFT,
  B1_REFERRAL_ENGINE_REFERRAL_STATE_ACTIVE,
  B1_REFERRAL_ENGINE_REFERRAL_STATE_PAUSED,
  B1_REFERRAL_ENGINE_REFERRAL_STATE_EXPIRED,
  B1_REFERRAL_ENGINE_REFERRAL_STATE_RETIRED,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * cashback state vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_CASHBACK_STATE_CREATED = 'CREATED' as const;
export const B1_REFERRAL_ENGINE_CASHBACK_STATE_ACTIVE = 'ACTIVE' as const;
export const B1_REFERRAL_ENGINE_CASHBACK_STATE_PAUSED = 'PAUSED' as const;
export const B1_REFERRAL_ENGINE_CASHBACK_STATE_EXPIRED = 'EXPIRED' as const;
export const B1_REFERRAL_ENGINE_CASHBACK_STATE_CANCELLED = 'CANCELLED' as const;

export const B1_REFERRAL_ENGINE_CASHBACK_STATES = [
  B1_REFERRAL_ENGINE_CASHBACK_STATE_CREATED,
  B1_REFERRAL_ENGINE_CASHBACK_STATE_ACTIVE,
  B1_REFERRAL_ENGINE_CASHBACK_STATE_PAUSED,
  B1_REFERRAL_ENGINE_CASHBACK_STATE_EXPIRED,
  B1_REFERRAL_ENGINE_CASHBACK_STATE_CANCELLED,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * loyalty state vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_LOYALTY_STATE_DRAFT = 'DRAFT' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_STATE_ACTIVE = 'ACTIVE' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_STATE_SUSPENDED = 'SUSPENDED' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_STATE_RETIRED = 'RETIRED' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_STATE_ARCHIVED = 'ARCHIVED' as const;

export const B1_REFERRAL_ENGINE_LOYALTY_STATES = [
  B1_REFERRAL_ENGINE_LOYALTY_STATE_DRAFT,
  B1_REFERRAL_ENGINE_LOYALTY_STATE_ACTIVE,
  B1_REFERRAL_ENGINE_LOYALTY_STATE_SUSPENDED,
  B1_REFERRAL_ENGINE_LOYALTY_STATE_RETIRED,
  B1_REFERRAL_ENGINE_LOYALTY_STATE_ARCHIVED,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * document kind vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL = 'REFERRAL' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL_PROGRAM = 'REFERRAL_PROGRAM' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL_CAMPAIGN = 'REFERRAL_CAMPAIGN' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL_RELATIONSHIP =
  'REFERRAL_RELATIONSHIP' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL_HIERARCHY = 'REFERRAL_HIERARCHY' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL_QUALIFICATION =
  'REFERRAL_QUALIFICATION' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_CASHBACK = 'CASHBACK' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_CASHBACK_CAMPAIGN = 'CASHBACK_CAMPAIGN' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_CASHBACK_RULE = 'CASHBACK_RULE' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY = 'LOYALTY' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY_PROGRAM = 'LOYALTY_PROGRAM' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY_TIER = 'LOYALTY_TIER' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY_POINT_POLICY =
  'LOYALTY_POINT_POLICY' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY_EARNING = 'LOYALTY_EARNING' as const;
export const B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY_REDEMPTION = 'LOYALTY_REDEMPTION' as const;

export const B1_REFERRAL_ENGINE_DOCUMENT_KINDS = [
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL_PROGRAM,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL_CAMPAIGN,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL_RELATIONSHIP,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL_HIERARCHY,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_REFERRAL_QUALIFICATION,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_CASHBACK,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_CASHBACK_CAMPAIGN,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_CASHBACK_RULE,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY_PROGRAM,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY_TIER,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY_POINT_POLICY,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY_EARNING,
  B1_REFERRAL_ENGINE_DOCUMENT_KIND_LOYALTY_REDEMPTION,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * relationship type vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_PARENT = 'PARENT' as const;
export const B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_CHILD = 'CHILD' as const;
export const B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_SIBLING = 'SIBLING' as const;
export const B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_SPONSOR = 'SPONSOR' as const;
export const B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_REFEREE = 'REFEREE' as const;
export const B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_CIRCLE = 'CIRCLE' as const;
export const B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_NETWORK = 'NETWORK' as const;

export const B1_REFERRAL_ENGINE_RELATIONSHIP_TYPES = [
  B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_PARENT,
  B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_CHILD,
  B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_SIBLING,
  B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_SPONSOR,
  B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_REFEREE,
  B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_CIRCLE,
  B1_REFERRAL_ENGINE_RELATIONSHIP_TYPE_NETWORK,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * qualification status vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_QUALIFICATION_STATUS_NOT_QUALIFIED = 'NOT_QUALIFIED' as const;
export const B1_REFERRAL_ENGINE_QUALIFICATION_STATUS_PENDING_VERIFICATION =
  'PENDING_VERIFICATION' as const;
export const B1_REFERRAL_ENGINE_QUALIFICATION_STATUS_QUALIFIED = 'QUALIFIED' as const;
export const B1_REFERRAL_ENGINE_QUALIFICATION_STATUS_OVER_QUALIFIED = 'OVER_QUALIFIED' as const;
export const B1_REFERRAL_ENGINE_QUALIFICATION_STATUS_EXPIRED_QUALIFICATION =
  'EXPIRED_QUALIFICATION' as const;

export const B1_REFERRAL_ENGINE_QUALIFICATION_STATUSES = [
  B1_REFERRAL_ENGINE_QUALIFICATION_STATUS_NOT_QUALIFIED,
  B1_REFERRAL_ENGINE_QUALIFICATION_STATUS_PENDING_VERIFICATION,
  B1_REFERRAL_ENGINE_QUALIFICATION_STATUS_QUALIFIED,
  B1_REFERRAL_ENGINE_QUALIFICATION_STATUS_OVER_QUALIFIED,
  B1_REFERRAL_ENGINE_QUALIFICATION_STATUS_EXPIRED_QUALIFICATION,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * loyalty tier status vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_PENDING = 'TIER_PENDING' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_BRONZE = 'TIER_BRONZE' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_SILVER = 'TIER_SILVER' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_GOLD = 'TIER_GOLD' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_PLATINUM = 'TIER_PLATINUM' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_DIAMOND = 'TIER_DIAMOND' as const;

export const B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUSES = [
  B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_PENDING,
  B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_BRONZE,
  B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_SILVER,
  B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_GOLD,
  B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_PLATINUM,
  B1_REFERRAL_ENGINE_LOYALTY_TIER_STATUS_DIAMOND,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * loyalty earning source vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_PURCHASE = 'PURCHASE' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_BILLING = 'BILLING' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_CAMPAIGN = 'CAMPAIGN' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_PROMOTION = 'PROMOTION' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_COUPON = 'COUPON' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_REFERRAL = 'REFERRAL' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_CASHBACK = 'CASHBACK' as const;
export const B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_MANUAL_ADJUSTMENT =
  'MANUAL_ADJUSTMENT' as const;

export const B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCES = [
  B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_PURCHASE,
  B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_BILLING,
  B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_CAMPAIGN,
  B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_PROMOTION,
  B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_COUPON,
  B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_REFERRAL,
  B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_CASHBACK,
  B1_REFERRAL_ENGINE_LOYALTY_EARNING_SOURCE_MANUAL_ADJUSTMENT,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * cashback calculation basis vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASIS_FIXED_AMOUNT = 'FIXED_AMOUNT' as const;
export const B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASIS_PERCENTAGE_OF_BILLING =
  'PERCENTAGE_OF_BILLING' as const;
export const B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASIS_PERCENTAGE_OF_FEE =
  'PERCENTAGE_OF_FEE' as const;
export const B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASIS_TIER_MULTIPLIER =
  'TIER_MULTIPLIER' as const;
export const B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASIS_CAMPAIGN_OVERRIDE =
  'CAMPAIGN_OVERRIDE' as const;

export const B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASES = [
  B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASIS_FIXED_AMOUNT,
  B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASIS_PERCENTAGE_OF_BILLING,
  B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASIS_PERCENTAGE_OF_FEE,
  B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASIS_TIER_MULTIPLIER,
  B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_BASIS_CAMPAIGN_OVERRIDE,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * decision failure code vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_FAILURE_INVALID_COMMAND =
  'B1_REFERRAL_ENGINE_INVALID_COMMAND' as const;
export const B1_REFERRAL_ENGINE_FAILURE_INCOMPATIBLE = 'B1_REFERRAL_ENGINE_INCOMPATIBLE' as const;
export const B1_REFERRAL_ENGINE_FAILURE_QUERY_UNAVAILABLE =
  'B1_REFERRAL_ENGINE_QUERY_UNAVAILABLE' as const;
export const B1_REFERRAL_ENGINE_FAILURE_PROHIBITED = 'B1_REFERRAL_ENGINE_PROHIBITED' as const;
export const B1_REFERRAL_ENGINE_FAILURE_DECISION_NOT_FOUND =
  'B1_REFERRAL_ENGINE_DECISION_NOT_FOUND' as const;
export const B1_REFERRAL_ENGINE_FAILURE_DECISION_INCOMPATIBLE =
  'B1_REFERRAL_ENGINE_DECISION_INCOMPATIBLE' as const;
export const B1_REFERRAL_ENGINE_FAILURE_CATALOG_INCOMPATIBLE =
  'B1_REFERRAL_ENGINE_CATALOG_INCOMPATIBLE' as const;
export const B1_REFERRAL_ENGINE_FAILURE_CATALOG_MISSING =
  'B1_REFERRAL_ENGINE_CATALOG_MISSING' as const;
export const B1_REFERRAL_ENGINE_FAILURE_BILLING_DOCUMENT_NOT_FOUND =
  'B1_REFERRAL_ENGINE_BILLING_DOCUMENT_NOT_FOUND' as const;
export const B1_REFERRAL_ENGINE_FAILURE_BILLING_DOCUMENT_INCOMPATIBLE =
  'B1_REFERRAL_ENGINE_BILLING_DOCUMENT_INCOMPATIBLE' as const;
export const B1_REFERRAL_ENGINE_FAILURE_CAMPAIGN_DECISION_NOT_FOUND =
  'B1_REFERRAL_ENGINE_CAMPAIGN_DECISION_NOT_FOUND' as const;
export const B1_REFERRAL_ENGINE_FAILURE_CAMPAIGN_DECISION_INCOMPATIBLE =
  'B1_REFERRAL_ENGINE_CAMPAIGN_DECISION_INCOMPATIBLE' as const;
export const B1_REFERRAL_ENGINE_FAILURE_PROMOTION_DECISION_NOT_FOUND =
  'B1_REFERRAL_ENGINE_PROMOTION_DECISION_NOT_FOUND' as const;
export const B1_REFERRAL_ENGINE_FAILURE_PROMOTION_DECISION_INCOMPATIBLE =
  'B1_REFERRAL_ENGINE_PROMOTION_DECISION_INCOMPATIBLE' as const;
export const B1_REFERRAL_ENGINE_FAILURE_COUPON_DECISION_NOT_FOUND =
  'B1_REFERRAL_ENGINE_COUPON_DECISION_NOT_FOUND' as const;
export const B1_REFERRAL_ENGINE_FAILURE_COUPON_DECISION_INCOMPATIBLE =
  'B1_REFERRAL_ENGINE_COUPON_DECISION_INCOMPATIBLE' as const;
export const B1_REFERRAL_ENGINE_FAILURE_A4_POLICY_DENIED =
  'B1_REFERRAL_ENGINE_A4_POLICY_DENIED' as const;
export const B1_REFERRAL_ENGINE_FAILURE_A3_BINDING_INVALID =
  'B1_REFERRAL_ENGINE_A3_BINDING_INVALID' as const;
export const B1_REFERRAL_ENGINE_FAILURE_A5_LEDGER_INVARIANT_BROKEN =
  'B1_REFERRAL_ENGINE_A5_LEDGER_INVARIANT_BROKEN' as const;
export const B1_REFERRAL_ENGINE_FAILURE_A6_PARTNER_INCOMPATIBLE =
  'B1_REFERRAL_ENGINE_A6_PARTNER_INCOMPATIBLE' as const;
export const B1_REFERRAL_ENGINE_FAILURE_A7_PRODUCT_INCOMPATIBLE =
  'B1_REFERRAL_ENGINE_A7_PRODUCT_INCOMPATIBLE' as const;
export const B1_REFERRAL_ENGINE_FAILURE_REPLAY_CONFLICT =
  'B1_REFERRAL_ENGINE_REPLAY_CONFLICT' as const;
export const B1_REFERRAL_ENGINE_FAILURE_REPLAY_EXPIRED =
  'B1_REFERRAL_ENGINE_REPLAY_EXPIRED' as const;
export const B1_REFERRAL_ENGINE_FAILURE_IN_PROGRESS = 'B1_REFERRAL_ENGINE_IN_PROGRESS' as const;
export const B1_REFERRAL_ENGINE_FAILURE_NUMBER_CONFLICT =
  'B1_REFERRAL_ENGINE_NUMBER_CONFLICT' as const;
export const B1_REFERRAL_ENGINE_FAILURE_EXPIRED = 'B1_REFERRAL_ENGINE_EXPIRED' as const;
export const B1_REFERRAL_ENGINE_FAILURE_USAGE_LIMIT_EXCEEDED =
  'B1_REFERRAL_ENGINE_USAGE_LIMIT_EXCEEDED' as const;
export const B1_REFERRAL_ENGINE_FAILURE_NOT_APPLICABLE =
  'B1_REFERRAL_ENGINE_NOT_APPLICABLE' as const;
export const B1_REFERRAL_ENGINE_FAILURE_HIERARCHY_INVALID =
  'B1_REFERRAL_ENGINE_HIERARCHY_INVALID' as const;
export const B1_REFERRAL_ENGINE_FAILURE_QUALIFICATION_INSUFFICIENT =
  'B1_REFERRAL_ENGINE_QUALIFICATION_INSUFFICIENT' as const;
export const B1_REFERRAL_ENGINE_FAILURE_TIER_INSUFFICIENT =
  'B1_REFERRAL_ENGINE_TIER_INSUFFICIENT' as const;
export const B1_REFERRAL_ENGINE_FAILURE_POINT_POLICY_INCOMPATIBLE =
  'B1_REFERRAL_ENGINE_POINT_POLICY_INCOMPATIBLE' as const;

export const B1_REFERRAL_ENGINE_FAILURE_CODES = [
  B1_REFERRAL_ENGINE_FAILURE_INVALID_COMMAND,
  B1_REFERRAL_ENGINE_FAILURE_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_FAILURE_QUERY_UNAVAILABLE,
  B1_REFERRAL_ENGINE_FAILURE_PROHIBITED,
  B1_REFERRAL_ENGINE_FAILURE_DECISION_NOT_FOUND,
  B1_REFERRAL_ENGINE_FAILURE_DECISION_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_FAILURE_CATALOG_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_FAILURE_CATALOG_MISSING,
  B1_REFERRAL_ENGINE_FAILURE_BILLING_DOCUMENT_NOT_FOUND,
  B1_REFERRAL_ENGINE_FAILURE_BILLING_DOCUMENT_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_FAILURE_CAMPAIGN_DECISION_NOT_FOUND,
  B1_REFERRAL_ENGINE_FAILURE_CAMPAIGN_DECISION_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_FAILURE_PROMOTION_DECISION_NOT_FOUND,
  B1_REFERRAL_ENGINE_FAILURE_PROMOTION_DECISION_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_FAILURE_COUPON_DECISION_NOT_FOUND,
  B1_REFERRAL_ENGINE_FAILURE_COUPON_DECISION_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_FAILURE_A4_POLICY_DENIED,
  B1_REFERRAL_ENGINE_FAILURE_A3_BINDING_INVALID,
  B1_REFERRAL_ENGINE_FAILURE_A5_LEDGER_INVARIANT_BROKEN,
  B1_REFERRAL_ENGINE_FAILURE_A6_PARTNER_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_FAILURE_A7_PRODUCT_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_FAILURE_REPLAY_CONFLICT,
  B1_REFERRAL_ENGINE_FAILURE_REPLAY_EXPIRED,
  B1_REFERRAL_ENGINE_FAILURE_IN_PROGRESS,
  B1_REFERRAL_ENGINE_FAILURE_NUMBER_CONFLICT,
  B1_REFERRAL_ENGINE_FAILURE_EXPIRED,
  B1_REFERRAL_ENGINE_FAILURE_USAGE_LIMIT_EXCEEDED,
  B1_REFERRAL_ENGINE_FAILURE_NOT_APPLICABLE,
  B1_REFERRAL_ENGINE_FAILURE_HIERARCHY_INVALID,
  B1_REFERRAL_ENGINE_FAILURE_QUALIFICATION_INSUFFICIENT,
  B1_REFERRAL_ENGINE_FAILURE_TIER_INSUFFICIENT,
  B1_REFERRAL_ENGINE_FAILURE_POINT_POLICY_INCOMPATIBLE,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * metric names (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_METRIC_REFERRAL = 'b1.referral-engine.referral' as const;
export const B1_REFERRAL_ENGINE_METRIC_CASHBACK = 'b1.referral-engine.cashback' as const;
export const B1_REFERRAL_ENGINE_METRIC_LOYALTY = 'b1.referral-engine.loyalty' as const;
export const B1_REFERRAL_ENGINE_METRIC_REPLAYED = 'b1.referral-engine.replayed' as const;
export const B1_REFERRAL_ENGINE_METRIC_CONFLICT = 'b1.referral-engine.conflict' as const;
export const B1_REFERRAL_ENGINE_METRIC_INCOMPATIBLE = 'b1.referral-engine.incompatible' as const;
export const B1_REFERRAL_ENGINE_METRIC_QUERY_UNAVAILABLE =
  'b1.referral-engine.query-unavailable' as const;
export const B1_REFERRAL_ENGINE_METRIC_IN_PROGRESS = 'b1.referral-engine.in-progress' as const;
export const B1_REFERRAL_ENGINE_METRIC_REPLAY_CONFLICT =
  'b1.referral-engine.replay-conflict' as const;
export const B1_REFERRAL_ENGINE_METRIC_REPLAY_EXPIRED =
  'b1.referral-engine.replay-expired' as const;
export const B1_REFERRAL_ENGINE_METRIC_NUMBER_CONFLICT =
  'b1.referral-engine.number-conflict' as const;
export const B1_REFERRAL_ENGINE_METRIC_EXPIRED = 'b1.referral-engine.expired' as const;
export const B1_REFERRAL_ENGINE_METRIC_USAGE_LIMIT_EXCEEDED =
  'b1.referral-engine.usage-limit-exceeded' as const;
export const B1_REFERRAL_ENGINE_METRIC_NOT_APPLICABLE =
  'b1.referral-engine.not-applicable' as const;
export const B1_REFERRAL_ENGINE_METRIC_HIERARCHY_INVALID =
  'b1.referral-engine.hierarchy-invalid' as const;
export const B1_REFERRAL_ENGINE_METRIC_QUALIFICATION_INSUFFICIENT =
  'b1.referral-engine.qualification-insufficient' as const;
export const B1_REFERRAL_ENGINE_METRIC_TIER_INSUFFICIENT =
  'b1.referral-engine.tier-insufficient' as const;
export const B1_REFERRAL_ENGINE_METRIC_POINT_POLICY_INCOMPATIBLE =
  'b1.referral-engine.point-policy-incompatible' as const;
export const B1_REFERRAL_ENGINE_METRIC_A4_POLICY_DENIED =
  'b1.referral-engine.a4-policy-denied' as const;
export const B1_REFERRAL_ENGINE_METRIC_A3_BINDING_INVALID =
  'b1.referral-engine.a3-binding-invalid' as const;
export const B1_REFERRAL_ENGINE_METRIC_A5_LEDGER_INVARIANT_BROKEN =
  'b1.referral-engine.a5-ledger-invariant-broken' as const;
export const B1_REFERRAL_ENGINE_METRIC_A6_PARTNER_INCOMPATIBLE =
  'b1.referral-engine.a6-partner-incompatible' as const;
export const B1_REFERRAL_ENGINE_METRIC_A7_PRODUCT_INCOMPATIBLE =
  'b1.referral-engine.a7-product-incompatible' as const;
export const B1_REFERRAL_ENGINE_METRIC_CATALOG_INCOMPATIBLE =
  'b1.referral-engine.catalog-incompatible' as const;
export const B1_REFERRAL_ENGINE_METRIC_CATALOG_MISSING =
  'b1.referral-engine.catalog-missing' as const;
export const B1_REFERRAL_ENGINE_METRIC_DECISION_NOT_FOUND =
  'b1.referral-engine.decision-not-found' as const;
export const B1_REFERRAL_ENGINE_METRIC_DECISION_INCOMPATIBLE =
  'b1.referral-engine.decision-incompatible' as const;
export const B1_REFERRAL_ENGINE_METRIC_BILLING_DOCUMENT_NOT_FOUND =
  'b1.referral-engine.billing-document-not-found' as const;
export const B1_REFERRAL_ENGINE_METRIC_BILLING_DOCUMENT_INCOMPATIBLE =
  'b1.referral-engine.billing-document-incompatible' as const;
export const B1_REFERRAL_ENGINE_METRIC_CAMPAIGN_DECISION_NOT_FOUND =
  'b1.referral-engine.campaign-decision-not-found' as const;
export const B1_REFERRAL_ENGINE_METRIC_CAMPAIGN_DECISION_INCOMPATIBLE =
  'b1.referral-engine.campaign-decision-incompatible' as const;
export const B1_REFERRAL_ENGINE_METRIC_PROMOTION_DECISION_NOT_FOUND =
  'b1.referral-engine.promotion-decision-not-found' as const;
export const B1_REFERRAL_ENGINE_METRIC_PROMOTION_DECISION_INCOMPATIBLE =
  'b1.referral-engine.promotion-decision-incompatible' as const;
export const B1_REFERRAL_ENGINE_METRIC_COUPON_DECISION_NOT_FOUND =
  'b1.referral-engine.coupon-decision-not-found' as const;
export const B1_REFERRAL_ENGINE_METRIC_COUPON_DECISION_INCOMPATIBLE =
  'b1.referral-engine.coupon-decision-incompatible' as const;

export const B1_REFERRAL_ENGINE_METRICS = [
  B1_REFERRAL_ENGINE_METRIC_REFERRAL,
  B1_REFERRAL_ENGINE_METRIC_CASHBACK,
  B1_REFERRAL_ENGINE_METRIC_LOYALTY,
  B1_REFERRAL_ENGINE_METRIC_REPLAYED,
  B1_REFERRAL_ENGINE_METRIC_CONFLICT,
  B1_REFERRAL_ENGINE_METRIC_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_METRIC_QUERY_UNAVAILABLE,
  B1_REFERRAL_ENGINE_METRIC_IN_PROGRESS,
  B1_REFERRAL_ENGINE_METRIC_REPLAY_CONFLICT,
  B1_REFERRAL_ENGINE_METRIC_REPLAY_EXPIRED,
  B1_REFERRAL_ENGINE_METRIC_NUMBER_CONFLICT,
  B1_REFERRAL_ENGINE_METRIC_EXPIRED,
  B1_REFERRAL_ENGINE_METRIC_USAGE_LIMIT_EXCEEDED,
  B1_REFERRAL_ENGINE_METRIC_NOT_APPLICABLE,
  B1_REFERRAL_ENGINE_METRIC_HIERARCHY_INVALID,
  B1_REFERRAL_ENGINE_METRIC_QUALIFICATION_INSUFFICIENT,
  B1_REFERRAL_ENGINE_METRIC_TIER_INSUFFICIENT,
  B1_REFERRAL_ENGINE_METRIC_POINT_POLICY_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_METRIC_A4_POLICY_DENIED,
  B1_REFERRAL_ENGINE_METRIC_A3_BINDING_INVALID,
  B1_REFERRAL_ENGINE_METRIC_A5_LEDGER_INVARIANT_BROKEN,
  B1_REFERRAL_ENGINE_METRIC_A6_PARTNER_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_METRIC_A7_PRODUCT_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_METRIC_CATALOG_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_METRIC_CATALOG_MISSING,
  B1_REFERRAL_ENGINE_METRIC_DECISION_NOT_FOUND,
  B1_REFERRAL_ENGINE_METRIC_DECISION_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_METRIC_BILLING_DOCUMENT_NOT_FOUND,
  B1_REFERRAL_ENGINE_METRIC_BILLING_DOCUMENT_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_METRIC_CAMPAIGN_DECISION_NOT_FOUND,
  B1_REFERRAL_ENGINE_METRIC_CAMPAIGN_DECISION_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_METRIC_PROMOTION_DECISION_NOT_FOUND,
  B1_REFERRAL_ENGINE_METRIC_PROMOTION_DECISION_INCOMPATIBLE,
  B1_REFERRAL_ENGINE_METRIC_COUPON_DECISION_NOT_FOUND,
  B1_REFERRAL_ENGINE_METRIC_COUPON_DECISION_INCOMPATIBLE,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * classification level vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_CLASSIFICATION_LEVELS = [
  'PUBLIC',
  'INTERNAL',
  'CONFIDENTIAL',
  'RESTRICTED',
  'HIGHLY_RESTRICTED',
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * data control classifications (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_DATA_CONTROL_CLASSIFICATIONS = [
  'PUBLIC',
  'INTERNAL',
  'CONFIDENTIAL',
  'RESTRICTED',
  'HIGHLY_RESTRICTED',
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * rule kind vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_RULE_KIND_A3_BINDING_RECHECK = 'A3_BINDING_RECHECK' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A4_POLICY_CURRENTNESS = 'A4_POLICY_CURRENTNESS' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A4_POLICY_OBLIGATION = 'A4_POLICY_OBLIGATION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A4_POLICY_REEVALUATION =
  'A4_POLICY_REEVALUATION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A4_POLICY_LIMIT = 'A4_POLICY_LIMIT' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A5_LEDGER_ACCOUNT_STATE =
  'A5_LEDGER_ACCOUNT_STATE' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A5_LEDGER_POSTING_BOUNDARY =
  'A5_LEDGER_POSTING_BOUNDARY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A5_FINANCIAL_INVARIANTS =
  'A5_FINANCIAL_INVARIANTS' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A6_PARTNER_STATE = 'A6_PARTNER_STATE' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A6_PARTNER_CAPABILITY_VERSION =
  'A6_PARTNER_CAPABILITY_VERSION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A6T08_SETTLEMENT_SUSPENSE_COMPENSATING =
  'A6T08_SETTLEMENT_SUSPENSE_COMPENSATING' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A6T09_EXTERNAL_RECONCILIATION =
  'A6T09_EXTERNAL_RECONCILIATION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A7_PRODUCT_CATALOG = 'A7_PRODUCT_CATALOG' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A7_PRODUCT_BOUNDARY = 'A7_PRODUCT_BOUNDARY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A7T04_PRODUCT_CUSTOMER_BINDING =
  'A7T04_PRODUCT_CUSTOMER_BINDING' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A7T05_PRODUCT_COMMAND_OPERATION =
  'A7T05_PRODUCT_COMMAND_OPERATION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A7T06_PRODUCT_NOTIFICATION =
  'A7T06_PRODUCT_NOTIFICATION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A7T07_PRODUCT_LIFECYCLE =
  'A7T07_PRODUCT_LIFECYCLE' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A7T08_PRODUCT_FINANCIAL_EFFECT =
  'A7T08_PRODUCT_FINANCIAL_EFFECT' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A7T09_PRODUCT_RECONCILIATION =
  'A7T09_PRODUCT_RECONCILIATION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_A7T10_PRODUCT_DATA_MINIMIZATION =
  'A7T10_PRODUCT_DATA_MINIMIZATION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_LOOKUP =
  'B1_COMMERCIAL_CATALOG_LOOKUP' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_COMPATIBILITY =
  'B1_COMMERCIAL_CATALOG_COMPATIBILITY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PLAN =
  'B1_COMMERCIAL_CATALOG_PLAN' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_TIER =
  'B1_COMMERCIAL_CATALOG_TIER' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_ENTITLEMENT =
  'B1_COMMERCIAL_CATALOG_ENTITLEMENT' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PACKAGE =
  'B1_COMMERCIAL_CATALOG_PACKAGE' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_BUNDLE =
  'B1_COMMERCIAL_CATALOG_BUNDLE' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_SUBSCRIPTION =
  'B1_COMMERCIAL_CATALOG_SUBSCRIPTION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_FEATURE_FLAG =
  'B1_COMMERCIAL_CATALOG_FEATURE_FLAG' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT =
  'B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PRICING =
  'B1_COMMERCIAL_CATALOG_PRICING' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_LOOKUP =
  'B1_COMMERCIAL_DECISION_LOOKUP' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_COMPATIBILITY =
  'B1_COMMERCIAL_DECISION_COMPATIBILITY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_REPLAY =
  'B1_COMMERCIAL_DECISION_REPLAY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_LOOKUP =
  'B1_BILLING_ENGINE_DOCUMENT_LOOKUP' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_COMPATIBILITY =
  'B1_BILLING_ENGINE_DOCUMENT_COMPATIBILITY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_REPLAY =
  'B1_BILLING_ENGINE_DOCUMENT_REPLAY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_LOOKUP =
  'B1_CAMPAIGN_DECISION_LOOKUP' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_COMPATIBILITY =
  'B1_CAMPAIGN_DECISION_COMPATIBILITY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_REPLAY =
  'B1_CAMPAIGN_DECISION_REPLAY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_LOOKUP =
  'B1_PROMOTION_DECISION_LOOKUP' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_COMPATIBILITY =
  'B1_PROMOTION_DECISION_COMPATIBILITY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_REPLAY =
  'B1_PROMOTION_DECISION_REPLAY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COUPON_DECISION_LOOKUP =
  'B1_COUPON_DECISION_LOOKUP' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COUPON_DECISION_COMPATIBILITY =
  'B1_COUPON_DECISION_COMPATIBILITY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_COUPON_DECISION_REPLAY =
  'B1_COUPON_DECISION_REPLAY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_CAMPAIGN =
  'B1_REFERRAL_ENGINE_REFERRAL_CAMPAIGN' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_PROGRAM =
  'B1_REFERRAL_ENGINE_REFERRAL_PROGRAM' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_ELIGIBILITY =
  'B1_REFERRAL_ENGINE_REFERRAL_ELIGIBILITY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_RELATIONSHIP =
  'B1_REFERRAL_ENGINE_REFERRAL_RELATIONSHIP' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_HIERARCHY =
  'B1_REFERRAL_ENGINE_REFERRAL_HIERARCHY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_QUALIFICATION =
  'B1_REFERRAL_ENGINE_REFERRAL_QUALIFICATION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_REWARD_DECISION =
  'B1_REFERRAL_ENGINE_REFERRAL_REWARD_DECISION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_CASHBACK_ELIGIBILITY =
  'B1_REFERRAL_ENGINE_CASHBACK_ELIGIBILITY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_CASHBACK_CAMPAIGN =
  'B1_REFERRAL_ENGINE_CASHBACK_CAMPAIGN' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_DECISION =
  'B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_DECISION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_CASHBACK_RULE_EVALUATION =
  'B1_REFERRAL_ENGINE_CASHBACK_RULE_EVALUATION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_LOYALTY_PROGRAM =
  'B1_REFERRAL_ENGINE_LOYALTY_PROGRAM' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_LOYALTY_TIER =
  'B1_REFERRAL_ENGINE_LOYALTY_TIER' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_LOYALTY_EARNING_DECISION =
  'B1_REFERRAL_ENGINE_LOYALTY_EARNING_DECISION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_LOYALTY_REDEMPTION_ELIGIBILITY_DECISION =
  'B1_REFERRAL_ENGINE_LOYALTY_REDEMPTION_ELIGIBILITY_DECISION' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_LOYALTY_POINT_POLICY =
  'B1_REFERRAL_ENGINE_LOYALTY_POINT_POLICY' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_NUMBER_DETERMINISTIC =
  'B1_REFERRAL_ENGINE_NUMBER_DETERMINISTIC' as const;
export const B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_DOCUMENT_VERSION =
  'B1_REFERRAL_ENGINE_DOCUMENT_VERSION' as const;

export const B1_REFERRAL_ENGINE_RULE_KINDS = [
  B1_REFERRAL_ENGINE_RULE_KIND_A4_POLICY_LIMIT,
  B1_REFERRAL_ENGINE_RULE_KIND_A4_POLICY_OBLIGATION,
  B1_REFERRAL_ENGINE_RULE_KIND_A4_POLICY_CURRENTNESS,
  B1_REFERRAL_ENGINE_RULE_KIND_A4_POLICY_REEVALUATION,
  B1_REFERRAL_ENGINE_RULE_KIND_A3_BINDING_RECHECK,
  B1_REFERRAL_ENGINE_RULE_KIND_A5_LEDGER_ACCOUNT_STATE,
  B1_REFERRAL_ENGINE_RULE_KIND_A5_LEDGER_POSTING_BOUNDARY,
  B1_REFERRAL_ENGINE_RULE_KIND_A5_FINANCIAL_INVARIANTS,
  B1_REFERRAL_ENGINE_RULE_KIND_A6_PARTNER_STATE,
  B1_REFERRAL_ENGINE_RULE_KIND_A6_PARTNER_CAPABILITY_VERSION,
  B1_REFERRAL_ENGINE_RULE_KIND_A6T08_SETTLEMENT_SUSPENSE_COMPENSATING,
  B1_REFERRAL_ENGINE_RULE_KIND_A6T09_EXTERNAL_RECONCILIATION,
  B1_REFERRAL_ENGINE_RULE_KIND_A7_PRODUCT_CATALOG,
  B1_REFERRAL_ENGINE_RULE_KIND_A7_PRODUCT_BOUNDARY,
  B1_REFERRAL_ENGINE_RULE_KIND_A7T04_PRODUCT_CUSTOMER_BINDING,
  B1_REFERRAL_ENGINE_RULE_KIND_A7T05_PRODUCT_COMMAND_OPERATION,
  B1_REFERRAL_ENGINE_RULE_KIND_A7T06_PRODUCT_NOTIFICATION,
  B1_REFERRAL_ENGINE_RULE_KIND_A7T07_PRODUCT_LIFECYCLE,
  B1_REFERRAL_ENGINE_RULE_KIND_A7T08_PRODUCT_FINANCIAL_EFFECT,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_LOOKUP,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_COMPATIBILITY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PLAN,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_TIER,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_ENTITLEMENT,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PACKAGE,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_BUNDLE,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_SUBSCRIPTION,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_FEATURE_FLAG,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_DYNAMIC_LIMIT,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_CATALOG_PRICING,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_LOOKUP,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_COMPATIBILITY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COMMERCIAL_DECISION_REPLAY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_LOOKUP,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_COMPATIBILITY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_BILLING_ENGINE_DOCUMENT_REPLAY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_LOOKUP,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_COMPATIBILITY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_CAMPAIGN_DECISION_REPLAY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_LOOKUP,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_COMPATIBILITY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_PROMOTION_DECISION_REPLAY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COUPON_DECISION_LOOKUP,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COUPON_DECISION_COMPATIBILITY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_COUPON_DECISION_REPLAY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_CAMPAIGN,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_PROGRAM,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_ELIGIBILITY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_RELATIONSHIP,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_HIERARCHY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_QUALIFICATION,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_REFERRAL_REWARD_DECISION,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_CASHBACK_ELIGIBILITY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_CASHBACK_CAMPAIGN,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_CASHBACK_CALCULATION_DECISION,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_CASHBACK_RULE_EVALUATION,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_LOYALTY_PROGRAM,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_LOYALTY_TIER,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_LOYALTY_EARNING_DECISION,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_LOYALTY_REDEMPTION_ELIGIBILITY_DECISION,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_LOYALTY_POINT_POLICY,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_NUMBER_DETERMINISTIC,
  B1_REFERRAL_ENGINE_RULE_KIND_B1_REFERRAL_ENGINE_DOCUMENT_VERSION,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * rule outcome vocabulary (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_RULE_OUTCOME_PASS = 'PASS' as const;
export const B1_REFERRAL_ENGINE_RULE_OUTCOME_FAIL = 'FAIL' as const;
export const B1_REFERRAL_ENGINE_RULE_OUTCOME_SKIP = 'SKIP' as const;
export const B1_REFERRAL_ENGINE_RULE_OUTCOME_NOT_APPLICABLE = 'NOT_APPLICABLE' as const;

export const B1_REFERRAL_ENGINE_RULE_OUTCOMES = [
  B1_REFERRAL_ENGINE_RULE_OUTCOME_PASS,
  B1_REFERRAL_ENGINE_RULE_OUTCOME_FAIL,
  B1_REFERRAL_ENGINE_RULE_OUTCOME_SKIP,
  B1_REFERRAL_ENGINE_RULE_OUTCOME_NOT_APPLICABLE,
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * compatibility rule identifiers (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_COMPATIBILITY_RULE_IDS = [
  'B1_REFERRAL_RULE_SCOPE_KEY_REQUIRED',
  'B1_REFERRAL_RULE_SCOPE_VERSION_REQUIRED',
  'B1_REFERRAL_RULE_CURRENCY_REQUIRED',
  'B1_REFERRAL_RULE_ACCOUNTING_UNIT_REQUIRED',
  'B1_REFERRAL_RULE_PRODUCT_DEPENDENCY_REQUIRED',
  'B1_REFERRAL_RULE_PARTNER_DEPENDENCY_REQUIRED',
  'B1_REFERRAL_RULE_DOCUMENT_VERSION_REQUIRED',
  'B1_REFERRAL_RULE_DECISION_REFERENCES_REQUIRED',
  'B1_REFERRAL_RULE_BILLING_DOCUMENT_REFERENCE_REQUIRED',
  'B1_REFERRAL_RULE_NUMBER_DETERMINISTIC',
  'B1_REFERRAL_RULE_NO_CROSS_CATALOG_REFERENCES',
  'B1_REFERRAL_RULE_NO_CROSS_SCOPE_NEGOTIATION',
  'B1_REFERRAL_RULE_PERIOD_VERSION_REQUIRED',
  'B1_REFERRAL_RULE_RELATIONSHIP_HIERARCHY_VALID',
  'B1_REFERRAL_RULE_QUALIFICATION_CRITERIA_VALID',
  'B1_REFERRAL_RULE_TIER_POLICY_VALID',
  'B1_REFERRAL_RULE_USAGE_LIMITS_VALID',
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * consumer contract identifiers (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_CONSUMER_CONTRACT_IDS = [
  'B1_REFERRAL_CONSUMER_CONTRACT_A1',
  'B1_REFERRAL_CONSUMER_CONTRACT_A2',
  'B1_REFERRAL_CONSUMER_CONTRACT_A3',
  'B1_REFERRAL_CONSUMER_CONTRACT_A4',
  'B1_REFERRAL_CONSUMER_CONTRACT_A5',
  'B1_REFERRAL_CONSUMER_CONTRACT_A6',
  'B1_REFERRAL_CONSUMER_CONTRACT_A7',
  'B1_REFERRAL_CONSUMER_CONTRACT_A6T10',
  'B1_REFERRAL_CONSUMER_CONTRACT_A6T09',
  'B1_REFERRAL_CONSUMER_CONTRACT_A7T09',
  'B1_REFERRAL_CONSUMER_CONTRACT_A7T08',
  'B1_REFERRAL_CONSUMER_CONTRACT_A7T06',
  'B1_REFERRAL_CONSUMER_CONTRACT_B1_COMMERCIAL_CATALOG',
  'B1_REFERRAL_CONSUMER_CONTRACT_B1_COMMERCIAL_DECISION',
  'B1_REFERRAL_CONSUMER_CONTRACT_B1_BILLING_ENGINE',
  'B1_REFERRAL_CONSUMER_CONTRACT_B1_CAMPAIGN_ENGINE',
  'B1_REFERRAL_CONSUMER_CONTRACT_OPERATIONS',
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * version negotiation rule identifiers (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_VERSION_NEGOTIATION_RULE_IDS = [
  'B1_REFERRAL_VERSION_RULE_SCOPE_VERSION_EXACT_MATCH',
  'B1_REFERRAL_VERSION_RULE_DOCUMENT_VERSION_EXACT_MATCH',
  'B1_REFERRAL_VERSION_RULE_PERIOD_VERSION_EXACT_MATCH',
  'B1_REFERRAL_VERSION_RULE_NO_CROSS_CATALOG_NEGOTIATION',
  'B1_REFERRAL_VERSION_RULE_NO_CROSS_BILLING_ENGINE_NEGOTIATION',
  'B1_REFERRAL_VERSION_RULE_NO_CROSS_CAMPAIGN_ENGINE_NEGOTIATION',
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * replay rule identifiers (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_REPLAY_RULE_IDS = [
  'B1_REFERRAL_REPLAY_RULE_WINDOW_86400',
  'B1_REFERRAL_REPLAY_RULE_EXACT_MATCH_REQUIRED',
  'B1_REFERRAL_REPLAY_RULE_IDEMPOTENT',
  'B1_REFERRAL_REPLAY_RULE_AUDIT_TRACED',
  'B1_REFERRAL_REPLAY_RULE_EXPIRES_AFTER_WINDOW',
  'B1_REFERRAL_REPLAY_RULE_INHERITS_A1_A7',
  'B1_REFERRAL_REPLAY_RULE_INHERITS_B1T03',
  'B1_REFERRAL_REPLAY_RULE_INHERITS_B1T04',
  'B1_REFERRAL_REPLAY_RULE_INHERITS_B1T05',
  'B1_REFERRAL_REPLAY_RULE_INHERITS_B1T06',
  'B1_REFERRAL_REPLAY_RULE_NUMBER_DETERMINISTIC',
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * declared dependencies (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_DECLARED_DEPENDENCIES = [
  'A1-CANONICAL-IDENTITY',
  'A2-AUTHORIZATION-CONTEXT',
  'A3-CUSTOMER-FINANCIAL-ACCOUNT-BINDING',
  'A4-PRODUCT-POLICY-DECISION',
  'A5-LEDGER',
  'A6-PARTNER-ADAPTER',
  'A6T05-EXTERNAL-OPERATION',
  'A6T08-SETTLEMENT-SUSPENSE-COMPENSATING',
  'A6T09-EXTERNAL-RECONCILIATION',
  'A6T10-DATA-CLASSIFICATION',
  'A7-PRODUCT-CATALOG',
  'A7-PRODUCT-POLICY-PROFILE',
  'A7T04-PRODUCT-CUSTOMER-BINDING',
  'A7T05-PRODUCT-COMMAND-OPERATION',
  'A7T06-PRODUCT-NOTIFICATION-DELIVERY',
  'A7T07-PRODUCT-LIFECYCLE',
  'A7T08-PRODUCT-FINANCIAL-EFFECT',
  'A7T09-PRODUCT-RECONCILIATION',
  'A7T10-PRODUCT-DATA-MINIMIZATION',
  'B1-COMMERCIAL-CATALOG',
  'B1-COMMERCIAL-DECISION',
  'B1-BILLING-ENGINE',
  'B1-CAMPAIGN-ENGINE',
  'CUSTOMER-PREFERENCE',
  'OPERATIONS-AUDIT',
  'OPERATIONS-IDEMPOTENCY',
  'OPERATIONS-OUTBOX',
  'OPERATIONS-METRICS',
  'OPERATIONS-DIAGNOSTICS',
  'WALLET',
  'LEDGER',
  'RECONCILIATION',
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * prohibited dependencies (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07).
 */
export const B1_REFERRAL_ENGINE_PROHIBITED_DEPENDENCIES = [
  'B1_REVENUE_RECOGNITION_ENGINE',
  'B1_TAX_ENGINE',
  'B1_COST_ACCOUNTING_ENGINE',
  'B1_PROFITABILITY_ENGINE',
  'B1_ANALYTICS_ENGINE',
  'B1_COMMERCIAL_RECONCILIATION_ENGINE',
  'B1_COMMERCIAL_DATA_CLASSIFICATION_REGISTRY',
  'B1_COMMERCIAL_IDEMPOTENCY_AUTHORITY',
  'B1_COMMERCIAL_AUDIT_AUTHORITY',
  'B1_COMMERCIAL_APPROVAL_AUTHORITY',
  'B1_COMMERCIAL_FEATURE_FLAG_AUTHORITY',
  'B1_COMMERCIAL_RELEASE_GATE',
  'A5_LEDGER_POSTING_AUTHORITY',
  'A5_LEDGER_JOURNAL_AUTHORITY',
  'A5_FINANCIAL_INVARIANTS_OVERRIDE_AUTHORITY',
  'A6T08_SETTLEMENT_AUTHORITY',
  'A6T08_SUSPENSE_AUTHORITY',
  'A6T08_COMPENSATING_AUTHORITY',
  'A6T09_RECONCILIATION_AUTHORITY',
  'A7T06_NOTIFICATION_DISPATCH_AUTHORITY',
  'A7T08_PRODUCT_FINANCIAL_EFFECT_AUTHORITY',
  'CASHBACK_REDEMPTION_AUTHORITY',
  'LOYALTY_BALANCE_AUTHORITY',
  'REFERRAL_REWARD_AUTHORITY',
] as const;

/**
 * B1 referral engine, cashback engine, and loyalty engine
 * prohibited adjacent scopes (frozen by
 * `docs/B1-IMPLEMENTATION-PLAN.md` §8 B1T07 and re-asserted from
 * the B1T03 catalog).
 */
export const B1_REFERRAL_ENGINE_PROHIBITED_ADJACENT_SCOPES = [
  'commercial.virtual-account.outbound-settlement',
  'commercial.savings.inbound-funding',
  'commercial.lending.inbound-funding',
  'commercial.bills.inbound-funding',
  'commercial.airtime.inbound-funding',
  'commercial.qr-merchant.inbound-funding',
  'commercial.agent-assisted.inbound-funding',
  'commercial.card.inbound-funding',
  'commercial.bulk-payroll.inbound-funding',
  'commercial.fx.inbound-funding',
  'commercial.cross-region.inbound-funding',
  'commercial.cross-currency.inbound-funding',
  'commercial.public-channel.inbound-funding',
  'commercial.marketing-consent.inbound-funding',
] as const;
