export enum PolicyDecisionState {
  ALLOW = 'ALLOW',
  ALLOW_WITH_LIMITS = 'ALLOW_WITH_LIMITS',
  PENDING_REVIEW = 'PENDING_REVIEW',
  DENY = 'DENY',
  SUSPEND = 'SUSPEND',
}

export enum PolicySourceClass {
  CUSTOMER = 'CUSTOMER',
  ONBOARDING = 'ONBOARDING',
  ELIGIBILITY = 'ELIGIBILITY',
  RESTRICTIONS = 'RESTRICTIONS',
  LIMITS = 'LIMITS',
  ENROLLMENT = 'ENROLLMENT',
  PERMISSIONS = 'PERMISSIONS',
  RISK = 'RISK',
  COMPLIANCE = 'COMPLIANCE',
  ACCOUNT_BINDING = 'ACCOUNT_BINDING',
  AUTHORIZATION = 'AUTHORIZATION',
}

export enum PolicyEvidenceFreshnessState {
  CURRENT = 'CURRENT',
  STALE = 'STALE',
  MISSING = 'MISSING',
  DELETED = 'DELETED',
  CONFLICTING = 'CONFLICTING',
  UNAVAILABLE = 'UNAVAILABLE',
  RESTRICTED = 'RESTRICTED',
}

export enum PolicyCollectionStatus {
  COMPLETE = 'COMPLETE',
  INCOMPLETE = 'INCOMPLETE',
  UNAVAILABLE = 'UNAVAILABLE',
}

export enum PolicyLimitEvaluationStatus {
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  WITHIN_LIMITS = 'WITHIN_LIMITS',
  EXCEEDED = 'EXCEEDED',
  INCOMPATIBLE = 'INCOMPATIBLE',
  UNAVAILABLE = 'UNAVAILABLE',
}

export enum PolicyRequirementMode {
  REQUIRED_CURRENT = 'REQUIRED_CURRENT',
  REQUIRED_ACTIVE = 'REQUIRED_ACTIVE',
  REQUIRED_IF_CONTEXT = 'REQUIRED_IF_CONTEXT',
  OPTIONAL_REFERENCE = 'OPTIONAL_REFERENCE',
  NOT_USED = 'NOT_USED',
}

export enum PolicyEnrollmentRequirement {
  REQUIRED_ACTIVE = 'REQUIRED_ACTIVE',
  REQUIRED_CURRENT = 'REQUIRED_CURRENT',
  NOT_REQUIRED = 'NOT_REQUIRED',
  ENROLLMENT_ACTION = 'ENROLLMENT_ACTION',
}

export enum PolicyPermissionRequirement {
  REQUIRED_ENABLED = 'REQUIRED_ENABLED',
  REQUIRED_CURRENT = 'REQUIRED_CURRENT',
  NOT_REQUIRED = 'NOT_REQUIRED',
}

export enum PolicyRiskRequirement {
  CURRENT_REQUIRED = 'CURRENT_REQUIRED',
  PROFILE_CONTROLLED = 'PROFILE_CONTROLLED',
  NOT_REQUIRED = 'NOT_REQUIRED',
}

export enum PolicyComplianceRequirement {
  CURRENT_REQUIRED = 'CURRENT_REQUIRED',
  PROFILE_CONTROLLED = 'PROFILE_CONTROLLED',
  NOT_REQUIRED = 'NOT_REQUIRED',
}

export enum PolicyAccountBindingRequirement {
  ACTIVE_REQUIRED = 'ACTIVE_REQUIRED',
  CURRENT_REQUIRED = 'CURRENT_REQUIRED',
  REQUIRED_IF_CONTEXT = 'REQUIRED_IF_CONTEXT',
  NOT_REQUIRED = 'NOT_REQUIRED',
}

export enum PolicyLimitRequirement {
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  CONFIGURATION_REQUIRED = 'CONFIGURATION_REQUIRED',
  USAGE_REQUIRED = 'USAGE_REQUIRED',
  CONFIGURATION_AND_USAGE_REQUIRED = 'CONFIGURATION_AND_USAGE_REQUIRED',
}

export enum PolicyLimitDimension {
  SINGLE_TRANSACTION_AMOUNT = 'SINGLE_TRANSACTION_AMOUNT',
  DAILY_TRANSACTION_COUNT = 'DAILY_TRANSACTION_COUNT',
  DAILY_TRANSACTION_AMOUNT = 'DAILY_TRANSACTION_AMOUNT',
  MONTHLY_TRANSACTION_AMOUNT = 'MONTHLY_TRANSACTION_AMOUNT',
  WALLET_BALANCE = 'WALLET_BALANCE',
}
