export enum PolicyProfileLifecycleState {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  RETIRED = 'RETIRED',
  REJECTED = 'REJECTED',
  ABANDONED = 'ABANDONED',
}

export enum PolicyRetentionClass {
  POLICY_HISTORY = 'A4_POLICY_HISTORY',
  EVIDENCE_SNAPSHOT = 'A4_EVIDENCE_SNAPSHOT',
}

export enum PolicyReplayOutcome {
  REPLAY_EXACT = 'REPLAY_EXACT',
  REPLAY_REFERENCE_ONLY = 'REPLAY_REFERENCE_ONLY',
  REPLAY_UNAVAILABLE = 'REPLAY_UNAVAILABLE',
  REPLAY_CONFLICT = 'REPLAY_CONFLICT',
  REPLAY_INTEGRITY_MISMATCH = 'REPLAY_INTEGRITY_MISMATCH',
}
