export enum PolicyCurrentnessState {
  CURRENT = 'CURRENT',
  NOT_FOUND = 'NOT_FOUND',
  EXPIRED = 'EXPIRED',
  REVIEW_DUE = 'REVIEW_DUE',
  STALE_EVIDENCE = 'STALE_EVIDENCE',
  MISSING_EVIDENCE = 'MISSING_EVIDENCE',
  DELETED_EVIDENCE = 'DELETED_EVIDENCE',
  CONFLICTING_EVIDENCE = 'CONFLICTING_EVIDENCE',
  UNAVAILABLE_EVIDENCE = 'UNAVAILABLE_EVIDENCE',
  RESTRICTED_EVIDENCE = 'RESTRICTED_EVIDENCE',
  POLICY_VERSION_RETIRED = 'POLICY_VERSION_RETIRED',
  POLICY_VERSION_SUPERSEDED = 'POLICY_VERSION_SUPERSEDED',
  POLICY_VERSION_UNAVAILABLE = 'POLICY_VERSION_UNAVAILABLE',
  UNKNOWN = 'UNKNOWN',
}

export enum PolicyReevaluationState {
  COMPLETED = 'COMPLETED',
  REPLAYED = 'REPLAYED',
  IN_PROGRESS = 'IN_PROGRESS',
  RETRY_SCHEDULED = 'RETRY_SCHEDULED',
  BLOCKED = 'BLOCKED',
  UNKNOWN_OUTCOME = 'UNKNOWN_OUTCOME',
}

export enum PolicyRecoveryState {
  NONE = 'NONE',
  RECOVERED = 'RECOVERED',
  REEVALUATION_REQUIRED = 'REEVALUATION_REQUIRED',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
  RETRY_REQUIRED = 'RETRY_REQUIRED',
  BLOCKED = 'BLOCKED',
  UNKNOWN_OUTCOME = 'UNKNOWN_OUTCOME',
}

export enum PolicyReevaluationTrigger {
  EXPIRED = 'EXPIRED',
  REVIEW_DUE = 'REVIEW_DUE',
  SOURCE_CHANGED = 'SOURCE_CHANGED',
  STALE_EVIDENCE = 'STALE_EVIDENCE',
  MISSING_EVIDENCE = 'MISSING_EVIDENCE',
  CONFLICTING_EVIDENCE = 'CONFLICTING_EVIDENCE',
  UNAVAILABLE_EVIDENCE = 'UNAVAILABLE_EVIDENCE',
  POLICY_VERSION_SUPERSEDED = 'POLICY_VERSION_SUPERSEDED',
  MANUAL = 'MANUAL',
}

export enum PolicyProfileVersionState {
  ACTIVE = 'ACTIVE',
  RETIRED = 'RETIRED',
  REJECTED = 'REJECTED',
  UNKNOWN = 'UNKNOWN',
}
