export enum WithdrawalStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum WithdrawalFailureCode {
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  WALLET_NOT_ACTIVE = 'WALLET_NOT_ACTIVE',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  SETTLEMENT_REJECTED = 'SETTLEMENT_REJECTED',
}
