export enum TransferStatus {
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum TransferDirection {
  SENT = 'SENT',
  RECEIVED = 'RECEIVED',
}

export enum TransferFailureCode {
  SOURCE_WALLET_NOT_FOUND = 'SOURCE_WALLET_NOT_FOUND',
  DESTINATION_WALLET_NOT_FOUND = 'DESTINATION_WALLET_NOT_FOUND',
  SELF_TRANSFER = 'SELF_TRANSFER',
  WALLET_NOT_ACTIVE = 'WALLET_NOT_ACTIVE',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  LEDGER_REJECTED = 'LEDGER_REJECTED',
}
