export enum TransferStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PENDING_RECOVERY = 'PENDING_RECOVERY',
  UNKNOWN = 'UNKNOWN',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum TransferDirection {
  SENT = 'SENT',
  RECEIVED = 'RECEIVED',
}

export enum TransferFailureCode {
  SOURCE_WALLET_NOT_FOUND = 'SOURCE_WALLET_NOT_FOUND',
  DESTINATION_WALLET_NOT_FOUND = 'DESTINATION_WALLET_NOT_FOUND',
  SELF_TRANSFER = 'SELF_TRANSFER',
  WALLET_NOT_ACTIVE = 'WALLET_NOT_ACTIVE',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  LEDGER_REJECTED = 'LEDGER_REJECTED',
  COMMAND_REJECTED = 'COMMAND_REJECTED',
  POLICY_NOT_EXECUTABLE = 'POLICY_NOT_EXECUTABLE',
  BINDING_NOT_ACTIVE = 'BINDING_NOT_ACTIVE',
  PERSISTENCE_REJECTED = 'PERSISTENCE_REJECTED',
  UNKNOWN_OUTCOME = 'UNKNOWN_OUTCOME',
  TRANSFER_CANCELLED = 'TRANSFER_CANCELLED',
}
