export enum DepositStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum DepositFailureCode {
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  WALLET_NOT_ACTIVE = 'WALLET_NOT_ACTIVE',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  SETTLEMENT_REJECTED = 'SETTLEMENT_REJECTED',
}
