export enum ProductGovernanceKind {
  PRODUCT_PROFILE = 'PRODUCT_PROFILE',
  PRODUCT_REQUIREMENT = 'PRODUCT_REQUIREMENT',
  PRODUCT_SCOPE = 'PRODUCT_SCOPE',
  LAUNCH_ENVELOPE = 'LAUNCH_ENVELOPE',
  SUPPORTED_COUNTRY = 'SUPPORTED_COUNTRY',
  SUPPORTED_CURRENCY = 'SUPPORTED_CURRENCY',
  PILOT_COHORT = 'PILOT_COHORT',
  CUSTOMER_SEGMENT = 'CUSTOMER_SEGMENT',
  REGULATORY_JURISDICTION = 'REGULATORY_JURISDICTION',
  REGULATORY_REQUIREMENT = 'REGULATORY_REQUIREMENT',
  BUSINESS_CAPABILITY = 'BUSINESS_CAPABILITY',
  FEATURE = 'FEATURE',
  FEATURE_FLAG = 'FEATURE_FLAG',
  LAUNCH_GATE = 'LAUNCH_GATE',
  GONO_GO_CRITERION = 'GONO_GO_CRITERION',
  PRODUCT_RISK = 'PRODUCT_RISK',
  OPERATIONAL_OWNER = 'OPERATIONAL_OWNER',
  PARTNER = 'PARTNER',
  PARTNER_EVALUATION = 'PARTNER_EVALUATION',
  SERVICE_LEVEL_OBJECTIVE = 'SERVICE_LEVEL_OBJECTIVE',
  SERVICE_LEVEL_INDICATOR = 'SERVICE_LEVEL_INDICATOR',
  ROLLBACK_STRATEGY = 'ROLLBACK_STRATEGY',
  SUCCESS_METRIC = 'SUCCESS_METRIC',
  PRODUCT_CONFIGURATION = 'PRODUCT_CONFIGURATION',
  LAUNCH_CHECKLIST = 'LAUNCH_CHECKLIST',
  PRODUCT_VERSION_METADATA = 'PRODUCT_VERSION_METADATA',
}

export enum ProductGovernanceStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  APPROVED = 'APPROVED',
  BLOCKED = 'BLOCKED',
  COMPLETE = 'COMPLETE',
  DEPRECATED = 'DEPRECATED',
}

export enum LaunchReadinessStatus {
  PASS = 'PASS',
  WARNING = 'WARNING',
  FAIL = 'FAIL',
}
