export enum ExternalDataHandlingLevel {
  PUBLIC = 'PUBLIC',
  INTERNAL = 'INTERNAL',
  CONFIDENTIAL = 'CONFIDENTIAL',
  RESTRICTED = 'RESTRICTED',
  HIGHLY_RESTRICTED = 'HIGHLY_RESTRICTED',
}

export const EXTERNAL_DATA_HANDLING_LEVELS = new Set<string>([
  ExternalDataHandlingLevel.PUBLIC,
  ExternalDataHandlingLevel.INTERNAL,
  ExternalDataHandlingLevel.CONFIDENTIAL,
  ExternalDataHandlingLevel.RESTRICTED,
  ExternalDataHandlingLevel.HIGHLY_RESTRICTED,
]);

export enum ExternalConsentSource {
  CUSTOMER_BENEFICIARY = 'CUSTOMER_BENEFICIARY',
  CUSTOMER_FUNDING_INSTRUMENT = 'CUSTOMER_FUNDING_INSTRUMENT',
  EXTERNAL_TARGET = 'EXTERNAL_TARGET',
  DERIVED = 'DERIVED',
}

export enum ExternalConsentStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
  INVALID = 'INVALID',
}

export const EXTERNAL_CONSENT_PURPOSES = new Set<string>(['OUTBOUND_BANK_SETTLEMENT']);

export const EXTERNAL_CONSENT_APPROVED_JURISDICTIONS = new Set<string>(['NG']);

export enum ExternalLegalHoldScope {
  EXTERNAL_OPERATION = 'EXTERNAL_OPERATION',
  EXTERNAL_REFERENCE = 'EXTERNAL_REFERENCE',
  EXTERNAL_CALLBACK = 'EXTERNAL_CALLBACK',
  EXTERNAL_SETTLEMENT = 'EXTERNAL_SETTLEMENT',
  EXTERNAL_SUSPENSE = 'EXTERNAL_SUSPENSE',
  EXTERNAL_AUDIT = 'EXTERNAL_AUDIT',
  EXTERNAL_OUTBOX = 'EXTERNAL_OUTBOX',
  EXTERNAL_IDEMPOTENCY = 'EXTERNAL_IDEMPOTENCY',
  EXTERNAL_DATA_CLASSIFICATION = 'EXTERNAL_DATA_CLASSIFICATION',
  EXTERNAL_CONSENT = 'EXTERNAL_CONSENT',
  EXTERNAL_DISCLOSURE = 'EXTERNAL_DISCLOSURE',
  EXTERNAL_SUPPORT_TRACE = 'EXTERNAL_SUPPORT_TRACE',
  EXTERNAL_SECRET = 'EXTERNAL_SECRET',
}

export enum ExternalLegalHoldAuthority {
  LEGAL = 'LEGAL',
  REGULATORY = 'REGULATORY',
  INVESTIGATION = 'INVESTIGATION',
  SECURITY = 'SECURITY',
  FRAUD = 'FRAUD',
  DISPUTE = 'DISPUTE',
  FINANCIAL_CONTROL = 'FINANCIAL_CONTROL',
}

export enum ExternalLegalHoldStatus {
  ACTIVE = 'ACTIVE',
  RELEASED = 'RELEASED',
}

export enum ExternalSecretCategory {
  PARTNER_CLIENT_AUTHENTICATION = 'PARTNER_CLIENT_AUTHENTICATION',
  PARTNER_REQUEST_SIGNING_KEY = 'PARTNER_REQUEST_SIGNING_KEY',
  CALLBACK_SECRET = 'CALLBACK_SECRET',
  CALLBACK_SIGNATURE = 'CALLBACK_SIGNATURE',
  PRIVATE_KEY = 'PRIVATE_KEY',
  CUSTOMER_PIN = 'CUSTOMER_PIN',
  CUSTOMER_OTP = 'CUSTOMER_OTP',
  DEVICE_FINGERPRINT_RAW = 'DEVICE_FINGERPRINT_RAW',
  RISK_NARRATIVE_RAW = 'RISK_NARRATIVE_RAW',
  COMPLIANCE_CASE_RAW = 'COMPLIANCE_CASE_RAW',
}

export const EXTERNAL_SECRET_CATEGORIES = new Set<string>(Object.values(ExternalSecretCategory));

export enum ExternalDisclosureAudience {
  SUPPORT = 'SUPPORT',
  OPERATIONS = 'OPERATIONS',
  RECONCILIATION = 'RECONCILIATION',
  FINANCE = 'FINANCE',
  COMPLIANCE = 'COMPLIANCE',
  LEGAL = 'LEGAL',
  SECURITY = 'SECURITY',
  A6_TEN_INTERNAL = 'A6_TEN_INTERNAL',
}

export const EXTERNAL_DISCLOSURE_AUDIENCES = new Set<string>(
  Object.values(ExternalDisclosureAudience),
);

export enum ExternalDataControlAction {
  CLASSIFICATION_RECORDED = 'CLASSIFICATION_RECORDED',
  CONSENT_RECORDED = 'CONSENT_RECORDED',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  RETENTION_RECORDED = 'RETENTION_RECORDED',
  HOLD_IMPOSED = 'HOLD_IMPOSED',
  HOLD_RELEASED = 'HOLD_RELEASED',
  SECRET_CLASSIFICATION_RECORDED = 'SECRET_CLASSIFICATION_RECORDED',
  DISCLOSED = 'DISCLOSED',
  DISCLOSURE_REJECTED = 'DISCLOSURE_REJECTED',
  SUPPORT_TRACE_BUILT = 'SUPPORT_TRACE_BUILT',
  PARTNER_PAYLOAD_REJECTED = 'PARTNER_PAYLOAD_REJECTED',
}

export enum ExternalDataMinimizationRejectionCode {
  CLASSIFICATION_NOT_REGISTERED = 'CLASSIFICATION_NOT_REGISTERED',
  CLASSIFICATION_LEVEL_INVALID = 'CLASSIFICATION_LEVEL_INVALID',
  CONSENT_EXPIRED = 'CONSENT_EXPIRED',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  CONSENT_PURPOSE_MISMATCH = 'CONSENT_PURPOSE_MISMATCH',
  CONSENT_JURISDICTION_MISMATCH = 'CONSENT_JURISDICTION_MISMATCH',
  CONSENT_TARGET_STALE = 'CONSENT_TARGET_STALE',
  CONSENT_GRANTOR_MISSING = 'CONSENT_GRANTOR_MISSING',
  RETENTION_HOLD_ACTIVE = 'RETENTION_HOLD_ACTIVE',
  RETENTION_BELOW_FLOOR = 'RETENTION_BELOW_FLOOR',
  RETENTION_MISSING = 'RETENTION_MISSING',
  HOLD_ALREADY_RELEASED = 'HOLD_ALREADY_RELEASED',
  HOLD_NOT_FOUND = 'HOLD_NOT_FOUND',
  HOLD_AUTHORITY_MISSING = 'HOLD_AUTHORITY_MISSING',
  HOLD_RELEASED_BY_MISSING = 'HOLD_RELEASED_BY_MISSING',
  SECRET_LEVEL_INVALID = 'SECRET_LEVEL_INVALID',
  SECRET_IN_RAW_PAYLOAD = 'SECRET_IN_RAW_PAYLOAD',
  SECRET_IN_SUPPORT_TRACE = 'SECRET_IN_SUPPORT_TRACE',
  DISCLOSURE_AUDIENCE_TOO_LOW = 'DISCLOSURE_AUDIENCE_TOO_LOW',
  DISCLOSURE_FIELD_NOT_REGISTERED = 'DISCLOSURE_FIELD_NOT_REGISTERED',
  DISCLOSURE_REJECTED_HIGHLY_RESTRICTED = 'DISCLOSURE_REJECTED_HIGHLY_RESTRICTED',
  DISCLOSURE_BEYOND_LEGAL_HOLD = 'DISCLOSURE_BEYOND_LEGAL_HOLD',
  PARTNER_PAYLOAD_REJECTED = 'PARTNER_PAYLOAD_REJECTED',
  PARTNER_PAYLOAD_MISSING_FIELD = 'PARTNER_PAYLOAD_MISSING_FIELD',
  CONSENT_REQUIRED = 'CONSENT_REQUIRED',
  DATA_CONTROL_AUDIT_FAILED = 'DATA_CONTROL_AUDIT_FAILED',
}

export enum ExternalPartnerPayloadRejectionCode {
  RAW_SECRET_PRESENT = 'RAW_SECRET_PRESENT',
  CUSTOMER_IDENTITY_PRESENT = 'CUSTOMER_IDENTITY_PRESENT',
  WALLET_IDENTITY_PRESENT = 'WALLET_IDENTITY_PRESENT',
  LEDGER_IDENTITY_PRESENT = 'LEDGER_IDENTITY_PRESENT',
  JOURNAL_IDENTITY_PRESENT = 'JOURNAL_IDENTITY_PRESENT',
  RAW_CALLBACK_SECRET = 'RAW_CALLBACK_SECRET',
  RAW_RISK_NARRATIVE = 'RAW_RISK_NARRATIVE',
  RAW_COMPLIANCE_NOTE = 'RAW_COMPLIANCE_NOTE',
  RAW_DEVICE_FINGERPRINT = 'RAW_DEVICE_FINGERPRINT',
  UNKNOWN_FIELD = 'UNKNOWN_FIELD',
}

export const EXTERNAL_DATA_MINIMIZATION_PARTNER_KEY = 'NIBSS_NIP' as const;
export const EXTERNAL_DATA_MINIMIZATION_CAPABILITY_KEY =
  'external.wallet.withdrawal.settlement' as const;
export const EXTERNAL_DATA_MINIMIZATION_CONTRACT_NAME = 'A6-EXTERNAL-DATA-MINIMIZATION' as const;
export const EXTERNAL_DATA_MINIMIZATION_CONTRACT_VERSION = 1 as const;
export const EXTERNAL_DATA_MINIMIZATION_CONTRACT_REFERENCE =
  'docs/ADR/ADR-0052-External-Rail-Data-Minimization-and-Consent.md' as const;
export const EXTERNAL_DATA_MINIMIZATION_CONTRACT_DOCUMENT =
  'docs/A6-EXTERNAL-DATA-MINIMIZATION-AND-CONSENT-CONTRACT.md' as const;
export const EXTERNAL_DATA_MINIMIZATION_OWNER = 'a6-external-data-minimization' as const;
export const EXTERNAL_DATA_MINIMIZATION_AUDIT_ENTITY_TYPE = 'A6_EXTERNAL_DATA_CONTROL' as const;
export const EXTERNAL_DATA_MINIMIZATION_DEFAULT_RETENTION_DAYS = 365;
export const EXTERNAL_DATA_MINIMIZATION_DISCLOSURE_RETENTION_DAYS = 30;
export const EXTERNAL_DATA_MINIMIZATION_SUPPORT_TRACE_RETENTION_DAYS = 90;
export const EXTERNAL_DATA_MINIMIZATION_IDEMPOTENCY_RETENTION_DAYS = 1;
export const EXTERNAL_DATA_MINIMIZATION_OUTBOX_PUBLISHED_RETENTION_DAYS = 30;
export const EXTERNAL_DATA_MINIMIZATION_MAX_KEY_LENGTH = 255;
export const EXTERNAL_DATA_MINIMIZATION_MAX_REASON_LENGTH = 255;
export const EXTERNAL_DATA_MINIMIZATION_MAX_OWNER_LENGTH = 160;
export const EXTERNAL_DATA_MINIMIZATION_MAX_FIELD_NAME_LENGTH = 200;
export const EXTERNAL_DATA_MINIMIZATION_MAX_SOURCE_DOMAIN_LENGTH = 80;
export const EXTERNAL_DATA_MINIMIZATION_MAX_DATASET_LENGTH = 120;
export const EXTERNAL_DATA_MINIMIZATION_MAX_AUDIENCE_LEVEL =
  ExternalDataHandlingLevel.HIGHLY_RESTRICTED;
export const EXTERNAL_DATA_MINIMIZATION_AUDIENCE_MAXIMUM_LEVELS: Readonly<
  Record<ExternalDisclosureAudience, ExternalDataHandlingLevel>
> = {
  [ExternalDisclosureAudience.SUPPORT]: ExternalDataHandlingLevel.CONFIDENTIAL,
  [ExternalDisclosureAudience.OPERATIONS]: ExternalDataHandlingLevel.CONFIDENTIAL,
  [ExternalDisclosureAudience.RECONCILIATION]: ExternalDataHandlingLevel.CONFIDENTIAL,
  [ExternalDisclosureAudience.FINANCE]: ExternalDataHandlingLevel.RESTRICTED,
  [ExternalDisclosureAudience.COMPLIANCE]: ExternalDataHandlingLevel.RESTRICTED,
  [ExternalDisclosureAudience.LEGAL]: ExternalDataHandlingLevel.RESTRICTED,
  [ExternalDisclosureAudience.SECURITY]: ExternalDataHandlingLevel.HIGHLY_RESTRICTED,
  [ExternalDisclosureAudience.A6_TEN_INTERNAL]: ExternalDataHandlingLevel.CONFIDENTIAL,
};
