export enum ExternalSettlementDecision {
  SETTLE = 'SETTLE',
  REJECT = 'REJECT',
}

export enum ExternalSettlementStatus {
  POSTED = 'POSTED',
  REVERSED = 'REVERSED',
}

export enum ExternalSuspenseStatus {
  OPEN = 'OPEN',
  HELD = 'HELD',
  CLEARED = 'CLEARED',
}

export const DEFAULT_SUSPENSE_OWNER = 'finance-ledger-suspense' as const;

export const EXTERNAL_SETTLEMENT_SUSPENSE_REASONS = [
  'EVIDENCE_REFERENCE_MISSING',
  'SETTLEMENT_AMOUNT_MISMATCH',
  'SETTLEMENT_CURRENCY_MISMATCH',
  'SETTLEMENT_ACCOUNTING_UNIT_MISMATCH',
  'INTERNAL_ACCOUNT_MISMATCH',
  'SETTLEMENT_ACCOUNT_UNAVAILABLE',
  'STALE_OPERATION_VERSION',
  'SETTLEMENT_KEY_INVALID',
  'DUPLICATE_SETTLEMENT',
  'INVALID_SETTLEMENT_STATE',
  'PARTNER_DISABLED',
  'EXTERNAL_OPERATION_NOT_FOUND',
  'COMPENSATING_NOT_PERMITTED',
] as const;

export type ExternalSettlementSuspenseReason =
  (typeof EXTERNAL_SETTLEMENT_SUSPENSE_REASONS)[number];

export const EXTERNAL_SETTLEMENT_REJECTION_CODES = [
  'EXTERNAL_OPERATION_NOT_FOUND',
  'INVALID_SETTLEMENT_STATE',
  'DUPLICATE_SETTLEMENT',
  'EVIDENCE_REFERENCE_MISSING',
  'SETTLEMENT_AMOUNT_MISMATCH',
  'SETTLEMENT_CURRENCY_MISMATCH',
  'SETTLEMENT_ACCOUNTING_UNIT_MISMATCH',
  'INTERNAL_ACCOUNT_MISMATCH',
  'SETTLEMENT_ACCOUNT_UNAVAILABLE',
  'PARTNER_DISABLED',
  'STALE_OPERATION_VERSION',
  'SETTLEMENT_KEY_INVALID',
  'SETTLEMENT_IDEMPOTENCY_CONFLICT',
  'SETTLEMENT_IDEMPOTENCY_IN_PROGRESS',
  'COMPENSATING_NOT_PERMITTED',
  'COMPENSATING_DUPLICATE',
  'COMPENSATING_REVERSAL_NOT_FOUND',
  'COMPENSATING_SUSPENSE_NOT_FOUND',
  'COMPENSATING_ALREADY_RECORDED',
  'SUSPENSE_NOT_FOUND',
  'SUSPENSE_NOT_OPEN',
  'SUSPENSE_REVERSAL_ALREADY_RECORDED',
  'SUSPENSE_REASON_INVALID',
  'SUSPENSE_OWNER_REQUIRED',
  'LEDGER_ACCOUNT_INACTIVE',
  'LEDGER_ACCOUNT_CURRENCY_MISMATCH',
  'LEDGER_ACCOUNT_UNIT_MISMATCH',
  'LEDGER_BALANCE_INSUFFICIENT',
  'LEDGER_JOURNAL_NOT_FOUND',
  'LEDGER_REPLAY_CONFLICT',
] as const;

export type ExternalSettlementRejectionCode = (typeof EXTERNAL_SETTLEMENT_REJECTION_CODES)[number];
